### ISSUE TITLE
Absentee Trainee Roster Still Resets Tuesday

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1012]
Example: Trainee missing Sat, Sun, and then misses Tuesday. Then the trainee should appear absent for 4 days. 

I am not sure what the best way to do this is. The only thing I think may work is if we duplicate the object Roster instance that we used on Sunday and just duplicate it for a Monday object. So essentially everyone that was absent Sunday is also counted absent Monday logically weather or not this was really the case. That way if they are marked absent Tuesday it iterates through picking up the Monday as a day absent also keeping the loop from breaking. Anyways, any way that we get this working is fine

**Comment by billyeh** [comment]
Discussion moved to #1145
