### ISSUE TITLE
Leave Slip Visual System - Revert to Old Server with New Design

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#1023]
Jerome prefers the old visual system on the old server with the bars as they are more clear about the leave slip status. Please refer below to the color usage.
![ap_spring 18_palette_revision-01](https://user-images.githubusercontent.com/29343365/38710685-7c368aec-3e76-11e8-81b8-dd604e44fa45.png)
![ap_spring 18_palette_revision-02](https://user-images.githubusercontent.com/29343365/38710688-7f40ff1a-3e76-11e8-98d0-b0b11e1d9975.png)

**Comment by finben** [comment]
Got this covered in branch #1050. Will be merged in soon
