### ISSUE TITLE
Bulk modify leaveslips edge case

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#1029]
When you refilter on top of a list of group selected trainees then deselect all, it keeps the trainees selected, but the bulk modifying option disappears. Then if the TA forgets who they had selected to begin with and select someone else, they're still "selected" and their action will bulk modify the unintentionally selected trainees as well.

**Comment by yipingbenjaminliu** [comment]
@francestsenn  , this should be a front end issue, take a look.

**Comment by ruthnan** [comment]
already fixed 3935ccf148db0810955024f640254b8bd44ea054
