### ISSUE TITLE
Exam issues updated

### ISSUE THREAD

**Issue by ksungreborn** [attendanceproject/djattendance#1030]
- [x] 1. **Matching questions:** For Matching questions, we want the ability to have more answer choices than questions (i.e. 9 matching questions and 10 possible answers to select from). The current supposed fix is to add an answer, but leave the point and prompt fields blank. The problem may be on line 234 in utils.py in the exams folder. Also look into hstore for bringing things from the back end to the front end.
- [x] 2. Keep everything on 'Exams' tab and drop 'Current' Tab
- [ ] 3. **Makeup Exams:** Test that makeup exams work. Trainees who needed a makeup exam did not see the exam show up in the tabs at the top of home page. Instead, they had to type in the URL directly to access the test. Also, when a makeup is opened for one trainee, check to make sure that other trainees are not able to take that makeup exam.
- [ ] 4. **Viewing graded exams:** Viewing graded exams has not been extensively tested yet. We should run the process and make sure that this works.
- [ ] 5. **Grading individual questions instead of sections:** Grading from TA side for an exam taken by trainee on the server: TA can only input a grade for a section, not for an individual question (i.e. 3 essay questions for a section, and only an overall score for the section can be given). But, we want TA's to be able to grade individual questions instead of just sections.
- [x] 6. In exam overview, change the Average score to display only 2 decimal values.
- [ ] 7. A trainee who has taken an exam, and a ta then editing the exam causes problem (maybe the solution is to prevent ta from editing exam after exam is opened?)
- [ ] 8. **Duplicate sections:** Some trainees got a duplicate of a single section. For example, when they saved their exam, somehow they got 2 of the same essay section. So, when the TA's went to grade the exam, they were not able to grade it. For the front end to show, we need to list all the sections and when there is a duplicate section, an error will throw. One guess is that the error occurs if the trainee presses the "Save" button twice really fast in succession.

From Raizel:
- [ ] 9. **Exam graders:** 3rd picture (sorry the pics are all bad quality) - As I mentioned yesterday, we'll need to be able to update permissions for trainees to grade. It looks like there was already some structure set up, it just needs to be developed. Sorry for springing that on you yesterday, but I'm glad you were surprised. This is one of the office's best kept secrets. Please keep it that way :)
UPDATE: Exam graders can have the same permissions as TA's
- [x] 10. Other feedback on formatting of instructions and spacing between questions (email from June 5).

**Comment by ksungreborn** [comment]
@ruthnan anything else you found that needs to be done? I remember you were telling me something about multiple choice during ITERO...

**Comment by francestsenn** [comment]
https://github.com/attendanceproject/djattendance/tree/exam-fixes

**Comment by yipingbenjaminliu** [comment]
addressed via #1252
