### ISSUE TITLE
service scheduling

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#1048]
- [x] try to avoid certain combinations of services e.g. 2 breakfast cleanups (prefer 1 breakfast cleanup, 1 dinner cleanup) #1103 
- [x] encouragement doesn't save/show up 43709d633
- [ ] border lines on service report for all trainees
- [x] volunteer slots/appearance for sign in sheets
- [x] page loads pretty slowly 43709d633
- [x] assignment doesn't seem smart. E.g. week of 4/17 ITERO trainees have exception for beginning of week but then end up not having that many services, so chairs is unfilled.
- [x] can't go into manual mode after graph is solved f19867f0ac070e06fa82bb5a83eb7e1de19ccbb2
- [x] need to be able to edit the notes #1102 
- [x] would be nice to fill in chair bros for them. Right now we made the Chairs designated service a Saturday service with workload 3 so that they don't get assigned any other services. So Monday and Wednesday chairs don't get the stars assigned. It's kind of a special case.
- [x] use whole term service frequency as cost 604c26777
- [x] give service schedulers a view showing trainees and workloads for the week to see who's under
- [ ] automate so that services are not assigned based on leave slips submitted (see below)
- [ ] have a way to report service attendance on the server

**Comment by finben** [comment]
Another request related to service scheduling from Jerome is. 
 "Automate so that services are not assigned based on leave slips submitted." Do you understand  what this means or do we need to get more details?

**Comment by billyeh** [comment]
This makes sense 👍

**Comment by billyeh** [comment]
closing,  moving to #1270
