### ISSUE TITLE
TA Feedback 4/15/18

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1053]
Priority Key
HP = High Priority
MP = Medium Priority

**Leave slips:**

- [ ] **Critical Issue:** The calendar no longer shows when pulling up a detailed leave slip view. @billyeh @yipingbenjaminliu 

- [ ] **HP** TA's are unable to change the events on a pending leave slip this should be editable for them  (They cannot change events on group slips. Else, everything is good)

- [x] **MP** Date of last meal out or night out not showing on detailed leave slip view for TA. e59c4853ee43a2c1688337ac4ca1da9ba7e7e12e

- [ ] **MP** There is an inherent issue with how roll and leave slip entries are being shown on the detailed leave slip page. There is no way to tell visually if there is an absence or tardy "under" a leave slip. Right now any approved leave slip changes the color of the event to blue, whether there is anything marked under or not. Please follow the principle of what we had in the old attendance server 

- [ ] **MP** When TA's process a leave slip from the detailed view it moves them on to the next leave slip in their queue which is good. However, when they process the last leave slip left in their queue it has a pop up saying saved and just refreshes them on the same page for that leave slip. Instead they should be redirected back out to the summary page and no popup is needed. 

- [ ] **MP** Numerous night out leave slips being reported as disappearing or moving to the following week on its own. Example: Connor Robinson, Samuel Gutierrez, Nestor Zepeda.

- [ ] Consider possibility of including TA private comments on list view.

- [ ] Add attendance period column on list view.
 
- [ ] TA leave slip detailed view on the detailed view, change fields to Trainee, Reason, Description, TA Comments, TA Informed, TA Assigned, and Private TA Comments.

- [x] On the detailed view, if a trainee says that he did not inform the office, the text only says "No", as opposed to "Training office informed? Yes". Example: http://10.0.8.35/leaveslips/individual/update/1646 Been fixed for a while now 3fb308eeb3bac491ee98671b1d45b0589b16c156

- [ ] Meal cleanup leave slips also excusing trainees from the meals themselves. Not an issue with the start time of the leave slip.

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

- [ ] Saving a leave slip on the _detailed_ view does not progress to the next pending leave slip.

- [ ] When processing leave slips via the detailed view, it would be good to have it automatically ordered so that we process the leave slips dated the earliest first (not the date submitted, but the date the leave slip is for). We had this on the old attendance server.

- [ ] Trainees are able to indicate a Saturday helper as a TA informed, which is fine. However, if they do so, it creates an error where it assigns the leave slip to him. When a trainee then tries to open the leave slip up, it forces them back to the homepage. When a TA tries to approve it, the page times out and gets a 504 error. Example: http://10.0.8.35/leaveslips/individual/update/2044. I think this is related to the prior issue of leave slips being assigned to non-TAs.

- [ ] When a TA inputs attendance for a trainee, the update is not reflected on the trainee's account (i.e., switching identity). Example: Katya Becker on 4/21 from afternoon study to evening study roll out.

**Extra field:**
  - [ ] “Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

**AUDIO**
- [ ] Request to add a notation saying that any files approved for download must be deleted?

**GROUP LEAVE SLIPS**

- [ ] When opening up a group leave slip the events do not have the hashed out selected appearance if there is already something there. We need the hashed appearance on the event to show what the group leave slip is for.

- [ ] Unable to tell who originally submitted a group leave slip. 

**ROLLS:**
- [ ] Add force page when submitting attendance late. 

- [ ] Add save and finalize buttons for personal, house, and team roll entry (even if it is a dummy finalize and save that does nothing since they automatically save).

- [ ] Need unfinalize roll button. Relatedly, the finalize button should be blanked out if attendance is finalized.

- [ ] TAs do not have a way to input team and house attendance. We currently have to go to each individual trainee.

**Web Access Requests:**

- [ ] No way to unmark a request once you have selected marked for fellowship. Needs to be a way to unmark for fellowship to be consistent with site (also noticed on other modules, such as Web Access)

**ROOM RESERVATIONS:**

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this?

- [x] Room choices are not in alphabetical order after editing available rooms. 6b8240be352d7400b64de5083dd0b2396d26c629

- [ ] Updating/editing a trainee's room reservation request approves it

**TA Landing Page**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips 

- [ ] Number of pending requests on TA ***and trainee*** homepages do not match actual number of requests. (Okay we fixed this but the thing is now when they select pending from the home page it actual looks for all sister approved and pending slips which is a good thing but our number is inaccurate again. For the homepage number we need to include slips with TA sister approved status @samvictor232 

**TA List Views**

- [ ] The order of the leave slips on the list view should not be by submission date. They
should be ordered by date of leave slip event, starting with the earliest.

- [ ] On the summary page ("View Trainee Attendance"), the submitted column on the left is extremely confusing. I thought for the longest time it was referring to the event. Please replace it with some sort of tag that just shows if it was submitted late

- [ ] **MP** On the leave slips summary list page, any filters we ask for are lost and default after we process a single leave slip. The filters should be kept

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] For Leave Slip TA list view Add attendance period column on list view.

- [ ] "View leave slips for" on list view includes people who are not TAs.

- [ ] TA Assigned to this leave slip" has a whole bunch of people who are non-TAs. 

- [ ] Across site lists need delete options for items from TA list view

**ABSENTEE TRAINEE ROSTER**
- [ ] Pluses are not being noted on the absent trainee roster. Pluses indicate that there is a possibility the trainee has been absent for more days, but cannot be confirmed due to HCs not submitting a daily accountability form

- [ ] Need a way to show which houses actually submitted the HC survey and which houses did not. Currently, if the HCs do not open the page, they do not show up on the report page, and if the HCs open the survey page, it will list them on the report page even without submitting the survey.

**LIFE STUDIES**

- [ ] **HP** Fix assign discipline based on attendance 

- [ ] For the “Assign Discipline” function for attendance the dates along with the period needs to be shown

**REPORTS**

- [ ] **MP** Generate grade and attendance reports by gospel team and sending locality.

- [ ] **HP** The reports generated and printable for Life-study assignments is incorrect need to meet with Andrew for requirements

**PERMISSIONS**

- [ ] **MP** Saturday helper brothers cannot approve web access requests getting a forbidden error. May affect other modules.

- [ ] Give certain trainees the ability to upload the class files, e.g., ministry meeting verses for PSRP, etc. ( These would be the sisters with the "Special Projects (Outlines)" designated service.)

**BIBLE READING TRACKER**

- [ ] Trainees can finalize their Bible reading without making inputs for all of the days. Example: Mark Fan week 6 /JR - Also see related issue #1011 

**EXAMS:**

- [ ] The word counting feature only worked for the first essay question @ksungreborn 

**Other:**

- [ ] **MP** HC Survey TA's are looking for a way to edit what the survey asks, edit times, and delete the server

- [ ] **MP**Button to change attendance period is only one-pixel large on Firefox. Also not intuitive.

- [ ] Link for TA's to edit HC survey needs to be more intuitive. 

- [ ] We now need to start working on a gospel statistics module

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated.

- [x] Too many trainees can submit linens requests only HC's need this.  Also fixed fora while 5042e50f0468aa6a13c480536c75bd490e2ead7c

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees.

- [ ] **HP** Ensure class notes report page is working after resolving roll/leaveslip issue

- [ ] No organization on HC survey report. Should list all the houses by brothers then sisters. Also, couples do not need to submit surveys, so they should be removed from inputting and the reports.

- [ ] 504 Gateway Time-out error when trying to pull up all leave slips for all TAs, even when limiting to 25 slips per page

**Comment by JoannaRumbley** [comment]
Forwarded from the TAs:

"Please relay to AP team:
The ability to select multiple leave slips for approval has made reviewing leave slips much easier!  I just wanted to send a positive, encouraging note regarding the server this time. Thank you. 
Much grace, 
Andrew
Agreed! Amen!
Walt
Yes, this has been a game-changer for me.
Joseph
"

Great job, AP team! 🥇

**Comment by JoannaRumbley** [comment]
Moved to #1093
