### ISSUE TITLE
Exam word count selection

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1057]
exam word count selector is off, needs to select the right word count for each section

**Comment by iamsitting** [comment]
Forloop counter is not working. They all showed up as count-1 for me.
https://github.com/attendanceproject/djattendance/blob/7499b9e87a46231e0b5b8f0f18992b90f33a0307/ap/exams/templates/exams/essay_question_template.html#L1-L9

**Comment by ksungreborn** [comment]
@yipingbenjaminliu @iamsitting https://github.com/attendanceproject/djattendance/pull/1060 please review and merge!
