### ISSUE TITLE
Exam 500 error

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1058]
Brandon Alfred and Sam Cummings both got 500 server errors submitting on ipad minis. I need to get their browser and ios version numbers. Because Joe Yu submitted on ipad mini with no problem

**Comment by iamsitting** [comment]
Nah it's:
ValueError at /exams/22/take
No JSON object could be decoded

This needs to handle empty responses:
https://github.com/attendanceproject/djattendance/blob/7499b9e87a46231e0b5b8f0f18992b90f33a0307/ap/exams/views.py#L450-L462
