### ISSUE TITLE
Graduation word count doesn't match what it should be

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#1082]
![screen](https://user-images.githubusercontent.com/2067277/39212262-0b0f0fc8-47c3-11e8-8d9d-38470ea3b47a.png)

The text on the right side says 300 words maximum but the actual field in the database is 150 (you can see this in the HTML). We should use `{{form.highlights.field.max_length}}` in the template on this and other fields so that this value updates when we update the code in the model. I don't know whether it's supposed to be 300 or 150 though.

**Comment by billyeh** [comment]
Got someone else to ask Hannah, word count should be 250 and 150 for the last two

**Comment by ruthnan** [comment]
So it was supposed to be 300 words, not characters.

**Comment by iamsitting** [comment]
@bdou I think it's urgent...

**Comment by iamsitting** [comment]
#1085
