### ISSUE TITLE
TA sister approved shouldn't be a leave slip status

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#1104]
It's more like an informational tag, e.g. boolean field. It's just pending, transferred, and it should retain the fact that it was approved by a TA sister. That's the issue with it being a status, since after being approved/denied by the brother they wouldn't know anymore that it had been TA sister approved in the past.

**Comment by JoannaRumbley** [comment]
Also, from the Monday meeting with Jerome:

- [ ] On the detailed view, have different buttons to "Save," "Transfer," and "Approve & Transfer":
- "Save" should save and keep it in their queue 
- "Transfer" should transfer to a TA brother without adding the "TA Sister Approved" tag
- "Approve" button should always transfer to the selected TA

- [ ] On the TA brother side, the "Approve" button should always **save and approve**.

**Comment by AngeloBelUCSD** [comment]
Tested:

On TA Sister Side
- Save
- Transfer
- Approve

On TA Brother Side
- **Approve** should always save and approve

Concerns:
There are two buttons on TA Sister Detail that have the same functionality: "Approve & Transfer" and "Approve".

**Comment by JoannaRumbley** [comment]
Now there's only "Approve & Transfer" and no "Approve" button, so it's not repetitive. It's good. 👍
