### ISSUE TITLE
Django-Admin Replacement (Attendance, Schedules, Leaveslips)

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1105]
- [x] All possible foreign keys need to have a filter for selection f7a80398d4480848c0dc2ae904190a180f8bc893

## Admin Roll update form validation:
- [x] the trainee must have that selected event
- [x] make sure the updated roll does not produce a duplication error
- for trainees on self-attendance, one roll must be submitted by the trainee and another by an attendance monitors
- for trainees not on self-attendance, there can only be one roll at any time

## Admin Schedule update form validation:
- [x] trainee cannot be moved off of a schedule if there are rolls for events on that schedule
- [x] trainee cannot be moved onto a schedule if there are rolls for events on a schedule that it will overlap
- [x] allow AMs to do a schedule split so that no duplicate rolls are produced and no mislink rolls are produced

## Trainee Schedule view:
- [x] Allow view of all the schedules attached to a trainee along with their events and possibly the rolls attached. c5775720d

**Comment by billyeh** [comment]
Having dedicated frontends will also fix our 504 timeout errors 
e.g. `2018/05/02 17:19:32 [error] 30223#0: *1480 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.15.79, server: ap.ftta.lan, request: "GET /admin/leaveslips/individualslip/4992/change/?_changelist_filters=qredactedHTTP/1.1", upstream: "uwsgi://unix:///home/ftta-ap/deployment/ap/ap.sock", host: "ap.ftta.lan", referrer: "http://ap.ftta.lan/admin/leaveslips/individualslip/?q=redacted"` and the possibly related 502 resource unavailable errors

**Comment by yipingbenjaminliu** [comment]
#1118 started this. still need to work on form validation and enforce data integrity constraints.
