### ISSUE TITLE
Leave Slip - Critical Issues 

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1112]
To resolve by Saturday:

1. Approved leave slips are not being reflected on attendance. Example: See Andrew Jen's attendance and leave slips (2257, 2258, 2259) for 3/11. May be due to other leave slips being previously denied for that same roll call.
From Jerome: This still seems to be an issue. I edited #3814 to cover an entire weekend, but denying #4723 and #4725, which had rolls marked overlapping with #3814, caused #3814 not to cover those rolls. 

2. Just tried editing an approved group leave slip, but took me to a 500 error page. Example: http://10.0.8.35/leaveslips/group/update/4224, but not unique to this leave slip.

🐛 --> 🦋  Transformation work

**Comment by davidhtien** [comment]
For point two I think this is because the attendance monitors are doing something illegal through admin, no particular fix to apply before talking to them and figuring out what they're doing

**Comment by billyeh** [comment]
Point 2 is because the service scheduling creates group slips without a TA.

We can change it here: https://github.com/attendanceproject/djattendance/pull/1114/files#diff-87402d2f2246fec85bc4dd1a3424c613R195

**Comment by davidhtien** [comment]
Ah ok makes sense, thanks @billyeh

**Comment by davidhtien** [comment]
@billyeh talked to Benji and he closed #1114 

I don't know if this is what you were suggesting but it doesn't seem like the best idea to assign a default TA to service scheduling slips because it will clutter their inboxes. 

So I'm just editing the form to not require a TA to be assigned

**Comment by yipingbenjaminliu** [comment]
fixed via 377c3fe96aba6e5a4bf4e48d06b2a287e3659328
