### ISSUE TITLE
Graduation Features for Fall 2018

### ISSUE THREAD

**Issue by bdou** [attendanceproject/djattendance#1121]
- [x] Considerations form - Need to add in a field required for fourth-termers to elaborate if they select "Other" regarding attending XB
- [x] Considerations form - Third choice for whether fourth-termers have fellowshipped with locality brothers should be "No, but I am scheduled to fellowship on " with a corresponding required datepicker field. 

Basically: 
![image](https://user-images.githubusercontent.com/6867060/39667347-99d3c520-5068-11e8-8e3b-7c9ef4aea244.png)

- [x] When an XB application is submitted, Hannah would like to receive an alert - I think via email.

**Comment by JoannaRumbley** [comment]
The deadline for this considerations form has passed. 
@bdou Did Hannah tell you these changes need to be made? Maybe I can check with her to find out if the form needs to be changed for this term or next term.

**Comment by bdou** [comment]
Yes, that's why these are features for Fall 2018. But nearer to next term we can ask her if there are any other changes she would like.

**Comment by finben** [comment]
I'm closing this one out. Sorry Hannah no alert coming your way
