### ISSUE TITLE
Front Page of Trainee's absence calculation appears to be off...

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1128]
![jwash1](https://user-images.githubusercontent.com/15247726/39684536-68df84cc-5171-11e8-91ae-507f78d80278.png)
![jwash2](https://user-images.githubusercontent.com/15247726/39684537-6900e360-5171-11e8-8641-22b4f4a01ba8.png)

**Comment by iamsitting** [comment]
Addressed here: dec5abd6bc433abb763223014f676213a4ef7ec8

**Comment by yipingbenjaminliu** [comment]
let's get a few people to test it on the live before we close this

**Comment by JoannaRumbley** [comment]
I think this works now...
