### ISSUE TITLE
Assign LS based on Missed Services

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1131]
Can we work on this functionality - Calculate and assign life studies based on missed services
@billyeh @ryanli633 @samvictor232 

Note:
Missed service is a regular offense (not Monday offense). 1 LS per missed service.
Additionally, trainees who have unexcused missed services also need to make up these services with another service. Any make-up service should be indicated on the missed services sheet in the cafeteria. Trainees who do not make up services may be volunteered for additional services (Info Manual).

**Comment by yipingbenjaminliu** [comment]
#1154
