### ISSUE TITLE
4th term audio still showing up

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1133]

**Comment by ruthnan** [comment]
how about this? 4d48bb208f287391e7ef588f3138e3aaf1eecb75

**Comment by billyeh** [comment]
The code is correct as is, the naming convention just needs to be standardized.

It turns out some brothers wanted a kind of `4T-10 Blah Blah.mp3` format, while others wanted a `FW-10 4T Blah Blah.mp3` format.

**Comment by yipingbenjaminliu** [comment]
These AV brothers need some oneness.

**Comment by yipingbenjaminliu** [comment]
@billyeh , closed?

**Comment by billyeh** [comment]
Not yet. We need to talk to them on Saturday :)

**Comment by JoannaRumbley** [comment]
Are these (below) also because of a wrong format?
- Week 5 God's Economy audio doesn't have the speaker name. 
- Monday Revival Meetings are by "Selection," "Reports," or "Presentations." Should these all use the same word/term?

**Comment by billyeh** [comment]
* There was probably an incorrectly labeled file uploaded first for God's Economy week 5, with no speaker, because there's another file for that week with the speaker.
* Yeah, we don't handle files with no speaker or multiple speakers 100% correctly, it's a little tricky.

**Comment by JoannaRumbley** [comment]
Ok. So there may be a small issue with the day brother Roger Good gave 3 classes in one day (including Greek). That was kinda amazing haha. Anyway, it's not too big an issue since the name of the class makes it clear which class you're selecting.

**Comment by billyeh** [comment]
Closing now. We can open a separate issue in the future for addressing speaker names. Fourth term audios are not showing up anymore.
