### ISSUE TITLE
TA Feedback - Extra Fields

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1141]
**Extra field:**
- [ ] Add "Does not count against perfect attendance" check box and functionality. @AngeloBelUCSD 

 - [ ] “Does not affect perfect attendance will be a built-in leave slip category” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override) @AngeloBelUCSD 

- [ ] Add functionality to "sign out" of Monday dinner via leave slip.

**Comment by ruthnan** [comment]
@JoannaRumbley, it might be good to assign the people as well as tag them on the issue

**Comment by finben** [comment]
Moving remaining issues to #1282
