### ISSUE TITLE
TA Feedback - Absent Trainee Roster

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1145]
**ABSENT TRAINEE ROSTER**
- [ ] Pluses are not being noted on the absent trainee roster. Pluses indicate that there is a possibility the trainee has been absent for more days, but cannot be confirmed due to HCs not submitting a daily accountability form @billyeh @finben 
_Check KW. Marked absent for 5/5 once, but it shows 8+. How is this being counted?_

- [ ] When submitting the daily HC attendance, some HCs are reporting that the system is saying that attendance was already submitted, even though they have not. This is causing a lot of confusion and misunderstanding between the HCs, who said they thought someone already submitted the daily attendance, and the office, who receives the report saying no attendance was submitted.

- [ ] Request to move back the time of the email to be sent to 8:30 @AngeloBelUCSD 

- [ ] Add counter for days that houses go unreported as well but lower priority @ryanli633

**Comment by finben** [comment]
For issue number 1. This would mean that her house monitors have gone 7 days without submitting a house attendance! That is why it would show up as 8+. The + only indicates that we are unsure if she is still out since her HC's have not been submitting their report. This is not an issue per say sine it is just due to her HC's not submitting

**Comment by billyeh** [comment]
We need to update the text on the report to actually say what it's doing. The text is really inaccurate.

**Comment by finben** [comment]
Well really aren't we just tacking on one extra day the Monday? All other days should be submitted. I sent Jerome a text to see what he wants to do. The problem is if a house consecutively fails to submit the data quickly becomes incredibly erroneous....

**Comment by finben** [comment]
Moving remaining issues to #1282
