### ISSUE TITLE
TA Feedback - Life Studies

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1146]
**LIFE STUDIES**

- [x] **HP** Fix assign discipline based on attendance @samvictor232 

- [x] For the “Assign Discipline” function for attendance the dates along with the period needs to be shown @samvictor232 

- [ ] Something is wrong with Summary-Discipline relationship. Alex C. has two summaries attached to a discipline with 1 quantity #1180

- [ ] Have column for Notes. Once a Life-study summary is assigned, there is no way to view the notes that were inputted (e.g., to note what service was missed, the time of mobile phone offense, etc.).

- [ ] Tried to assign a LS summary to individual. Tells us to put in a valid date and time even though a due date was inputted (when they clicked Submit). (Assign to House doesn't seem to have this issue)

- [ ] Add cron job calculation for automatic life study assignment

- [ ] Life Study Report and Monday Report shouldn't have "-1" on the report. Ones that have been completed shouldn't be on the report.

- [ ] There's no way to approve a paper life study

**Comment by JoannaRumbley** [comment]
Is there a difference btween LS report and LS TA view?

**Comment by iamsitting** [comment]
I believe a report view is like a list view and TA view is like a detail view.

**Comment by finben** [comment]
Moving remaining issues to #1282
