### ISSUE TITLE
TA Feedback 5/9 - Permissions

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1148]
**PERMISSIONS**

- [x] **MP** Saturday helper brothers cannot approve web access requests getting a forbidden error. May affect other modules. @billyeh 

- [x] Give certain trainees the ability to upload the class files, e.g., ministry meeting verses for PSRP, etc. These would be the sisters with the "Special Projects (Outlines)" designated service. Natalie Lau, Shirleen Fang, Stacy Castillo, Deborah Chen  @finben

**Comment by finben** [comment]
I am not able to reproduce the forbidden errors the Saturday TA's got. I tried several cases. I am going to mark off as this issue cannot be duplicated
