### ISSUE TITLE
TA Feedback 5/9 - Exams

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1149]
**EXAMS:**

- [x] Once a trainee went on to view the exam (for questions, to start on their exam, etc), it did not allow them to log back on to continue/finish their exam. I believe the workaround for this was to go in and give a trainee “make up exam” privileges.  As of this evening, there were at least 3 trainees that approached me to indicate they weren’t able to log back on to their exams to complete it. @ksungreborn

**Comment by ksungreborn** [comment]
This should be fixed already
