### ISSUE TITLE
TA Feedback - Web Access Requests

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1150]
**Web Access Requests:**

- [ ] No way to unmark a request once you have selected marked for fellowship. Needs to be a way to unmark for fellowship to be consistent with site (also noticed on other modules, such as Web Access) @kcmin

- [x] **MP** The interface for guest web access requests is broken. TAs are unable to input anything into the fields. @yipingbenjaminliu #1232

**Comment by finben** [comment]
Moving remaining issues to #1282
