### ISSUE TITLE
TA Feedback - Room Reservations

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1151]
**ROOM RESERVATIONS:**

- [ ] Marking a request for fellowship removes the request from the list. You have to remove "pending" from the search box and type in "fellowship" or "marked for fellowship". This is too cumbersome and confusing. The list should not be based on a search for "pending". Are there any other modules set up like this? 
_@designers_

- [x] Warning pops up when creating a reservation: DataTables warning: table id=schedule-table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3

________________
COMPLETE:

- [x] Updating/editing a trainee's room reservation request approves it @zioninzion #1224

**Comment by xuefeizheng** [comment]
@isaactsou is working on a mockup page for Room Reservations

**Comment by finben** [comment]
Moving remaining issues to #1282
