### ISSUE TITLE
TA Feedback 5/9 - TA Landing Page

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1152]
**TA Landing Page**
- [x] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips @iamsitting 

- [x] Number of pending requests on TA ***and trainee*** homepages do not match actual number of requests. (Okay we fixed this but the thing is now when they select pending from the home page it actual looks for all sister approved and pending slips which is a good thing but our number is inaccurate again. For the homepage number we need to include slips with TA sister approved status 2122d460fb1abfcc320678100a00146ac21b6f06

**Comment by iamsitting** [comment]
#1170

**Comment by finben** [comment]
I tested and it looks good! Great job, closing this out
