### ISSUE TITLE
TA Feedback - Other

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1154]
@**Other:**
-  [x] We now need to start working on a gospel statistics module @iamsitting @ksungreborn 

- [ ] Trainees added to designated services are not automatically being given links to input designated service hours. @ruthnan 

- [ ] Have a way to take attendance and assign discipline for missed services, rotational or designated. 
#1131 
@samvictor232 

- [ ] TAs need to be able to submit new personal or group leave slips on behalf of trainees. Automatically approved slips when a TA submits. @iamsitting 

- [x] **HP** Ensure class notes report page is working after resolving roll/leaveslip issue @iamsitting #1181  

- [x] **MP** A TA brother received a 500 error after trying to approve a class note submission. @iamsitting 

- [ ] For Maintenence - Change/Add columns to: date requested, trainee requested, trainee Phone, house, room, request type, description, comments, status. @priscilagonzalez 

- [ ] Button to change attendance period is only one-pixel large on Firefox. Also not intuitive. - "Please note this is only on certain systems and it is not a browser version issue. I don't feel we should be spending to much time working on this issue at this point and will re-discuss with Jerome" -ben)

- [ ] Trainees added to designated services are not automically being given links to input designated service hours.

- [ ] Date formatting on TA leave slip list view should match the format on the requests tables. (Should it be "May 05" or "05/05/18 4:52 PM" ?) @priscilagonzalez 
_Update: For all requests: Have "May 05" format on summary lists and "MM/DD/YY 00:00 AM" format on detail views_

- [ ] We would like to have a ticker tape on the bottom of the screens to show announcements and news items, similar to what we had on http://10.0.8.30/ftta/announcements/list.php.  Have options to mark as verbal, server, or commons announcement. (mainly for the TV)
______________
COMPLETE:

- [x] 504 Gateway Time-out error when trying to pull up all leave slips for all TAs, even when limiting to 25 slips per page #1025 @yipingbenjaminliu @davidhtien @iamsitting @billyeh #1184

**Comment by francestsenn** [comment]
Addressed Firefox button issue. Doesn't seem like a problem.

**Comment by JoannaRumbley** [comment]
On Chrome it looks like this:
![image](https://user-images.githubusercontent.com/33075368/40017986-d6a7e554-576f-11e8-8794-30bba57fb2e3.png)

On Firefox it looks like this:
![image](https://user-images.githubusercontent.com/33075368/40018078-13f34da4-5770-11e8-9f2b-527103bb0a92.png)

On Firefox, there's no problem with clicking the number and changing the period, but you can't see the grey down arrow because it's only 1 pixel. (It seems like it's not an issue, but people may not know where they can change the period unless there's a down arrow)

**Comment by billyeh** [comment]
Yeah, that's interesting. On my Firefox it looks fine

![arrow](https://user-images.githubusercontent.com/2067277/40023415-df16df96-577f-11e8-8cca-b3c98111ba8f.png)

**Comment by JoannaRumbley** [comment]
that's weird. I just updated firefox (version 60.0) and the arrow still looks like one pixel.

**Comment by iamsitting** [comment]
@JoannaRumbley for gospel stats module, could we get a spec doc? We're not sure exactly what the TAs want. Same for class notes. I've got class notes working, but not sure if there's more to it.

**Comment by finben** [comment]
Moving remaining issues to #1282
