### ISSUE TITLE
TA Feedback - HC Survey

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1155]
**SURVEYS:**

- [ ] No organization on HC survey report. Should list all the houses by brothers then sisters. Also, couples do not need to submit surveys, so they should be removed from inputting and the reports. @yipingbenjaminliu @iamsitting 
Update: The list now separates brothers and sisters, but it is still unorganized among brother's houses and among sister's houses
______________
COMPLETE:

- [x] Need a way to show which houses actually submitted the HC survey and which houses did not. Currently, if the HCs do not open the page, they do not show up on the report page, and if the HCs open the survey page, it will list them on the report page even without submitting the survey. - Note: It looks like some houses have not submitted the survey, and it is past the deadline. Needs to be fixed and reopened for those houses to take survey. @yipingbenjaminliu @iamsitting
- [x] HP Fix HC Survey Admin Date Input #1156
- [x] MP HC Survey TA's are looking for a way to , edit times, and delete the survey Link for TA's to edit HC survey needs to be more intuitive. 894ab9b e1624bd
- [x] When she clicks the end time field again, it automatically changes the date/time even before she clicks anywhere on the calendar that pops up #1169

**Comment by iamsitting** [comment]
I got this.

**Comment by iamsitting** [comment]
Currently, there is no way to edit the questions on the survey. This feature is more complicated and should be an issue of itself since it would involve a redesign of the entire module.

**Comment by iamsitting** [comment]
@JoannaRumbley Can I get more details about the automatic time change? I can't reproduce it.

**Comment by yipingbenjaminliu** [comment]
@iamsitting it's the same one hour jump as we encountered.

**Comment by yipingbenjaminliu** [comment]
the time is being rendered as 12-hour based but the picker on on military time.

**Comment by yipingbenjaminliu** [comment]
problem references to #1172

**Comment by JoannaRumbley** [comment]
One issue was not completely fixed. See update comment above. @iamsitting @yipingbenjaminliu

**Comment by yipingbenjaminliu** [comment]
added additional order of house names. @JoannaRumbley , keeping this open for now. see if this is okay with the TAs, touch base with them and get back to us.

**Comment by finben** [comment]
Moving remaining issues to #1282
