### ISSUE TITLE
Front-end Admin for Rolls

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1165]
Form validation for the following
### Roll
- Date needs to match the event weekday 99dd2c02dd233eedb385775e537f0499dc3bb8dc
- Roll date and event needs to match schedule week 28b3111c46461aa5f1ad2b631f156acd46b77275
- Priority check for roll event on schedule week 28b3111c46461aa5f1ad2b631f156acd46b77275

**Comment by iamsitting** [comment]
Anything else before I make a PR?

**Comment by yipingbenjaminliu** [comment]
@iamsitting , make sure success url returns the right link and uses the right paramters for the methods it's calling

**Comment by yipingbenjaminliu** [comment]
closed via #1195
