### ISSUE TITLE
HC Survey Critical Issue - Do today! 

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1167]
From Hannah C. in front office:

- [x] When she tries to make a new survey, she can't enter the end time. The error comes up "please enter valid date/time." 

- [x] When she clicks the end time field again, it automatically changes the date/time even before she clicks anywhere on the calendar that pops up

Also, a little less critical:

- [x] When she clicks survey 1 it brings her to a page showing survey 2, and vice versa

**Comment by iamsitting** [comment]
The date/time entry is fixed in #1156. We just need to pull on the live server. @yipingbenjaminliu

**Comment by iamsitting** [comment]
Closing... See #1155
