### ISSUE TITLE
Region / State / Province on City needs some kind of validation

### ISSUE THREAD

**Issue by allenwebb** [attendanceproject/djattendance#118]
https://github.com/attendanceproject/djattendance/blob/dev/ap/aputils/models.py#L34

We need to validate the region field somehow to reduce the likelihood of garbage being entered such as misspellings etc which would make queries and reports difficult. It might be good to create a model for this. It would allow us to have short codes such as CA for California, etc.

**Comment by ricefield** [comment]
fixed in #124
