### ISSUE TITLE
Limit Leave Slips to One Attendance Period

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1185]
When a TA approves a leave slip, they can see which events were chosen by looking at the schedule. But they won't know if it includes events from the following periods unless they change the period to see it.
So a TA could unknowingly excuse trainees for events in future periods. That's not good.

**Comment by finben** [comment]
We need to bring this one up in our discussion Monday with Jerome before we know what he wants to do about this.

**Comment by JoannaRumbley** [comment]
True; hopefully, this issue will have a clearer direction after Monday.

**Comment by JoannaRumbley** [comment]
From Monday meeting:
**Only allow trainees to submit slips for ONE attendance period at a time.**

I'll change the title of this issue to match this.

**Comment by iamsitting** [comment]
#1212
