### ISSUE TITLE
Naming the Audio

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1186]
Continuing from discussion on #1133 

Need to iron out the naming format and make sure each class is labeled correctly (currently, we label them with week #, class name, and speaker). 
- Week 5 God's Economy audio doesn't have the speaker name.
- Monday Revival Meetings are by "Selection," "Reports," or "Presentations." Should these all use the same word?

(This is a minor issue, but it does matter more from a UX perspective. We want people to feel the server is clear and consistent.)

**Comment by billyeh** [comment]
https://mail.google.com/mail/u/3/#inbox/163565813e70bce5

**Comment by JoannaRumbley** [comment]
...?
