### ISSUE TITLE
Trainee Vehicles

### ISSUE THREAD

**Issue by allenwebb** [attendanceproject/djattendance#119]
The Vehicle Model doesn't cover the following scenarios (that have come up during the data import):
1. There are married couples where two trainees share a vehicle **Fix:** make vehicle a many to many key of trainee
2. There are trainees who may use different vehicles at different times (swap it out with their parent's vehicle, etc) and thus have more than one vehicle **Fix:** make vehicle a many to many key of trainee
3. There isn't a capacity field for the number of seats available (used by the service schedulers and bunk selection) **Fix:** add numeric capacity field
4. There isn't a year field (not necessary but it is present in the old data) **Fix:** add year field
5. Some of the colors imported are longer than the 10 character limit. 20 might be a good size.  **Fix:** increase the length of the color field to 20
6. If a state/province model is added to link the city model to, the state field in this model could point to that model. Also some of the license plates are from Canada so make sure not to limit it to only states in the USA.
7. If the relationship between the trainee and vehicle models is changed to many to many, the license plate field should probably be kept unique for each state.
https://github.com/attendanceproject/djattendance/blob/dev/ap/aputils/models.py#L84

**Comment by ricefield** [comment]
fixed in #124 (minus using `ManyToMany` with `Trainee`)
