### ISSUE TITLE
Interim Intention bugs

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#1197]
- [x] There is no link for the TAs to view the summary of the interim intentions submissions, i.e., 'ta_view' url is not available from the cards. Addressed.
- [x] Once the interim intention has set values for dates open/closed, when you reopen the admin url, it doesn't show the set values as default. - Can't duplicate.
- [ ] There is a TypeError "undefined is not an object (evaluating 'e.originalEvent.touches[0]')" when you select the month on the datepicker, and the dropdown doesn't retract when you've selected a month. - Which page and field?
- [x] Why is it so squished on the admin view? i.e., there's a lot of white buffer page. - Need a design.

**Comment by yipingbenjaminliu** [comment]
um...excuse me. Rude. @iamsitting you wrote this thing, finish it.

**Comment by iamsitting** [comment]
@yipingbenjaminliu You messed with the datetime picker.

**Comment by iamsitting** [comment]
Closing. Could reproduce the third item. Re-open if this bug is found again.
