### ISSUE TITLE
For web access requests, mac_address doesn't show up in database

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#1236]
It looks like the computers aren't actually identifiable via their mac addresses. Most of the WARs have "None" as their mac_address in the database.

**Comment by davidhtien** [comment]
ok so this actually makes sense, we only identify guest web access requests by MAC address as an alternative to a user, generally if you get a WAR approved you can activate it on any device as long as you sign onto that device with your account so MAC address isn't super useful. 

`<QuerySet [<WebRequest: [Ot] Bill. Duration: 15>, <WebRequest: [Fs] Justin Yun. Duration: 30>, <WebRequest: [Sr] Tanya Lien. Duration: 120>, <WebRequest: [Sr] Pablo Valenzuela. Duration: 120>, <WebRequest: [Ot] None. Duration: 15>, <WebRequest: [Ot] Angelo Belmonte. Duration: 45>, <WebRequest: [Ot] John Quinton. Duration: 120>, <WebRequest: [Ot] John Quinton. Duration: 240>, <WebRequest: [Ot] John Quinton. Duration: 180>, <WebRequest: [Ot] John Quinton. Duration: 180>, <WebRequest: [Ot] jeffrey chan. Duration: 90>]>`
