### ISSUE TITLE
Updated exam issues

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#1252]
Taken from #1030 , #979 , and #1235, for clarifications ask @ksungreborn 

- [x] Option to make graded exams available separate from making the exam available

from #1030 
- [x] 3. **Makeup Exams:** Test that makeup exams work. Trainees who needed a makeup exam did not see the exam show up in the tabs at the top of home page. Instead, they had to type in the URL directly to access the test. Also, when a makeup is opened for one trainee, check to make sure that other trainees are not able to take that makeup exam.
- [x] 4. **Viewing graded exams:** Viewing graded exams has not been extensively tested yet. We should run the process and make sure that this works.
- [ ] 5. **Grading individual questions instead of sections:** Grading from TA side for an exam taken by trainee on the server: TA can only input a grade for a section, not for an individual question (i.e. 3 essay questions for a section, and only an overall score for the section can be given). But, we want TA's to be able to grade individual questions instead of just sections.
- [ ] 7. A trainee who has taken an exam, and a ta then editing the exam causes problem (maybe the solution is to prevent ta from editing exam after exam is opened?)
- [x] 8. **Duplicate sections:** Some trainees got a duplicate of a single section. For example, when they saved their exam, somehow they got 2 of the same essay section. So, when the TA's went to grade the exam, they were not able to grade it. For the front end to show, we need to list all the sections and when there is a duplicate section, an error will throw. One guess is that the error occurs if the trainee presses the "Save" button twice really fast in succession. #1287 

From Raizel:
- [ ] 9. **Exam graders:** 3rd picture (sorry the pics are all bad quality) - As I mentioned yesterday, we'll need to be able to update permissions for trainees to grade. It looks like there was already some structure set up, it just needs to be developed. Sorry for springing that on you yesterday, but I'm glad you were surprised. This is one of the office's best kept secrets. Please keep it that way :)
UPDATE: Exam graders can have the same permissions as TA's

from #979 
- [ ] finalize for grade -> after changing exam section/question BUG, trainee can’t see exam score after finalized/saved, and exam is finalized on ta side (done in branch exam-fixes)
Other less priority
1. open for makeup for specific trainees
2. generate makeup pdf - trainees that haven’t taken the test yet
3. sort functions (what has been graded, what hasn’t)

from #1235 
- [x] required number of questions to answer can be greater than question count, please validate that field
- [x] filtered class, when returned to does not filter according to selection; eg: select an exam, return to manage exams page, the filter still is selected but the content is not filtered

Additional comments from Raizel (6/19)
- [x] Make instructions not required for a section
- [x] Have the option to preview exam available when editing
- [x] Making exams open outside of editing exam
- [x] Being able to view whether an exam is open outside of editing exam
- [ ] Use fewer words (* if question is required instead of a sentence, removing section titles)

From Questionnaire
- [x] Saving/finalizing an exam causes it to "disappear". The exam should show up as being finalized on the "Exams" page.

~~From Raizel (6/26) -- related to exit questionnaire~~
~~- [ ] A button to retrieve answers to exams and store them in a file.~~

From Raizel (7/13)
- [x] Change the background color of the essay responses to a lighter color (The gray boxes make grading pretty hard on the eyes)
- [x] ~~Work on the "save" function so that comments can be saved without hitting "finalize" (I'm assuming this refers to grading)~~ Comments are not loading properly, so it looks like they weren't saved.

Other
- [ ] Consider calculating total points in an exam from question scores
- [x] Show an actual exam in preview rather than having its own HTML
- [x] Confirm exam finalization
- [ ] Notification bell when saving a graded exam says "invalid scores" even when the score is valid and updated
- [ ] Doesn't allow to submit non-integer grades for paper responses

From Nikki (10/3)
- [x] Default to filtering the exam list by current term

From Nikki (emailed 10/26)
- [x] Some errors when trying to open responses via "Grade Exam". Caused by use of " in comments.
- [x] Some errors when trying to enter scores for handwritten exams.
- [x] Allow trainees to view responses after finalization
- [x] Printing essay exams for review. Response box cuts off text.
- [x] Have makeups show trainee's old/previous responses

From Spring 2019 grading
- [x] Errors when no score is added for the section

**Comment by francestsenn** [comment]
@ryanli633 branch is named "1252/exam-fixes"
