### ISSUE TITLE
Semi-annual module

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#1266]
- [ ] Study location form
- [ ] Study location report
- [ ] Study attendance form #1267 
- [ ] Study attendance report #1267

**Comment by yipingbenjaminliu** [comment]
I'll take care of study attendance

**Comment by iamsitting** [comment]
We need attendance form ASAP. The location form model should at least be there.

attendance form & report
http://attendance.ftta.lan/ftta/semiAnnual/studyAttendance.php
http://attendance.ftta.lan/ftta/semiAnnual/viewAttendance.php

location form & report:
http://attendance.ftta.lan/ftta/semiAnnual/studyLocation.php
http://attendance.ftta.lan/ftta/semiAnnual/studyLocationReport.php

**Comment by iamsitting** [comment]
#1283
