### ISSUE TITLE
Present rolls on table entry

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#1269]
Present rolls are showing up on team roll tables for team monitors (i.e Greg Lee).

**Comment by yipingbenjaminliu** [comment]
yea, it's supposed to be there, did he input it as anything else?

**Comment by yipingbenjaminliu** [comment]
It's probably associated with a leaveslip

**Comment by iamsitting** [comment]
Yeah I figured. But that's not clearly conveyed.

**Comment by yipingbenjaminliu** [comment]
okay, i'll do something about it
