### ISSUE TITLE
Gospel Trips Testing Bugs/Issues

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1278]
- [x] I was unable to log on to the server as anyone until I went into an incognito browser to get to the admin page and create an initial dummy data gospel trip. This is because gospel_trip/context_processors.py line 14 gets hung up if there is not an existing gospel trip in the database https://github.com/attendanceproject/djattendance/pull/1177/commits/a10f87a5090f7113bb77faf994d72e9ebb598380
- [x] When editing an existing gospel trip the submit button is leading to a blank page https://github.com/attendanceproject/djattendance/pull/1177/commits/a10f87a5090f7113bb77faf994d72e9ebb598380
- [x] When trying to look at the gospel trip as a trainee got a error
 TypeError at /gospel_trips/trip/1 string indices must be integers
workspace/djattendance/ap/gospel_trips/forms.py in __init__, line 39

**Comment by iamsitting** [comment]
These are all addressed.
