### ISSUE TITLE
Design: Tag colors

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#1299]
**Current server:**
<img width="225" alt="screen shot 2018-06-28 at 3 05 51 pm" src="https://user-images.githubusercontent.com/29343365/42063056-cf86732e-7ae4-11e8-82aa-52af660b1656.png">

**Mock up:**
NOTE: Boxes should not have rounded corners.

![tags](https://user-images.githubusercontent.com/29343365/42063009-9164c3fc-7ae4-11e8-8b64-d4f028325eb8.png)

**Comment by bdou** [comment]
#1333
