### ISSUE TITLE
Design: Highlight color

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#1300]
**Current Server**
<img width="1230" alt="screen shot 2018-06-28 at 3 08 17 pm" src="https://user-images.githubusercontent.com/29343365/42063165-4a74d86e-7ae5-11e8-9513-f028973c7b37.png">

- [ ] Please use #d8e5eb (very light blue) as the highlight color instead of the current dark tan color

**Comment by bdou** [comment]
#1333
