### ISSUE TITLE
"No module named dj_static" when runserver on Vagrant box

### ISSUE THREAD

**Issue by thunderrabbit** [attendanceproject/djattendance#131]
Steps to reproduce

0. have VirtualBox 4.3.26 and Vagrant 1.7.2 installed
1. `git clone https://github.com/openteam-tusur/attendance.git`
2. `cd attendance`
2. `vagrant up` 
3. `vagrant ssh`
4. `cd ap`
5. `python manage.py syncdb --settings=ap.settings.dev`
6. `python manage.py runserver 0.0.0.0:8000 --settings=ap.settings.dev`

[[snip](http://pastebin.com/F45znwxn)]

django.core.exceptions.ImproperlyConfigured: WSGI application 'ap.wsgi.application' could not be loaded; Error importing module ap.wsgi: "No module named dj_static"
^C(ap)vagrant@vagrant-ubuntu-trusty-64:~/ap/ap$ exit

[full log](http://pastebin.com/QKLyBhmd)

host OS is Mac OS X 10.10.2

**Comment by ricefield** [comment]
@jonyao can you comment on this? my impression this that this is just a problem with the `requirements.txt` files.
