### ISSUE TITLE
Gospel trips - test

### ISSUE THREAD

**Issue by priscilagonzalez** [attendanceproject/djattendance#1310]
Gospel Trip Creator

- [x] Need steps for user to create questions and instructions under sections, or make it more intuitive with required fields. 3ccf20084f2e0870fae40ba6a51e8cc16555c758 - better navigation
- [x] After saving or deleting, it goes to a blank page. It needs redirection. cb15257148ff050b21e039cd1fb2af8d964ffc54 - show errors
- [x] When you are on the Preview page, there is no way to return to the Gospel Trip Admin page 01ea045348d18359a09f7d5c6006075ac64f58bb -- buttons
- [x] No field name needed for Instructions section bcc56d2d25afb8af4598678e826bbdf0e934a951 -- removed this model
- [x] Close time should not be earlier than Open time bcc56d2d25afb8af4598678e826bbdf0e934a951
- Insert/Edit image: 4287490b3
  - [x] General tab: the field Source uploads the image, but it still says _Failed to upload image: Invalid JSON: {"success": “True"}
  - [x] Upload: Both “Browse for an image” and “drop an image here” do not work. _Invalid JSON: {"success": "True”}
- [x] if the user needs more than 1 section/instruction/question, he needs to submit and then go back to the page; should he be able to add multiple questions without pressing “submit” after each change? f3f0e13907fd075a84493215c5e226c8f7989687 -- duplicate function (never start from scratch)
- [ ] Should not allow “submit” without filling out any field - also, should we have both “save” and “submit” buttons?
- [ ] Delete shouldn’t be a check box. Is it supposed to be a panel of buttons to the right, like the other pages?

**Comment by JoannaRumbley** [comment]
New review and issues on #1337
