### ISSUE TITLE
`npm run build` failing. New babel version removed stage presets

### ISSUE THREAD

**Issue by alextricity25** [attendanceproject/djattendance#1320]
Hey, guys.

I'm going through https://github.com/attendanceproject/djattendance/wiki/Automated-installation-(Ubuntu-14.04). I've only run into a few bumps i've already worked through, but one seems to be predominately apparent across all travis ci jobs and my local build:

```
ERROR in ../ap/templates/bundles/index.js
Module build failed: Error: [BABEL] /home/alex/Development/djattendance/ap/templates/bundles/index.js: 
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
for more details. TL;DR is that it's more beneficial in the
  long run to explicitly add which proposals to use.

For a more automatic migration, we have updated babel-upgrade,
https://github.com/babel/babel-upgrade to do this for you with
"npx babel-upgrade".
```

The `packages.json` file pins babel core to 7.0.0-beta.46, however still version 7.0.0-beta.56 is being installed on my system:
```
npm list | grep babel
├─┬ @babel/core@7.0.0-beta.56
```
It seems npm is not respecting beta pre release identifiers in the package.json file and installing the latest pre-release anyway.

**Comment by iamsitting** [comment]
Hey @alextricity25 , Yeah the Ubuntu installation guide hasn't been maintained since most of us run on Mac, so there may be several bumps. I've noticed the travis-ci build fails too. My system installs beta.51 which is fine. But I really haven't had a chance to look at it. I guess we just have to run: "npx babel-upgrade". Let me know if you figure out a solution. Thanks.

**Comment by alextricity25** [comment]
> I guess we just have to run: "npx babel-upgrade"

@iamsitting Sure thing. I'll take a look to see if that tool will help us out here.
