### ISSUE TITLE
Travis Fail

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#1338]
Let's fix this:
Command "git clone -q git://github.com/billyeh/HtmlTestRunner /tmp/pip-HCzTtN-build" failed with error code 128 in None
The command "pip install -r requirements/test.txt" failed and exited with 1 during .

**Comment by yipingbenjaminliu** [comment]
resovled by #1343, i think that the build was failing because of the duplicate naming of the custome template tags
