### ISSUE TITLE
Possible Email Mixup on Import?

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1380]
It appears that when the trainees go on and change their password, they are able to access everything (even though it is very slow in loading certain pages) until about Thursday, 8/23. However, today when they tried to login, they weren’t able to. When Andrew went in to admin with a desire to reset their password, he noticed that their email address was changed to the email of their emergency contact (e.g. Christian Wilks’ mother’s email was listed and Phoebe Chang’s father’s email was listed). Joe wondered if the email fields got mixed up when you did a new import on Saturday, 8/25.

**Comment by finben** [comment]
New request on bug sheet. Hopefully someone can take a look

**Comment by iamsitting** [comment]
Not a mixup on our side. The import file that I was given had those emails. So the mixup was on the MS Access.
