### ISSUE TITLE
Issue with Team Rolls

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1388]
Joseph Hernandez marked two people on his team tardy on Friday Home Mtg 6:30 PM. But after finalizing the entire team got set to Tardy and was finalized.... I reset through going under Sven's account and marking some with P's. However if I reset them to blank they would stay as tardies. 

Apparently the office is getting notified by multiple team monitors that this is happening.

**Comment by JoannaRumbley** [comment]
My HC also mentioned this issue with house roll once.
