### ISSUE TITLE
Bug Fix Request 09/09/18

### ISSUE THREAD

**Issue by AngeloBelUCSD** [attendanceproject/djattendance#1402]
By Austin Anderson

Non Critical Bug
Description
Designated hours task performed box. Max # of characters allowed in field is 141, throws error indicating a 140 max char limit. Likely an off-by-one-error

**Comment by davidhtien** [comment]
May or may not be related to a bug on life-studies, @kcmin reported that you need 251 words to submit a LS

**Comment by joysyu** [comment]
I think this has been fixed! I cannot reproduce it and there's a 140 max char limit.

**Comment by finben** [comment]
Let's close it out. Fixed
