### ISSUE TITLE
Let's make a production.py so we don't have to keep appending --settings at the end

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#142]
Trying to get ride of this insanity:

```
python manage.py runserver --settings=ap.settings.dev
```

We can make a separate file called production.py that has the production setting hardcoded. This way we don't have to always indicate settings at the end by default. Friendly to beginner programmers who are copy-pasta'ing django code.

So, only in production would we run this:

```
python production.py runserver
```

See this for examples:
http://stackoverflow.com/questions/8318688/django-manage-py-settings-default

**Comment by radicalray** [comment]
@ricefield Give me the green light and I'll just do it now.

**Comment by ricefield** [comment]
@radicalray best practice in this instance is to just set the `DJANGO_SETTINGS_MODULE` environment variable. Realistically, no one should be appending a `--settings` flag at the end of every `manage.py` call. The stackoverflow discussion you link to discusses this approach.

This can easily be done using `virtualenv`. With `virtualenvwrapper` I just put the line `export DJANGO_SETTINGS_MODULE="ap.settings.dev"` in my `postactivate` script. Alternately, you can modify your `manage.py` (not advised). 

Then in production or staging, we simply set `DJANGO_SETTINGS_MODULE` to `ap.settings.prod` or `ap.settings.staging`

**Comment by radicalray** [comment]
Ok, just tested. If you use --fake. It does the right thing. Direct quote from the website: https://docs.djangoproject.com/en/1.8/topics/migrations/

That’s it! The only complication is if you have a circular dependency loop of foreign keys; in this case, makemigrations might make more than one initial migration, and you’ll need to mark them all as applied using:

```
python manage.py migrate --fake yourappnamehere
```

This is true in our case b/c we have more than "0001_initial" for each app due to circular dependencies.
