### ISSUE TITLE
Self-Attendance bug

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1422]
Concerning trainees getting put on self-attendance midway through the term:

- [ ] Take away the notification requesting them to submit attendance for previous weeks

- [ ] Ensure that attendance statistics remain accurate

- [ ] On personal attendance (and on View Leave Slips on the TA side), all their previous tardies and absences have disappeared from the calendar

**Comment by iamsitting** [comment]
@davidhtien @yipingbenjaminliu Any ideas? I'm thinking about creating a new model:
SelfAttendancePool
- trainees: M2M
- weeks: csv
- term: Term

This would be how we manage self-attendance trainees week by week. Very similar to schedules.

**Comment by yipingbenjaminliu** [comment]
I don't think there's a need to create a new model to address the issue. Just ask the AMs what they would want to do with the existing rolls and implement the change into the following:
https://github.com/attendanceproject/djattendance/blob/0201a936e1bd3bc17fd7a7df72192d2afad54757/ap/attendance/views.py#L310-L315

**Comment by iamsitting** [comment]
They want to preserve their existing rolls. So there needs to be a way to track when the trainees were put on self-attendance.

**Comment by yipingbenjaminliu** [comment]
@iamsitting, if they want to preserve their existing rolls, then creating a new model would probably be the best solution as they're introducing new information for us to keep track of. Build the model, I can implement the processing in views.

@davidhtien , thoughts?

**Comment by JoannaRumbley** [comment]
Obsolete due to change to single roll attendance system
