### ISSUE TITLE
All Graduation and Interim Intentions Issues

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1430]
*Interim Intentions*
- [x] Report is including all the data entered by the trainee. For example, Sawyer Zachary has "Returning" as his intent to return, but also "Other/Undecided (explain)" under his intention and some comments related to his interim plans. I looked at the interim intentions form through his profile, and it seems like he had written the comments under "Unsure if I will be returning," but ultimately clicked "Returning" and submitted. On the report, it should probably only display the data related to the trainee's final selection.

- [x] The form on the old attendance server asked for specific information from the trainees based on which option they chose under Post Training Intentions (which translates into "Intentions" on the report in the new server), and not just "Explain:". Most trainees did not provide information such as the locality they will end up in for work, what school and program they will be enrolled in, what campuses they will be serving at, or when they will start serving.

- [x] Missing calendar report.

*Graduation*
- [ ] May need functionality to be able to edit the questions and for a TA to see what the trainee sees. _TAs still want this..._

**Comment by JoannaRumbley** [comment]
Closing this. Opened a new issue for graduation module. #1639
