### ISSUE TITLE
More issues hit on migrate in 1.8

### ISSUE THREAD

**Issue by haileyl** [attendanceproject/djattendance#144]
Hit the following problems when running migrate (after commenting out python-coveralls).  Apparently fixed in django-next, but running into other issues when using the most current bits.

https://github.com/lukaszb/django-guardian/issues/303

@ricefield @radicalray

**Comment by ricefield** [comment]
I'm not quite sure what you're linking to @haileyl . I don't think we have `django-guardian` in our codebase right? Where is this error surfacing? 

IIRC, I fixed something like this recently... https://github.com/django-extensions/django-extensions/pull/671 referencing the same issue. You could probably do the same by opening a pull-request on whatever third-party module is throwing this error. If it's nonessential, we can consider to remove it.

**Comment by radicalray** [comment]
@haileyl Is this issue resolved?
