### ISSUE TITLE
Django 1.8   AttributeError: 'Options' object has no attribute 'module_name'

### ISSUE THREAD

**Issue by snowboarder003** [attendanceproject/djattendance#145]
Problem - Django extension using deprecated name. (using module instead of model which was changed in 1.8)

Fix -
1) Edit file local/lib/python2.7/site-packages/django_extensions/admin/__init__.py
2) Change line 63: 
   info = self.model._meta.app_label, self.model._meta.module_name
    to 
   info = self.model._meta.app_label, self.model._meta.model_name

@ricefield @radicalray

**Comment by ricefield** [comment]
see https://github.com/attendanceproject/djattendance/issues/144 and https://github.com/django-extensions/django-extensions/pull/671. Likely just need to update `django-extensions` to 1.5.5 (currently at 1.5.3)

**Comment by ricefield** [comment]
@snowboarder003 @haileyl FYI, you don't want to do edit anything in your `site-packages` folder. It may work as a hack to get things running, but it won't work on a fresh deploy. In this case, update the package, remove it if it's nonessential, or submit a PR to patch the package in question.
