### ISSUE TITLE
Meal Seating Issues (On-Board Issues)

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#1506]
- [x] This issue is for one of the on-boarding trainees. We need to get the meal order print out in alphabetical order down the column instead of being alphabetical by row. If you look at the meal seating chart in the cafeteria you will immediately see what I am talking about.

- [x] Recently, when the meal seating sisters generated based on date of birth it did it by year instead of month/day. Obviously, this is awkward as all the 30 years olds were sitting together. Needs to be changed

- [x] Bonus - - Add more variables for them to generate meal seating by

**Comment by iamsitting** [comment]
For DOB meal seating: https://stackoverflow.com/questions/4236226/ordering-a-django-queryset-by-a-datetimes-month-day
