### ISSUE TITLE
Get rid of Deprecation Warnings and speed up code reload

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#152]
Current dev branch has very slow code reload/refresh rate perhaps due to all the django 1.9 deprecation warnings. Let's get rid of that.

**Comment by billyeh** [comment]
Just realized this is what I was working on in the [https://github.com/attendanceproject/djattendance/tree/quash-startup-errors](quash-startup-errors) branch.

:) all startup errors gone. Unfortunately, didn't get the last step of upgrading django to 1.10 to work.

**Comment by billyeh** [comment]
Mission accomplished #436

**Comment by radicalray** [comment]
Great work! Don't stress out about upgrade to 1.10 since 1.8 has long-term support and it feels that django gets more and more unstable as you get closer to Dev. -.-

**Comment by billyeh** [comment]
Yeah, just upgraded libraries, switched to non-deprecated functions basically.

Loads a little faster now but it's not instant or anything. Although my computer actually seems on the slower side.
