### ISSUE TITLE
Self-attendance not finalizing

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1546]
Ady Garcia has not been able to finalize her attendance for 2-3 weeks. After she clicks Finalize, the notification still shows up on the home page. She uses Chrome, so it shouldn't be a browser issue.
She talked with Megan (attendance monitor), who reproduced the same issue on Ady's account. Megan was able to help her finalize, but she's had to help her with the same issue for 2-3 weeks now. Apparently, Megan said this has happened to a few trainees.

**Comment by joysyu** [comment]
Doesn't seem to be a problem for now.
