### ISSUE TITLE
Book collection should include order?

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#155]
This way, we can list the life study collection in a particular order and suggest next books to do life study on.

@ricefield

**Comment by ricefield** [comment]
@radicalray it's an interesting idea. any reason why we can't just follow volume number, or bible book order? 

this model was originally meant to be used in conjunction with the syllabus and book pre-order functionality, with the possibility of building out library book-tracking functionality in the future

**Comment by radicalray** [comment]
@ricefield I didn't think of using the volume numbers but maybe people would get lazy to put in the volume number for some books in collections? Also, is the volume number guaranteed to be in collection order. I've heard of books being inserted in the order post publication to insert lost/missing messages given. In which case, the volume number wouldn't be in order.

**Comment by ricefield** [comment]
@radicalray haha, in which case, do you think it's worth the trouble to go investigate the "collection order"? At the end of the day, we're not really building a ministry reading tracker or recommendation engine.

**Comment by radicalray** [comment]
It's just an optional field we leave, not mandatory order but if people want to add order in the future won't be hard to do. 

Ray
