### ISSUE TITLE
Life study wordcount not working

### ISSUE THREAD

**Issue by kcmin** [attendanceproject/djattendance#1555]
![image](https://user-images.githubusercontent.com/12653261/50300754-3e384480-043a-11e9-869a-0475e8f0f995.png)

![image](https://user-images.githubusercontent.com/12653261/50300704-10530000-043a-11e9-9d2f-cae74da54594.png)

When submitting life studies, the word count is not working, see photos. Trainees aren't able to submit life studies if the word count is <250

**Comment by iamsitting** [comment]
#1557
