### ISSUE TITLE
Model optimization

### ISSUE THREAD

**Issue by ricefield** [attendanceproject/djattendance#159]
@radicalray, @davidhtien let's look through the model and figure out where we can denormalize or otherwise shore up inefficiencies in our model design. Create an issue for it (so we can discuss) and use the label "Model Cleanup". Then link it here so we have a collection of all the proposed changes. 

List:
* consolidate locality model: https://github.com/attendanceproject/djattendance/issues/153

**Comment by radicalray** [comment]
Good idea! :+1:  I'll let David Tien spearhead this and throw in some input along the way. @ricefield @davidhtien
