### ISSUE TITLE
Completed TA Issues

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1603]
Here are TA issues that have been completed. Each issue should have the date they were **posted**.

- [x] **HP** Web access module not working.  3/2/19

**Comment by poohbear0628** [comment]
@JoannaRumbley I don't think the room reservation issue has been resolved, at least not when I spoke to @kcmin about this issue on Sat service time.

**Comment by JoannaRumbley** [comment]
I think he was talking about the other room reservations issue. This one is fixed already. :)
