### ISSUE TITLE
Trainee import tool or Rewrite FTTA Online Application

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#164]
May be easier to rewrite online Application than writing a custom half-broken importer.

@ricefield @lifedispenser @davidhtien @snowboarder003 @leonardlan

**Comment by ricefield** [comment]
We've discussed this before, and the decision was that we should rewrite. Unfortunately, no one has been able to pick it up.

cc: @lifeunion and @jonyao

**Comment by yipingbenjaminliu** [comment]
We'll be taking the approach of using Python scripts to do import. We still need to rewrite the application when the new server settles down
