### ISSUE TITLE
We need an internal wiki to put training-sensitive info for devs in the future

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#165]
We need an internal wiki to put training-sensitive info for devs in the future

@ricefield @lifedispenser @snowboarder003 @davidhtien @schai6 @leonardlan

**Comment by ricefield** [comment]
@radicalray what kind of sensitive info do you imagine would go there?

**Comment by radicalray** [comment]
Maintain server in production. Notes of who to ask for password and username. How to fix old server bugs. Internal design docs for how our algorithm works. I don't want to publish it in public so won't be seen by other trainees.

**Comment by ricefield** [comment]
@radicalray this is kind of what the Dropbox is for I guess. I would recommend using that, to avoid cluttering too many tools to keep track of.

**Comment by radicalray** [comment]
We may not always have internet connection to look up internal network structure, etc. Pretty frustrating if it's not locally hosted in the training. @ricefield

**Comment by ricefield** [comment]
yeah this is why we were using AeroFS at one point, which synced purely over LAN, but that got expensive fast. I think there's a good point to that, but nevertheless, I'm wary of adding yet another tool to keep track of. Dropbox, at the very least, syncs to your local drive, and it's not like documentation changes that often. 

Anyways, that's my 2cents. really up to you guys.

**Comment by radicalray** [comment]
Internal wiki up and running! Using Django Wiki. PTL!
