### ISSUE TITLE
Web Access Requests - Ordering the List by Date

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1656]
I haven't noticed it happen before, but the way the web access requests are listed is weird. Until recently, I thought the most recent ones were at the bottom (which already seems backward to me), but my recent requests have been out of order. See picture:
![image](https://user-images.githubusercontent.com/33075368/57892480-e2f55d00-77f3-11e9-96bc-806a676f655f.png)

**Comment by Plew** [comment]
Strange, the code that sorts that is a template used by every request list. Its under templates/requests/request_list.html. It shouldn't have changed. I'm thinking its a problem with packet loss, if we can reproduce it I will look into it, but probably not a concern.

**Comment by JoannaRumbley** [comment]
Ok...it doesn't stop users from doing what they need to do, so it's low priority. Will close the issue until or unless the TAs mention it.
