### ISSUE TITLE
TA to edit slip from personal attendance

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1662]
When a TA is viewing a leave slip via a trainee's personal attendance, there is no way to change the leave slip on that page. The TA has to go to the "View Leave Slips" page to change it. It's very tedious for them. 

- [x] If the user is a TA, when they click on a specific slip from the personal attendance page, open a new tab with the TA view of the details of that slip. (They can change it on the detailed view, which is found in the details of a slip listed on the View Leave Slips page.) This fix may require work with react.js

**Comment by joysyu** [comment]
This was fixed in #1635
