### ISSUE TITLE
Urgent Issue - Attendance/Leave slips

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1674]
From Jerome:

I tried inputting Julius Chang's attendance for 5/29. For some reason, when I clicked the two TF roll calls, plus Study, Din, Min Meet, and Prayer to mark him absent, nothing would happen. However, when I viewed his attendance on his account, I saw that the absences went through. This is similar to the second part of the leave slip on 3/22 "Attendance: Leave Slips" starting "Pulling up Isaac...". This is a fundamental issue that needs to be corrected a.s.a.p. I have e-mailed you screenshots as well.

As Jerome said, this may (or may not) be related to previous issues about the TA and trainee views being different when viewing leave slips. For example, there was this previous bug that hasn't been addressed:

Pulling up Isaac Tsai's night out leave slip for 3/10 shows ...no roll calls marked, despite the trainee marking the roll calls when he submitted the leave slip. (I added the rolls to the leave slip so that he wouldn't be assigned discipline.)

TA View:
![juliuschang-taview](https://user-images.githubusercontent.com/33075368/59080827-a7ecc380-889f-11e9-8a15-cb68703181f2.jpg)

Trainee View:
![juliuschang-traineeview](https://user-images.githubusercontent.com/33075368/59080834-ade2a480-889f-11e9-91a6-806c5c6e3576.jpg)

**Comment by JoannaRumbley** [comment]
Not sure who to assign for this... 
Any ideas as to what might be causing this inconsistency between the TA  and trainee views?

**Comment by joysyu** [comment]
Hmm I haven't been able to reproduce this... @JoannaRumbley Can you attach the screenshots he emailed? Thanks!!

**Comment by Plew** [comment]
I also cant reproduce the issue. Submitting roll for Julius on that specific day and rolls works on live and local for me.

**Comment by Plew** [comment]
JK literally 5s after typing that we realized it was due to the server running out of space.  This is completely not related to those other issues.
