### ISSUE TITLE
Deleting web access requests

### ISSUE THREAD

**Issue by francestsenn** [attendanceproject/djattendance#1676]
Allow web access requests not associated with a user to be deleted. Currently, deleting web access requests made by non-trainees (like short-termers) is throwing errors.

Internal Server Error: /web_access/delete/3997

NoReverseMatch at /web_access/delete/3997
Reverse for 'user_detail' with arguments '(None,)' not found. 1 pattern(s) tried: ['accounts/(?P<pk>\\d+)$']

Web access requests that have thrown errors: 3929, 3137, 3138, 3139, 3997

**Comment by joysyu** [comment]
@francestsenn whose account can i use to reproduce this?

**Comment by francestsenn** [comment]
@joysyu I don't think you need to be logged in to any account. I'm not sure why, but I wasn't able to replicate the problem on my local server. On the live server, I got an error when I made and tried to delete a guest web access request that's on the login page. I'm not sure what's going on, but I get redirected to the 504 page
