### ISSUE TITLE
Exams

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#1695]
- [x] Trainees should not be able to finalize exam responses after TAs close the exam, even if the trainee has that exam's page open

- [ ] Any open exams should automatically close after the term ends

**Comment by hannah-g-chen** [comment]
@francestsenn , do the exams automatically close after the term ends? Just wanted to make sure.

**Comment by francestsenn** [comment]
@hannah-g-chen Exams do not automatically close, and there's not an easy way to do this. However, TAs can now easily see which exams are open and close them. The issue beforehand was that there was no way to tell that exams were still open from the TA side.
