### ISSUE TITLE
Leave Slips Checkbox for TA's

### ISSUE THREAD

**Issue by hannah-g-chen** [attendanceproject/djattendance#1697]
When changing the reason of a leave slip, particular between a reason that does not count against perfect attendance and a reason that counts against perfect attendance (or vice versa), the check box indicating whether it counts against perfect attendance does not update. This can be deceiving, as we assuming this would automatically be reflected once the reason is changed.

@appletreeisyellow

**Comment by appletreeisyellow** [comment]
@hannah-g-chen Can you give me a list of reasons that doesn't count against perfect attendance?

**Comment by appletreeisyellow** [comment]
@hannah-g-chen Never mind! I got them. The reasons that don't count against perfect attendance are service, conference, team trip, and fellowship.
