### ISSUE TITLE
Semi Annual Module

### ISSUE THREAD

**Issue by hannah-g-chen** [attendanceproject/djattendance#1703]
- [x] The study location report does not include trainees who have not submitted responses. It needs to.

- [x] Also, after approving or denying a semi-annual study location request on http://ap.ftta.lan/semi/location-report/, the order of pending, approved, and denied requests are random.

@francestsenn

**Comment by francestsenn** [comment]
To address the first issue, we'll add the responses at the start of the term. I'm adding those for this term.
