### ISSUE TITLE
Term upgrade each import

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#172]
How do we upgrade / increment term number for each training at the beginning of each term. I'm particularly interested in the edgecase when a trainee leaves the trainee mid-term and comes back at a later time so auto-incrementation may not work properly.

Did we design for these edgecases from the outset?

@ricefield

**Comment by ricefield** [comment]
I'm not 100% sure if we have built a mechanism for this behavior yet, so you're free to devise it. My guess is that it should just be a part of the scripts that we run at the beginning of every term, just like what we currently doing of `attendanceproj`

Do you have more edge cases you think we need to handle? At least for the one where a trainee leaves mid-term, these are infrequent enough that the office knows to handle them individually, so we don't have to account for it in the code.

**Comment by ricefield** [comment]
@radicalray i think the best way to tackle this is to create an app for term creation/migration. e.g., `/newterm` and put all the logic and UI in there together. maybe one of the PMs can pick this up?

**Comment by radicalray** [comment]
@elijyl @haileyl ?

**Comment by rayoowoo** [comment]
Import cases (that I could come up with):

**Beginning of the term:**
_Returning trainees from previous term:_
Changed housing
Changed teams
Changed TAs
Changed personal information (home address, phone number, etc.)
Changed account types
Changed schedules

_4th trainees who are leaving (deactivated)_

_Non-4th termers who leave the training (deactivated)_

_Returning trainees after hiatus_
Changed housing
Changed teams
Changed TAs
Changed personal information (home address, phone number, etc.)
Changed account types
Changed schedules

**Middle of Term:**
_First-terms receive their teams_

_Trainee information changed (mainly in groups):_
Changed housing
Changed teams
Changed TAs
Changed personal information (home address, phone number, etc.)
Changed account types
Changed schedules

_Short-termers who become full-time_

_Mid-term trainees who leave on their own_

_Trainees asked to leave_

**Comment by haileyl** [comment]
Right now, we get the term in the CSV file, and our plan is to just read it and save it.  There have been trainees that have completed one term, and then come back again as a first-termer, so it's definitely not something we can calculate based on how many terms they're attached to.  In the future (in a world where we no longer have the office DB, if that ever happens), we can auto-increment this value and manually adjust it if there are special circumstances.
