### ISSUE TITLE
Prepare for production deployment

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#176]
Here are some note links when we want to deploy django. Will be better to write automated script to manage our servers and deployment cycles. The popular one on the internet is fabric scripts. 

So, we need to figure out:
 - [x] static file server
 - [ ] automated git pull / build, migrate, runserver process in a headless state
 - [x] db backup strategy (HD failures)
 - [ ] Not running django as sudo root user?

Here are some links I'll read later:

https://www.djangopackages.com/grids/g/deployment/
http://www.robgolding.com/blog/2012/01/14/django-in-production-part-3---automation-and-monitoring/

http://www.mattmakai.com/presentations/2014-san-fran-django-ansible.html#/ -> ansible

http://python-deploy-framework.readthedocs.org/en/latest/pages/django-deployment.html

https://django-fab-deploy.readthedocs.org/en/0.7.5/guide.html -> fab deploy

https://www.orchardup.com/

@ricefield @lifedispenser

**Comment by ricefield** [comment]
Seems awfully complicated to me. I agree some of these things need to be worked out, but my original plan had always been to just use Dokku (http://dokku.viewdocs.io/dokku/) and run everything as being Heroku compatible (Heroku for staging, Dokku for production internally).

Don't have a strong opinion on the other things, but I would generally caution against over-engineering this. Store things in simple configs and deploy with `git push` is the most ideal. Tools like ansible and fabric scripts feel over complicated to me.
