### ISSUE TITLE
LS (new server): Trainee, Admin, TA Views + Bugs

### ISSUE THREAD

**Issue by ichootheword** [attendanceproject/djattendance#178]
TRAINEE VIEWS:
 
	1.	Landing page with notification for LS assignment on top (in yellow)
 
![image](https://cloud.githubusercontent.com/assets/17632988/14062367/c35f92e8-f359-11e5-870b-8b402a90a54c.png)

CI - stands for Cellphone and Internet
Still need: 1 - indicates how many more LS assignments need to be finished
 
Notes: Change codes? (e.g. CI => Cellphone)
	

2.	Life Study Summaries Home Page
![image](https://cloud.githubusercontent.com/assets/17632988/14062368/cd8fbb30-f359-11e5-86c8-bd581ef998c9.png)

Notes: Assigned LS does not show due date nor type of offense (i.e. Monday or Regular)


	3. New Life-Study Submission Page
![image](https://cloud.githubusercontent.com/assets/17632988/14062370/d17f17e0-f359-11e5-96fe-a4d98319658f.png)

Notes: Doesn't show word count or words remaining; LS can be submitted without meeting any minimum requirement
	
	4. Life-Study Summary Submitted
![image](https://cloud.githubusercontent.com/assets/17632988/14062371/d8222a60-f359-11e5-97b2-5d29853e1819.png)
 
Note: Life-studies assigned are not numbered. LS that has not been approved can be deleted - take away this functionality.

		5.	Life-Study Summaries Approved
 
![image](https://cloud.githubusercontent.com/assets/17632988/14062375/f70f2568-f359-11e5-8860-1f5aa67473ff.png)

	6.	Deleting Approved LS Summary from List
![image](https://cloud.githubusercontent.com/assets/17632988/14062376/fcd6d8a6-f359-11e5-9b8c-26f4a7c9da3d.png)

Note: What does it mean for the LS to be deleted? Does it mean to just disappear from view, or from the entire database and therefore irretrievable?

**Comment by ichootheword** [comment]
ADMIN VIEW
 
	1.	LS Home Page

![image](https://cloud.githubusercontent.com/assets/17632988/14062387/5112cf6a-f35a-11e5-8bae-44e8600cfb49.png)

 
	2.	Assigning LS
![image](https://cloud.githubusercontent.com/assets/17632988/14062388/54d9c5d6-f35a-11e5-945f-6de7ff057991.png)

Note: TA must assign both due date + due time

	3.	Viewing Trainees' LS Summary
![image](https://cloud.githubusercontent.com/assets/17632988/14062391/67a8d81e-f35a-11e5-92c3-fef9de060096.png)

 
	4.	Approving LS Summary

 
![image](https://cloud.githubusercontent.com/assets/17632988/14062392/6aed4b86-f35a-11e5-8a9d-3ce2794ad40a.png)

	5.	Deleting Trainees' Approved LS
 
![image](https://cloud.githubusercontent.com/assets/17632988/14062393/6f21cf2e-f35a-11e5-917e-31ee4344c0c3.png)

Note: What happens when LS summaries get deleted? Retrievable? Are the summaries that are deleted viewable somewhere? What happens when a TA wants to find a deleted LS summary?
 
**Consider another possibility once a LS summary is approved - possibly a database of each individual trainee's LS summaries, rather than one central location? **

**Comment by ichootheword** [comment]
ADMIN VIEW
1.	LS Home Page
<img width="1226" alt="ls home page" src="https://cloud.githubusercontent.com/assets/17632988/14062422/52b337fa-f35b-11e5-8c3c-8515be7849f7.png">

 
2.	Assigning LS
<img width="1228" alt="assigning ls" src="https://cloud.githubusercontent.com/assets/17632988/14062423/5e949fc8-f35b-11e5-930d-080298b6e753.png">
<img width="1223" alt="view ls summary submission" src="https://cloud.githubusercontent.com/assets/17632988/14062426/6e194dd6-f35b-11e5-8feb-ff4460279da5.png">

Note: TA must assign both due date + due time

3.	Viewing Trainees' LS Summary
<img width="1223" alt="view ls summary submission" src="https://cloud.githubusercontent.com/assets/17632988/14062434/b50962f8-f35b-11e5-94ae-bfc18e27a93d.png">
 
4.	Approving LS Summary
<img width="1223" alt="ls summary approved" src="https://cloud.githubusercontent.com/assets/17632988/14062435/baa2fdc8-f35b-11e5-9c2e-0f4a7405d1e5.png">

**Comment by ichootheword** [comment]
TA VIEWS:

1. Home View
![image](https://cloud.githubusercontent.com/assets/17632988/14062448/4f774760-f35c-11e5-8309-8eb6db3b857d.png)

2. View LS Submission(s)
![image](https://cloud.githubusercontent.com/assets/17632988/14062450/5a543de6-f35c-11e5-949e-b7cfa071b7ec.png)

Note: Add ability to toggle between multiple LS submissions by trainee

**Comment by radicalray** [comment]
@ichootheword Great Work! Good insights into the UI and good catches on the details! For deleting life study summaries, in the old server, you can't even see life studies that have been approved. Do we want to show the same thing or let you be able to see your past summaries? When you delete, it actually deletes from the db (maybe not what we want...). Each "list" is grouped according to each discipline. So, maybe we want to have past/finished disciplines and current disciplines. Do we want to group by disciplines or just give them a flat list? (They could get 2 LS for cellphone, 3 for attendance, 1 for speeding, and 1 for failing house inspection). How to show that in a easy way so they're not confused which LS is for which disciplines as well as make it easy to view all LS in a flat list? You may need to think about it as well as have a convo with TA's on their thoughts for old LS/visible/invisible.

**Comment by radicalray** [comment]
One more thing, there's a TA view. That's the view they'll look at most likely not the admin view. Create a TA and make sure to test it out.

**Comment by ichootheword** [comment]
I'll grab a TA sometime this week to talk about it, Ray. If the TAs would prefer that, I'll try to consider some ways we could display LS according to groups in a simple way.
