### ISSUE TITLE
Upgrade to django 1.9 for jsonfield

### ISSUE THREAD

**Issue by czhaocmu** [attendanceproject/djattendance#179]
https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#jsonfield

**Comment by haileyl** [comment]
+1.  I'm mapping a key to JSON currently (sorry, should have told you that explicitly earlier) to take care of the nesting issue, but jsonfield would be nice.

http://www.craigkerstiens.com/2013/07/03/hstore-vs-json/

**Comment by billyeh** [comment]
Upgrading to python3 would be nice too.

**Comment by billyeh** [comment]
Update on this: upgrading straight to Django 1.11 from current 1.8.

This diagram shows that 1.11 will be supported from this year to the end of 2020. Support for 1.8 is ending after this year. https://www.djangoproject.com/download/#supported-versions

Also, package maintainers will no longer support version <1.11 after Django 2 comes out in a year. https://docs.djangoproject.com/en/1.11/releases/1.11/#deprecating-warnings-are-no-longer-loud-by-default
```
Following the release of Django 2.0, we suggest that third-party app authors drop support for all versions of Django prior to 1.11. At that time, you should be able run your package’s tests using python -Wd so that deprecation warnings do appear. After making the deprecation warning fixes, your app should be compatible with Django 2.0.
```

**Comment by billyeh** [comment]
Upgrading everything is always going to be an issue so let's close this since at least Django's up to date now.
