### ISSUE TITLE
Custom trainee list picker broken

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#180]
The api for for trainee list picker seems broken.

http://ap.ftta.lan/schedules/event/create/

![image](https://www.dropbox.com/s/h0wyxk1hcr7wc1y/Screenshot%202016-04-02%2019.42.30.png?dl=1)

The api json links seem to be broken.

![image](https://www.dropbox.com/s/4wgoczvr4cio34n/Screenshot%202016-04-02%2019.44.45.png?dl=1)

**Comment by radicalray** [comment]
Can we add this somehow to our custom queryset in the back?

@haileyl @jontey 

To be used for import/schedule migrations/service scheduling?

**Comment by billyeh** [comment]
This is fixed on the `dev` branch from #423
