### ISSUE TITLE
Importer Design Spec

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#182]
Hopefully this is not too awful. It's also not formatted neatly, so there's a lot of white space :(

This is primarily for the start of the term. i still need to write more for a mid-term import. 

It's not complete, and there are a few changes that I need to make, so that images will all be different in the future. But for the most part, this is how (we? I?) see the start of the term. 

Thoughts? 

https://www.dropbox.com/s/a7e1heyd1mnb7p0/Importer%20design%20spec.docx?dl=0
^the file is too big to embed

**Comment by rayoowoo** [comment]
Actually, the entire schedule section is going to be scrapped. Just FYI

**Comment by radicalray** [comment]
@rayoowoo Great, looks awesome! thanks for the screenshots and sketches. I like the front and center simple design.

Here's some small things I thought of:

Did we cover the case for updated info fields? Will the form show up with fields changed highlighted? can users see before/after for changed fields? Maybe not use red color to indicate change (usually used for error/invalid field), use yellow? 

Also, will all 4 tabs be needed? Will they be sometimes not needed to show up? Like no changes in houses? Should we put a (facebook red number tag on the tabs) to show how many records have changed so they don't need to click into it.

Do we want the import button to be so easily accessible, front and center, makes people want to click on it without thinking twice or double-checking to make sure all the deltas are correct? It's a really big operation and we should encourage users to slow down and consider before they accidentally click on it? If we let them undo the import, this might not be as big of an issue.

Others, feel free to give some comments, this is just a discussion thread.

@rayoowoo @ichootheword @elijyl @rochellewang @czhaocmu @lifedispenser

**Comment by rayoowoo** [comment]
@radicalray 
I didn't differentiate between updated info fields and info fields manually changed by the user. I guess we may want to. Yellow and another color?

I feel like all 4 tabs should be there, (1) for consistency, and (2) just in case the user needs to create something new, like a new house. But maybe we could have something  like an exclamation to indicate there's a discrepancy between the CSV and the server's record?

![notify discrepancy](https://cloud.githubusercontent.com/assets/17632989/14366916/03552ed4-fcca-11e5-80e3-7e8081967da2.jpg)

 Also the "schedule" tab is being switched out for "localities." Schedules will be a little different (Hailey had some good ideas). I'm updating the spec today, so I'll try to get it out at the end of the day. 

For the import button issue, I was thinking that after clicking the "import" button, there were would be a popup asking them to confirm. 
![yes or no](https://cloud.githubusercontent.com/assets/17632989/14367057/be6dfd04-fcca-11e5-8b6e-751c4d2a5ec7.jpg)

I don't know if that's enough to prevent accidental imports. 

Also, Hailey brought up some issues with having the "Do Not Include" option, particularly with regards to handling typos, so that's probably going to be changed. I still have to figure that out in a more concrete way. 

Thanks!

**Comment by rayoowoo** [comment]
i was thinking that we could remove all the "create new" from the importer - the cases are way too rare. And it wouldn't be all that difficult to just create things manually, outside of this import process. Is that good?

**Comment by rayoowoo** [comment]
New spec.
[Importer design spec v. 3c.pdf](https://github.com/attendanceproject/djattendance/files/211600/Importer.design.spec.v.3c.pdf)

this is the dropbox to all the images on this spec:
https://www.dropbox.com/sh/7ntwsjixt4e3anv/AAA7cUil9W7NVQxde3SbOWdra?dl=0

**Comment by rayoowoo** [comment]
finished the schedules portion. final for now.

[Importer design spec v. 4.pdf](https://github.com/attendanceproject/djattendance/files/233218/Importer.design.spec.v.4.pdf)

**Comment by billyeh** [comment]
Closing as this is not an actionable issue. We can always refer back, though
