### ISSUE TITLE
Model redesign for Trainees + TA's

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#184]
Hey @ricefield, I found a potential way to make our user definition much cleaner.

```
class Lesson(models.Model):
    RECURRENCE_CHOICES = (
        (0, 'None'),
        (1, 'Daily'),
        (7, 'Weekly'),
        (14, 'Biweekly')
    )

    student = models.ForeignKey(Student)
    frequency = models.IntegerField(choices=RECURRENCE_CHOICES)
    lessonTime = models.TimeField('Lesson Time')
    startDate = models.DateField('Start Date')
    endDate = models.DateField('End Date')
    cancelledDate = models.DateField('Cancelled Date', blank=True, null=True)
    paidAmt = models.DecimalField('Amount Paid', max_digits=5, decimal_places=2, blank=True, null=True)
    paidDate = models.DateField('Date Paid', blank=True, null=True)

class CancelledLessonManager(models.Manager):
    def get_query_set(self):
        return self.filter(cancelledDate__isnull=False)

class CancelledLesson(Lesson):
    class Meta:
        proxy = True

     objects = CancelledLessonManager()

class PaidLessonManager(models.Manager):
    def get_query_set(self):
        return self.filter(paidDate__isnull=False)

class PaidLesson(Lesson):
      class Meta:
          proxy = True

      objects = PaidLessonManager()
```

Django Proxy Models! It let's us treat Trainees and TA's like they're complete different models in django but only occupies 1 table in the db, saving us from doing complicated pre-db-joins for performance issues. Also, keeps things a lot cleaner by having 1 table for all the users.

Does this address all the concerns we had for having a separate user/profile/trainee/traineeassistant models? thanks! 

This is the link the code snippet is from: http://stackoverflow.com/questions/10937660/handling-recurring-events-in-a-django-calendar-app

**Comment by ricefield** [comment]
I remember looking at proxy models when the project first started... the only advantage they really have is they allow you to define a custom manager and/or change the default ordering on a model/table. I don't see how that is applicable to this problem.

**Comment by radicalray** [comment]
Because it's so inefficient to do a database join across 3 tables every time we want to get a single user. I want to merge it all into 1 table and masquerade the distinction in types with proxy models.

**Comment by ricefield** [comment]
If you *really* want to just merge everything into a single user table, then I don't think you need proxy models at all, you can just go ahead and do it. 

I don't really think it's an elegant design, but it certainly will be _faster_.

**Comment by radicalray** [comment]
Ok, let's do it.

**Comment by radicalray** [comment]
Code restructured and merged into one table now. Closing.
