### ISSUE TITLE
Roll Entry Spec

### ISSUE THREAD

**Issue by elizajyl** [attendanceproject/djattendance#188]

**Comment by elizajyl** [comment]
[RollEntry - 5-28.pdf](https://github.com/attendanceproject/djattendance/files/288081/RollEntry.-.5-28.pdf)

Updated Spec

**Comment by elizajyl** [comment]
Additional Note on Web-Roll Entry Form
- Roll entered for 2nd year trainees on self-attendance will not be reflected in the trainee's schedule. However, the AM's roll information will be stored for comparison with the trainee's own attendance record for auditing purposes. See "AM Attendance View" Spec for more details.

**Comment by jontey** [comment]
Done. Some small bugs and enhancements still needed. Listed in #316
