### ISSUE TITLE
Let's use Dropbox as git repo

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#195]
http://www.anishathalye.com/2016/04/25/dropbox-as-a-true-git-server/

For db backups and sensitive files? 

@lifedispenser @ricefield

**Comment by ricefield** [comment]
lol, I literally just read the same link. 

I think that's fine, but if they're just files, I don't necessarily see the need to store them as git repos.

A good use case for this, though, might be to store the original attendanceproj code... which would save us the trouble of having to anonymize/scour it for sensitive data.

**Comment by radicalray** [comment]
Looping Danny into this convo. @snowboarder003

**Comment by radicalray** [comment]
Feature done. Good job @snowboarder003 ! See internal wiki for instruction on how this is setup.
