### ISSUE TITLE
Create a Feedback/Feature request page

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#196]
Create a Feedback/Feature request page to let users report bugs and submit suggestions for improvements!

Also, a page for devs/TA's to see/track/review and push issues/bugs automatically to github?

@ricefield @lifedispenser

**Comment by ricefield** [comment]
@ysbecca took a stab at this a few years back: https://github.com/attendanceproject/djattendance/pull/65

**Comment by billyeh** [comment]
Consolidating from #64 

what categories should be available for user-submitted bug reports? and how should this affect the way we structure our github issue labels?

we should consider the historical and potential usage of issue reports:
- non-critical bug reports (i.e. "I ran into this error, bug got around it, nbd")
- important/critical bug reports (i.e. a blocking error that prevents someone from completing a task)
- requests for changes e.g.: 
  - "update the text on this page" 
  - "left something in your box/come see me"
  - "this leave slip doesn't work" 
  - "change so-and-so's schedule please"
- requests for data (e.g. generating a report)
- feature requests/suggestions

**Comment by finben** [comment]
A paper form has been created and uploaded to the dropbox to be used as a physical form beginning next term as the server launches. It has been decided that until the near future to force both feature requests as well as bug reports to be made on a physical form and submitted to the attendance area service area. This is primarily to limit the number of excessive requests being made to the AP team.
