### ISSUE TITLE
Grades

### ISSUE THREAD

**Issue by haileyl** [attendanceproject/djattendance#200]
We might want to just represent this as exams that can't be taken on the server, or we could come up with a simpler model to track these.  This should be used for life lessons/MoHL quizzes or LoS reading completion grades.  This would allow grades to be calculated on the server, makeup lists to be generated and grade reports to be created.

Tasks:
- Design/model for score item -- consider whether to repurpose exams or if we want to make a particular score for each type of grade--completion, vs. grading.
- Need a way to assign passing scores per class or per graded item
- Set item weights and calculate overall grades (e.g. MoHL scores \* 0.3 + exam grade \* 0.6 + life lessons score \* 0.1).  Also need to be able to fail someone based on just an individual item.
- Exam makeup and retake lists--to be generated by class, across classes (a grading sister or TA should be able to select particular classes), or per graded item/exam as necessary.
- Generate grade reports: by sending locality, by team, by trainee.

**Comment by finben** [comment]
This is now included. TA's have ability to input grades for paper graded exams now on the server which takes care of the scope. We still need grade report generation but that is documented in our future project management milestones
