### ISSUE TITLE
Exams enhancements

### ISSUE THREAD

**Issue by haileyl** [attendanceproject/djattendance#201]
Some things that can be added but aren't p0:
- [ ] Sorting/filters on single exam grade view.
- [ ] List of currently open exam retakes--retake should be kept until grader explicitly deletes it.
- [ ] We don't have a PM design for exams, but eventually, front end will have to be tweaked.
- [x] Other exam question types
- [x] Autograde functionality

**Comment by rayoowoo** [comment]
Eliza should be working on exams now. 

@elizajyl

**Comment by finben** [comment]
Closing this @ksungreborn  is working directly with office for their up to date requests
