### ISSUE TITLE
Need some fields in the trainee model

### ISSUE THREAD

**Issue by haileyl** [attendanceproject/djattendance#205]
# fields to use: termsCompleted, couples, HouseCoor, college, major, degree
    #   vehicleYesNo, vehicleModel, vehicleLicense, vehicleColor, vehicleCapacity,
    #   greekcharacter
    # unused fields: homePhone, workPhone, emergencyContact, emergencyAddress,
    #   emergencyPhoneNumber, emergencyPhoneNumber2, readOldTestament, 
    #   readNewTestament, gospelPreference1, gospelPreference2, traineeStatusID,

**Comment by radicalray** [comment]
What's traineeStatusID? @haileyl

**Comment by haileyl** [comment]
Oops sorry, that column's unused in the csv.

**Comment by haileyl** [comment]
What's expensive is not the profile/joining on the profile.  It's the permissions piece that's super costly.

**Comment by radicalray** [comment]
Hey Hailey, how's the rewrite coming along? We want to get it merged in as soon as possible. Let me know if you need any help. @haileyl
