### ISSUE TITLE
Violation of DRY in life studies model

### ISSUE THREAD

**Issue by burricks** [attendanceproject/djattendance#207]
While removing logic from the templates in the life studies module, in a couple of small areas, I had some repeated code between two files: 'templates/discipline_list.html' and 'templates/trainee/trainee_discipline_list.html'. Not really sure how to modularize it without repeating myself somewhere else in the code.

**Comment by burricks** [comment]
Fixed

**Comment by radicalray** [comment]
@burricks For future reference, please reference commit + branch / PR issues are fixed so we can track it in the future. Thanks!
