### ISSUE TITLE
Some issues to think about in the life studies model

### ISSUE THREAD

**Issue by burricks** [attendanceproject/djattendance#208]
- There's no word-count, and no way to report word-count to TA’s
- In update, one cannot change the book or the chapter of a summary once it has been saved. Could be a problem in cause of a mistake made when submitting. 
- A TA cannot un-approve a life-study 
- It’s possible to submit more than one life-study summary for the same chapter
- Period selection in assigning life-studies according to attendance isn't working
- No way to view past life-studies that have been approved

**Comment by radicalray** [comment]
Hey @burricks , word-count function is done in exams, just add it in. Talk to @haileyl 

For the rest, can you check old server functionality to see if they are there and reprioritize the list. Also, please feel free to fix the critical bugs as you spot them!
