### ISSUE TITLE
Service Schedule Module

### ISSUE THREAD

**Issue by lifedispenser** [attendanceproject/djattendance#212]
# Introduction

The service schedule module assigns services to trainees weekly. It uses a min-max flow algorithm from ortools to do so efficiently. 
## Models

| Model | Description |
| --- | --- |
| Seasons | Periods of time when services are active |
| Categories | Categories of Services |
| Services |  |
| AssignmentPools | Service Slots of the Service that get filled by qualified workers represented by worker groups |
| WorkerGroups | Picklist of predefined workers OR query of qualified workers that serve as the pool that can be assigned to a service |
| QueryFilters | A filter that returns a group of workers |
| ServiceExceptions | Block a Worker or a group of workers from getting assigned to services based on datetime |
| WeekSchedule | The schedule instance for a particular week |
| Assignments | Assign a worker to a service on the WeekSchedule instance |
## SubModules

*\* note - some submodules do not have all their pages mocked up.
### 1. Initial Setup

CRUD pages that allow you to establish Seasons, Categories, Worker Groups, and Query Filters
### 2. Service Setup

Advanced Pages that allow you to setup Services. 
Services are grouped by category and have service slots, which are filled in by workergroups. Service slots can be set to fill in manually by hand through a Service Manager Role or automatically through a cost optimization solver.
## ![services](https://cloud.githubusercontent.com/assets/81975/15272035/58cfd3f0-1a1b-11e6-8275-4079a54ab483.png)

![edit service - basic](https://cloud.githubusercontent.com/assets/81975/15272036/5b0a8ab6-1a1b-11e6-9308-cfc3c5fde8b5.png)
### 3. Exception Requests and Worker Settings

Pages to setup exceptions for groups of workers to prevent them from receiving services based on time periods and reduce worker workload.

![service exception form](https://cloud.githubusercontent.com/assets/81975/15272042/b766c43c-1a1b-11e6-80e4-9191183c1638.png)
### 4. Manually fill out Special Services

Service Managers are responsible for assigning services manually for particular service slots. 
### 5. Update Worker Counts and Autogenerate Schedule

Module that automatically fills in the rest of the unfilled services based on exceptions, worker counts and worker groups
## ![update worker counts](https://cloud.githubusercontent.com/assets/81975/15272047/1283bcb2-1a1c-11e6-85c5-afbdb5ff06c1.png)

![auto generate schedule](https://cloud.githubusercontent.com/assets/81975/15272045/0cf50cce-1a1c-11e6-8d87-81f622206e67.png)
### 6. Schedule Instance Viewer

View all service assignments of a Schedule instance. 

![view service](https://cloud.githubusercontent.com/assets/81975/15272049/3b377a18-1a1c-11e6-8fc6-735e34394b92.png)
### 7. Service Instance Viewer and Modifier

View and Modify assignments for service slots of a service

![view service](https://cloud.githubusercontent.com/assets/81975/15272050/436fa336-1a1c-11e6-8365-a23516aa641a.png)
### 8. Service Swapper

Page to enable service assignments swaps

![swap services](https://cloud.githubusercontent.com/assets/81975/15272052/51c87f3e-1a1c-11e6-8b54-48bad3bbb660.png)
## ![sign in sheet](https://cloud.githubusercontent.com/assets/81975/15272056/5d68aff8-1a1c-11e6-9017-b69917f5c3a5.png)

![print schedule](https://cloud.githubusercontent.com/assets/81975/15272054/56a16f8e-1a1c-11e6-950a-b971f06ddb7b.png)

**Comment by lifedispenser** [comment]
# Introduction
The service schedule module assigns services to trainees weekly. It uses a min-max flow algorithm from ortools to do so efficiently. 

## Models
Seasons (Periods of time when services are active)
Categories (Categories of Services)
Services 
AssignmentPools (Service Slots of the Service that get filled by qualified workers represented by worker groups)
Worker Groups (Picklist of predefined workers OR query of qualified workers that serve as the pool that can be assigned to a service)
QueryFilters (A filter that returns a group of workers)
ServiceExceptions (Block a Worker or a group of workers from getting assigned to services based on datetime).
WeekSchedule (The schedule instance for a particular week)
Assignments (assign a worker to a service on the WeekSchedule instance)

## SubModules

### Initial Setup
CRUD pages that allow you to establish Seasons, Categories, Worker Groups, and Query Filters

### Service Setup
Advanced Pages that allow you to setup Services. 
Services are grouped by category and have service slots, which are filled in by workergroups. Service slots can be set to fill in manually by hand through a Service Manager Role or automatically through a cost optimization solver.

### Exception Requests and Worker Settings
Pages to setup exceptions for groups of workers to prevent them from receiving services based on time periods and reduce worker workload.

### Manually fill out Special Services
Service Managers are responsible for assigning services manually for particular service slots. 

### Schedule Autogenerator
Module that automatically fills in the rest of the unfilled services based on exceptions and worker groups
 
### Schedule Instance Viewer
View all service assignments of a Schedule instance. 

### Service Instance Viewer and Modifier
View and Modify assignments for service slots of a service

### Service Swapper
Page to enable service assignments swaps

### Service Sign in Sheet & Print Services

**Comment by rayoowoo** [comment]
#5 Check with kitchen to see if it would be helpful for the server to accumulate meal attendance for them.

**Comment by jontey** [comment]
- Still need to add auto generate leaveslips from assignments
- Add print reports
- Switch trainees for leaveslips

**Comment by jontey** [comment]
Mostly done. The remainder tasks are listed in #473
