### ISSUE TITLE
TA View- Class Notes and Life-Study Summaries

### ISSUE THREAD

**Issue by rochellewang** [attendanceproject/djattendance#218]
[For Git.docx](https://github.com/attendanceproject/djattendance/files/276063/For.Git.docx)
@catier101

**Comment by rochellewang** [comment]
Here is the updated Class Notes and Life-Study Summaries mockup. 
Changes: 
1) on the left, under the panel we have two buttons ("Marked for Fellowship" and "Approved Assignments")

2) instead of "Deny" there is now a "Fellowship" button. When a TA clicks this button, the "Remarks" box pops up. The TA can leave a comment, then send. When they send a comment, the list still auto-advances to the next Class Note or Life-Study Summary on the list. 
![7 class notes fellowship popup](https://cloud.githubusercontent.com/assets/17633336/15630058/31888d9e-24e0-11e6-8e73-dbba5ec5a88d.jpg)

3) The "Marked for Fellowship" button leads to this page:

![8 marked for fellowship](https://cloud.githubusercontent.com/assets/17633336/15630112/5ed2c948-24e2-11e6-9845-8d27c2cd74e7.jpg)

The Remarks pop-up is the default view. When the TA closes the pop-up box, it stays on that Class Note/Life-Study Summary.

4) "Class Notes" is a hyperlink to this original full list view:
![9 class notes home](https://cloud.githubusercontent.com/assets/17633336/15630131/218ebd8e-24e3-11e6-8d01-b6d3def0f66c.jpg)

**Comment by rochellewang** [comment]
A couple more things:
1) An "Approve All" button to automatically approve all Class Notes or Life-Study Summaries on the list.
2) "View Class Notes for all TAs" and "View Life-Study Summaries for all TAs" at the top of each page respectively.

**Comment by leonardlan** [comment]
Gonna try taking a look at this one...

**Comment by rayoowoo** [comment]
#79 Suggestion from Jerome: if a trainee has Monday discipline assigned, then night out leave slips for that Monday would automatically be denied.
