### ISSUE TITLE
Mid-term Information Changes

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#222]
I called it a "term manager." not sure what to call it later on.
It's meant for making changes in the database in the middle of the term.

Here's a preliminary spec. There are instructions for editing information for individuals (trainees, houses, teams, etc.) in Django admin in a separate document.

[Term Manager design spec v.pdf](https://github.com/attendanceproject/djattendance/files/288073/Term.Manager.design.spec.v.pdf)

[Django Admin Information Changes Instructions.pdf](https://github.com/attendanceproject/djattendance/files/288074/Django.Admin.Information.Changes.Instructions.pdf)

**Comment by jontey** [comment]
Most of the bulk editing features are solved by adding this plugin https://github.com/burke-software/django-mass-edit
