### ISSUE TITLE
Python Fix all the python indentations

### ISSUE THREAD

**Issue by schai6** [attendanceproject/djattendance#224]
Convert all indentation to 2 spaces instead of 4 spaces or tab.

**Comment by leonardlan** [comment]
Conform, Sam.
@schai6

**Comment by rayoowoo** [comment]
i closed this issue. is it okay? @schai6 @leonardlan

**Comment by radicalray** [comment]
Don't close it, this is not fixed yet. Consolidate it into maybe final things to do as we're finishing up. 

Ray
