### ISSUE TITLE
Breaking commas in json api

### ISSUE THREAD

**Issue by schai6** [attendanceproject/djattendance#227]
ap/attendance/templates/attendance/attendance_react.html

I wonder if we can write a template filter in django to just serialize it directly into a json object so we don't have to print this out. This will print out like this:

var Events = [
{...},
{...},
];

The last comma will break in some browsers.

**Comment by billyeh** [comment]
This page says there's support for every major browser. I don't believe we care about IE <10. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Browser_compatibility
