### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#237]
![image](https://cloud.githubusercontent.com/assets/17632989/15760542/8f98d09c-28c8-11e6-96fb-7ae9856efcad.png)

on the left nav bar, the following links do not do anything:

Class Notes, A/V requests, maintenance Requests, room reservation requests, announcements.

Is this because these modules have not been completed / added yet?

**Comment by radicalray** [comment]
That is correct. They are not critical for p0 deployment.
