### ISSUE TITLE
TA View Spec

### ISSUE THREAD

**Issue by rochellewang** [attendanceproject/djattendance#243]
[Spec Final.docx](https://github.com/attendanceproject/djattendance/files/296869/Spec.Final.docx)

Ignore the stuff that's crossed out.

@davidhtien

**Comment by davidhtien** [comment]
Hey actually I would prefer to have it in pdf format if you could do that, I think it's pretty simple right? Just save as .pdf in word, that way you also don't have to upload a bunch a files to github if you don't want to

**Comment by davidhtien** [comment]
[Spec.Final.compressed.pdf](https://github.com/attendanceproject/djattendance/files/298310/Spec.Final.compressed.pdf)

**Comment by davidhtien** [comment]
[Spec.Final.pdf](https://github.com/attendanceproject/djattendance/files/298314/Spec.Final.pdf)

**Comment by rochellewang** [comment]
Clicking on fellowship marks it for fellowship, **leaves a comment for the trainee saying “Please come in for fellowship”** and auto advances.

**Comment by rochellewang** [comment]
![Uploading Leave Slip Private Comments.jpg…]()

**Comment by rochellewang** [comment]
![leave slip detailed view with private remarks](https://cloud.githubusercontent.com/assets/17633336/15802059/5404d3b0-2a5c-11e6-9eaa-9f213f8b762c.jpg)

**Comment by rochellewang** [comment]
[Spec Final.docx](https://github.com/attendanceproject/djattendance/files/333263/Spec.Final.docx)

Updated TA View Spec

**Comment by rochellewang** [comment]
Code for (current) room reservations:

https://github.com/timekit-io/booking-js
http://hourhq.com/?utm_medium=link&utm_source=timekit-io&utm_campaign=introducing-hour-link

**Comment by rayoowoo** [comment]
#79 Suggestion from Jerome: if a trainee has Monday discipline assigned, then night out leave slips for that Monday would automatically be denied.

**Comment by allisonfaith** [comment]
[TA view Class Notes.pdf](https://github.com/attendanceproject/djattendance/files/560179/TA.view.Class.Notes.pdf)
[TA view Leave Slips.pdf](https://github.com/attendanceproject/djattendance/files/560181/TA.view.Leave.Slips.pdf)
[TA view Life-Study Summaries.pdf](https://github.com/attendanceproject/djattendance/files/560180/TA.view.Life-Study.Summaries.pdf)
[TA view Room Reservation.pdf](https://github.com/attendanceproject/djattendance/files/560182/TA.view.Room.Reservation.pdf)
[TA View.pdf](https://github.com/attendanceproject/djattendance/files/560178/TA.View.pdf)

**Comment by iamsitting** [comment]
Closed by Ben F.
