### ISSUE TITLE
TA's should have their is_staff set to true

### ISSUE THREAD

**Issue by davidhtien** [attendanceproject/djattendance#244]
```
class TrainingAssistant(User):
  class Meta:
      proxy = True

  is_staff = models.BooleanField(default=True)

  objects = TAManager()
```

something like this I presume?

**Comment by davidhtien** [comment]
`class TrainingAssistant(User):
  class Meta:
      proxy = True

  is_staff = models.BooleanField(default=True)
  
  objects = TAManager()`

something like this I presume?

**Comment by radicalray** [comment]
@burricks Is this the intended behavior?

**Comment by jontey** [comment]
TA's need that to be true in order to access Django Admin.

Also needs to be set for any groups that will require access to Django Admin, ie. Attendance Monitors
