### ISSUE TITLE
Permissions Wiki + precepts of permissions in code rather than in db

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#246]
Need Specs on how permissions for all user roles should dictate which pages they can view/edit/etc... (@rayoowoo -> Make a wiki page for this so all devs can refer to it in the future)

@burricks can help create all the permissions and finalize our permissions design across all the major apps.

**Comment by rayoowoo** [comment]
Permissions for all user roles have been put onto the wiki. as we progress in the project, with pages being merged, changed, deleted, added, I'll edit that page.

**Comment by radicalray** [comment]
@burricks @rayoowoo can you add the link here to the wiki page?

**Comment by rayoowoo** [comment]
https://github.com/attendanceproject/djattendance/wiki/Permissions
