### ISSUE TITLE
Multiple individual leave slips on one event?

### ISSUE THREAD

**Issue by davidhtien** [attendanceproject/djattendance#247]
I don't think this makes sense to have, at most one event should be able to have one individual leaveslip and one group leaveslip

**Comment by davidhtien** [comment]
@rochellewang @elizajyl @radicalray @schai6

**Comment by radicalray** [comment]
Could you have multiple trainees individual leaveslip referencing the same event object?

**Comment by rayoowoo** [comment]
@davidhtien @rochellewang @elizajyl @radicalray @schai6
has this been resolved?

**Comment by ruthnan** [comment]
imo it doesn't make sense that you would have multiple individual leaveslips; why wouldn't you just edit your existing leaveslip? Allowing multiple individual leaveslips would make it possible for you to assign one TA to a leaveslip, and another TA to the same leaveslip, cluttering TA inboxes with more leaveslips.
