### ISSUE TITLE
Homepage Design

### ISSUE THREAD

**Issue by rochellewang** [attendanceproject/djattendance#249]
**Modules**
For everyone:
 1.  **Attendance** - for all attendance related matters, will need a homepage
 a) Submit Individual Leave Slip
 b) Submit Group Leave Slip
 c) Designated service hours?

 2. **Requests** - dropdown 
a) AV
b) Web Access 
c) e-Shepherding
d) Room Reservation
e) House Request

 3. **Life Studies/Class Notes** - will need homepage or list view of all the life studies/class notes you need to do

 4. **Classes** - things that supplement the class: Greek vocab helper, PSRP Class Outlines, Class Syllabus, Exams

For special permissions: 
 5. **Roll Entry** - Attendance Monitors, House Coordinators, Team Monitors, YPC 
 6. **Service Groups** 

Things under "Other" that we need to find a place for: 
a) Prayer Partner Generator
b) Special Schedules (ITERO, Thanksgiving Conference)*
c) Maps
d) Sister Lee Audio Files
e) Interim Intentions Form*
f) Semi-Annual Training Testing Groups*
g) Inspection Pages

_________________What about this information grouping for things under "Other"?_________________

Resources
a) maps
b) Sister Lee Audio Files
c) prayer partner generator

Events
a) Special schedules (ITERO, Thanksgiving Conference)
b) Semi-Annual Training Testing Groups

Forms
a) interim intentions
b) inspection pages

___________________________________________________________________________________
*Gospel section may include some things which are only made available at certain times

Gospel
a) Gospel stats
b) Gospel trip forms
c) List of gospel trip locations

*Things to consider: where to put things that only show up at certain times (ie: ITERO schedule, Interim Intentions Form, Semi-Annual Training Testing Groups)

**Comment by radicalray** [comment]
What about bible reading progress? Service assignment for the week.

**Comment by rochellewang** [comment]
@radicalray Right now on the new server, there is a separate Bible Reading Tracker page with 3 toggle tabs: "Daily" (records daily Bible reading C/N/M), 1st year (tracks 1st year reading progress through whole Bible) and 2nd year (tracks 2nd year reading progress through NT with footnotes). We were thinking of moving daily Bible reading to the home page. 

Service assignment for the week is on the weekly calendar on the home page and would be right above the daily Bible reading.

**Comment by miriamc09** [comment]
Hi all! Here is the presentation pdf to show the TA's
@ichootheword @rayoowoo @rochellewang let me know if you have any last minute feedback / things you think we should include in the visual presentation. Thanks!

[AP_homepage_TApresentation.pdf](https://github.com/attendanceproject/djattendance/files/322048/AP_homepage_TApresentation.pdf)

**Comment by miriamc09** [comment]
Here is the updated presentation. I thought it would be best to show the page layout in black and white first and get their opinion of it before we ask about color palettes. 
[AP_homepage_TApresentation.pdf](https://github.com/attendanceproject/djattendance/files/330986/AP_homepage_TApresentation.pdf)

**Comment by rochellewang** [comment]
Idea for improvement: switch the main four modules (AT, RQ, GS, OT) to the tabs so they are accessible from every page along with the FTTA banner. For the modules that will have dropdown menus, put a little down arrow.

**Comment by rochellewang** [comment]
Notes from meeting with Brother Curt and Brother Jerome (6/23):

- Borders could be thinner around “life-studies and class notes”
- Option two seems clearer to read (for color-blind people, contrast is important)
- For homepage: things that show up weekly like gospel stats (reminder to put it in, not put all the categories right there)
- Get a list of what modules will be complete by next term 

Better to get something done then gradually tweak, have something functional; in your specs you can have bells and whistles but get something functional out. We don’t want to run two systems in parallel.

email: Ta-brothers@ftta.org

**Comment by miriamc09** [comment]
Here is the latest iteration:

![ap_homepage_v2-01](https://cloud.githubusercontent.com/assets/19627516/16537369/af594002-3fb5-11e6-971b-e2ac6d6d0d02.png)
