### ISSUE TITLE
Check LifeStudy fixes

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#253]
@ichootheword, @jontey finished the lifestudy changes, his changes are merged and up on server. Please test it out and close the corresponding issues if they're fixed.

See his pr:
https://github.com/attendanceproject/djattendance/pull/239

**Comment by radicalray** [comment]
@ichootheword @rayoowoo Can you check to make sure life study is bug-free?

**Comment by rayoowoo** [comment]
- [ ] Monday offenses should only be allowed to done on Mondays.
- [ ] there is no finalize feature
- [ ] TA's have to do everything on Django admin for now.
