### ISSUE TITLE
Announcement (Notifications)

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#260]
Way to push announcements to trainees. Different kinds:

1. view-once announcements (your request was approved)
2. time-triggered announcements (You have not finalized attendance/bible tracker, open exams etc.)
3. completion-triggered announcements (you have not complete interim intention form yet)
4. time-duration announcements (shown for a period of time, Please wash hands before lunch, etc)
5. private-message announcements from office sisters/TA's.

Consideration for announcement design:

1. efficiency: calculating announcement every page load is expensive (i.e. check if available exam through table joins expensive)
2. stale states: Very hard to turn off event-triggered messages (ie old server) in case of a bug.

We may be able to piggy back off of admin feature currently? 

![alt text](https://www.dropbox.com/s/h8ubxxteao0x381/Screenshot%202016-06-11%2015.57.47.png?dl=1)

To record all db actions/events

**Comment by rayoowoo** [comment]
##### View-once:
A/V, Room Reservation, Web Access, e-shepherding, etc. request statuses
Leave Slip statuses
##### time-triggered announcements (You have not finalized attendance/bible tracker, open exams etc.)
###### failure to finalize: 
Attendance (2nd years, HCs, TMs, YP TMs, Desig Servs)
Bible Reading
Gospel Team Stats
##### completion-triggered announcements (you have not complete interim intention form yet)
###### Forms:
Interim intentions form
Semi-annual study form
Gospel Trip Destinations
Pay for conference?
###### Others:
Life studies
Class notes
Graduation-related
##### time-duration announcements (shown for a period of time, Please wash hands before lunch, etc)
Pay for conference
Pay board and lodging
Pay semi-annual fee
##### private-message announcements from office sisters/TA's.
book rewards
general announcements
