### ISSUE TITLE
Life study alerts

### ISSUE THREAD

**Issue by allisonfaith** [attendanceproject/djattendance#261]
multiple life study alerts for the same life study assignment on home page

**Comment by radicalray** [comment]
@allisonfaith  Screenshots and more description please.

**Comment by allisonfaith** [comment]
![life study notification bug](https://cloud.githubusercontent.com/assets/19786868/15987701/2e23b284-2fe7-11e6-8efd-0026fb35bb47.PNG)

Even when I dismiss the alerts and refresh the home page, there are still multiple alerts.

**Comment by jontey** [comment]
I thought that was a bug on my database. I can take a look at it

**Comment by rayoowoo** [comment]
was this resolved? @jontey @allisonfaith
