### ISSUE TITLE
Page Layouts

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#262]
Well this is a preliminary look through. I went through about 90-95% of the pages on the server, plus the existing design specs, and there's 5 basic page layout, along with a few unique layouts. 

[Page Layouts.pdf](https://github.com/attendanceproject/djattendance/files/310610/Page.Schemes.pdf)

@miriamc09 @lifedispenser if I did this wrong, let me know. 

I'll look through the pages again, and reconsider them. 

This is a list of all the views categorized by the 4 page layouts on excel:
[categorization of pages.xlsx](https://github.com/attendanceproject/djattendance/files/310609/categorization.of.pages.xlsx)

Rochelle posted all the views for the TA: https://github.com/attendanceproject/djattendance/issues/258.

**Comment by miriamc09** [comment]
Here is the latest iteration of page design for each of the 5 categories of pages:
![ap_pagelayouts-01](https://cloud.githubusercontent.com/assets/19627516/16537403/52c57490-3fb6-11e6-9510-8d3a36276932.png)
![ap_pagelayouts-02](https://cloud.githubusercontent.com/assets/19627516/16537404/52c5ccb0-3fb6-11e6-83eb-9499e1c1c38b.png)
![ap_pagelayouts-03](https://cloud.githubusercontent.com/assets/19627516/16537401/52c50762-3fb6-11e6-9285-fdbef13af0d2.png)
![ap_pagelayouts-05](https://cloud.githubusercontent.com/assets/19627516/16537402/52c51b1c-3fb6-11e6-990d-af3ed983e03c.png)
![ap_pagelayouts-06](https://cloud.githubusercontent.com/assets/19627516/16537400/52c4c93c-3fb6-11e6-9fc2-c845672c0ac9.png)
