### ISSUE TITLE
RFID Rolls

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#266]
Spec incoming. If you all think of any edge cases that I haven't covered, or there are any issues, or there are any possible solutions to the issues I listed, please comment!

also, @radicalray I'm not sure where the RFID readers will be - would you happen to know?

**Comment by rayoowoo** [comment]
# Automated Rolls in the Cafeteria

### Introduction

Rolls that take place in the cafeterias will now be taken by swiping badges on an RFID reader, thus replacing handwritten attendance rolls for meal times and study times. 

### Included Rolls

* Breakfast (Tuesday - Saturday) - 7:35am
* Breakfast (Lord's day) - 7:30am
* Lunch (Saturday) - 11:45am
* Dinner (Monday - Thursday, Saturday) - 5:45pm
* Campus & internet gospel team study rolls (Tuesday) - 4:15pm
* Campus & internet gospel team study rolls (Wednesday) - 4:30pm
* Campus & internet gospel team study rolls (Thursday) - 4:45pm
* Afternoon Study Roll (Saturday) - 2:15pm
* Character afternoon study roll (Thursday) - 4:45pm

### Excluded Rolls
Special schedules that have special rolls (e.g. Memorial Day Conference - Monday breakfast rolls) that take place within the cafeteria will be manually set. Rolls that do not occur within the cafeteria are currently not included. These include:

* Evening study rolls (Thursday, Saturday)
* Character study roll on Tuesdays (not regular)
* Children's, YP, and community study rolls (Tuesday - Thursday)
* Friday night study roll
* Class Rolls (includes PSRP)
* Team Rolls
* Service Group Rolls
* House Rolls

### Setup

There is a place on the server where the times for readers are activated for roll-taking. The time of each roll is manually determined:

![automatic meal rolls](https://cloud.githubusercontent.com/assets/17632989/16130980/b17b15e6-33c0-11e6-90ae-6d2cb76bb272.jpg)

For most rolls, tardies will be at the time indicated on the schedule, and absences 15 minutes afterward. For these rolls, the RFID readers will be activated for roll-taking 15 minutes prior to what would be a tardy, and the readers are deactivated at the time of which would be considered an absence. (For example, Tuesday campus study roll is listed as 4:15pm on the schedule. 4:15pm would be considered tardy, 4:30pm considered an absence. The reader would be activated from 4:00pm to 4:30pm.)

Certain rolls do not have a tardy option, only absences. These are:
* Tuesday Dinner
* Thursday Dinner
* Saturday Dinner

Absences will still be 15 minutes after the time listed on the schedule. For these rolls that do not have tardies, the RFID reader will still be activated 15 minutes prior to the time on the schedule, until the time of absence. (For example, for Tuesday dinner, absences will be at 6:00pm. The reader would be activated from 5:30pm to 6:00pm).

### Procedure

RFID readers will be placed at both the brothers' and sisters' sides of the cafeteria. Roll is taken in the same manner as unlocking doors to the buildings - by hovering or touching the name badge, with the cap tag, to the RFID reader. (is there any feedback upon "signing in"? like a beep or a flash?) The reader records the ID of the tag to indicate the trainee identity; and the time in which the read took place, which determines the roll status. During each activation period, the RFID reader will take a reading from a unique ID once.

The roll taken by the reader will be displayed on the attendance server in the Attendance Module. These rolls will be visible to the Training Assistant, Trainer, Developer, and Attendance Monitor permission groups. These rolls will be entered in the same way as attendance monitors currently input them manually. 

**Monday Dinner Sign-outs**
*(let me know if this is possible)*

Trainees will sign out of Monday dinners via a special leave slip on the server. These leave slips must be submitted on the Thursday the previous week. Only the Monday dinners of the current attendance period should be available to sign out from via this leave slip. If submitted on time, this leave slip will be automatically approved. If submitted late (after Thursday), the leave slip is automatically denied. The number of trainees who have not signed out of Monday dinner will be given to the kitchen sisters. 

### Issues

is there any feedback upon "signing in"? like a beep or a flash? 

If the RFID readers do not work, how should we let the trainees know, and how should we proceed to take roll?

**Comment by radicalray** [comment]
@rayoowoo Uniform tardy? Think of a way for Attendance monitors to input those types of tardies. Also, way to input missed attendance if trainees forget their badge?

**Comment by rayoowoo** [comment]
![map of cafeteria](https://cloud.githubusercontent.com/assets/17632989/16283819/494dcdd4-3883-11e6-9176-f0006e341773.jpg)
Here is a map of the cafeteria. 
@elizajyl where could we put readers?

**Comment by rayoowoo** [comment]
## Potential RFID Readers Locations
I wasn't sure how many readers we would be getting, so I just assumed 5 per gender. Here are three possible locations and potential traffic flow.

### Scenario 1
![possible 1](https://cloud.githubusercontent.com/assets/17632989/16467905/4db5c176-3dfe-11e6-8dcb-982e6515d747.jpg)

### Scenario 2
![possible 2](https://cloud.githubusercontent.com/assets/17632989/16467904/4d9c63f2-3dfe-11e6-9b25-36e85b8c288a.jpg)

### Scenario 3
![possible 3](https://cloud.githubusercontent.com/assets/17632989/16467903/4d976f14-3dfe-11e6-8664-51c741c64f1c.jpg)

**Comment by rayoowoo** [comment]
#### Scenario 1
![possible 1a](https://cloud.githubusercontent.com/assets/17632989/16504645/efd17098-3ecd-11e6-995e-10f0e48e7d6c.jpg)

#### Scenario 2
![possible 2a](https://cloud.githubusercontent.com/assets/17632989/16504646/efd37de8-3ecd-11e6-8d05-b57468907ee3.jpg)

#### Scenario 3
![possible 3a](https://cloud.githubusercontent.com/assets/17632989/16504644/efce11aa-3ecd-11e6-9197-c5bc95e08a5c.jpg)

**Comment by rayoowoo** [comment]
@radicalray 
for forgotten badges, I'd need to ask how the TAs or brother Curt how they would like to consider a forgotten badge roll-wise (e.g. if it's considered a uniform tardy). 

But for now, we could just have a submission page online for them to put their name in. 

![image](https://cloud.githubusercontent.com/assets/17632989/16536783/9e7de83c-3fab-11e6-862f-15b57022238c.png)

we still need to ask the TAs about what they want for uniform tardies in general. will do that next week.

**Comment by rayoowoo** [comment]
I'm not sure if we need a uniform tardy for meal and study rolls. I'll go ask brother Jerome some time this week.

**Comment by billyeh** [comment]
Closing as this is not an actionable issue. We can always refer back, though
