### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by allisonfaith** [attendanceproject/djattendance#270]
I logged out this afternoon and I got a white page, and now I'm seeing this
![1](https://cloud.githubusercontent.com/assets/19786868/16139321/f55d6a04-33fa-11e6-8dbf-9c9c3db6c7be.PNG)

**Comment by radicalray** [comment]
Currently broken. You can login as ap for now until we fix it. Go to /admin and login as ap and then maybe switch user?

**Comment by radicalray** [comment]
Good job, @jontey, fixed and deployed now!
