### ISSUE TITLE
Bible Tracker progress bar seem to be broken on production server

### ISSUE THREAD

**Issue by amarisch** [attendanceproject/djattendance#276]
Ajax call returned whole page instead of number.

**Comment by radicalray** [comment]
Seems like a local issue on @amarisch computer.

**Comment by radicalray** [comment]
Nope, seems like a legitimate issue. Has been duplicated on production in most recent pull.

@czhaocmu

**Comment by radicalray** [comment]
Method breaks when more than one record for bible reading is found for a user:

```trainee_bible_reading = BibleReading.objects.get(trainee = my_user)```

line 90 breaks if get returns more than 1 record. I'm not sure how it's possible to have such a case. We should look into how duplicates get created by accident.
