### ISSUE TITLE
Web Access Create Page crashes the server when viewed on mobile phone

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#281]
For some reason, only when you view ```http://ap.ftta.lan/web_access/create``` on a phone, brings the server down and won't load. What's going on? Maybe with the way the mac-address is being calculated not compatible with phones?

**Comment by leonardlan** [comment]
I think this is when the phones doesn't have access to the internet and it was trying to source external jquery link. I've changed it to source the server's copy so it should be resolved now.
