### ISSUE TITLE
Audio Request Specs Document

### ISSUE THREAD

**Issue by ichootheword** [attendanceproject/djattendance#285]
# Audio Request

---

The Audio Request is a module of the server where trainees have access to each class of the term via streaming of the recorded messages. Trainees can also request to download the audio recording of a class. Trainees who have class notes due will have the messages highlighted in orange with a link to go to the class notes module (see design below). 

Because all the class audios will be available via streaming, TA’s will have to manage trainees’ download requests of specific reasons only. Trainees who are sick for a class will automatically have the audio recordings available for download, but will be prompted with the policies of FTTA audio recordings prior to downloading. 
## Request Design

---

The module will have the following functionalities:
### Trainee View:
![trainee attendance_summary](https://user-images.githubusercontent.com/23424787/29999350-dd33e7b2-8ff9-11e7-8562-6c0d33977eea.png)

Audio Video(?) Request Home page with current week’s messages displayed
Any recorded message of that week in the training will be made available to listen to via streaming
Trainees can request to download a message and must provide a specific reason as to why
Trainees can view their history of download requests
### Training Assistant View:

A list of Audio Video Download Requests will be made viewable either with individual TA’s or all TA’s. Yellow pending requests will be prioritized in viewing. 


## Trainee View:

The Audio Visual Request (AVR) module will basically function as a media player, with the streamable messages of each week listed on the left with the trainees’ respective classes in chronological order. Additional special fellowship meetings that were recorded in that week will be at the bottom. Special fellowship recordings can also be made available on the module combined with Sister Lee’s Audio Files (possibly a ‘Special Fellowship Audio Files’ module?). 

![av request home](https://cloud.githubusercontent.com/assets/17632988/16354524/7ed07f46-3a4b-11e6-8c07-99eb8e4ec02e.jpg)

When a message is selected and played, the media player on the top right will display the message with the following information: date, class name, and the speaker’s name. 

Trainees will have the option to bookmark wherever they left off listening to the message in case they cannot finish the message in one sitting. Trainees will also have the option of requesting to download that message if they want to listen from their personal device. 

The trainee’s history of download requests will be listed on the bottom right - yellow for pending requests and green for those approved. Trainees will be able to directly download the approved requests from either this view, or by viewing the Download Requests page (see below).

![av request audio playing](https://cloud.githubusercontent.com/assets/17632988/16354528/91e3a45a-3a4b-11e6-80d8-33e52789183a.jpg)

![download requests view](https://cloud.githubusercontent.com/assets/17632988/16354531/a7ef3034-3a4b-11e6-9f1a-ea37fd7473ef.png)

Trainees who are excused from class due to sickness will automatically have the class(es) available for download in their request history. Any trainees who want to request to download a message for any other reason than sickness will have to submit a download request. By being as specific and detailed as possible for their reason, this can reduce the amount of unnecessary traffic between the trainee and the office. TA’s would see the detailed comments in the request and would respond accordingly. If the matter still requires fellowship, the trainee’s request will be marked for fellowship. 

![download request](https://cloud.githubusercontent.com/assets/17632988/16354533/d0fc02cc-3a4b-11e6-9585-febf01eb67ca.jpg)

Trainees who have class notes due for being absent for two or more lessons of a class will have those messages highlighted in orange with a link to go directly to complete their class notes. The class notes module should have the functionality to allow trainees to listen to the message while typing in their class notes.

![av request class notes due](https://cloud.githubusercontent.com/assets/17632988/16354537/dc290ce4-3a4b-11e6-84ca-b5725601683a.jpg)
![class notes](https://cloud.githubusercontent.com/assets/17632988/16354540/e0d04104-3a4b-11e6-8c37-66de88365541.jpg)
## Training Assistant View:

TA’s will generally only respond to Audio Visual Download Request as their primary use of this module. TA’s will have a list view of pending AVR’s (yellow). Once approved, the request will disappear from view. 

![ta avr list](https://cloud.githubusercontent.com/assets/17632988/16354542/eeb3d222-3a4b-11e6-9ee6-6fe44a7f04c3.png)

TA’s can view trainees’ request both to individual TA’s or to all TA’s and respond to them appropriately (in the case of a trainee seeking a specific TA in the office to fellowship about their AVR, but he is not there while other TA’s are available). 

![ta avr ali pending](https://cloud.githubusercontent.com/assets/17632988/16354545/fb884e24-3a4b-11e6-8eda-81e73b0db27d.png)

![all ta avr pending](https://cloud.githubusercontent.com/assets/17632988/16354546/00acad8c-3a4c-11e6-806a-5539e6f67249.png)

![all ta avr pending approved](https://cloud.githubusercontent.com/assets/17632988/16354547/064f4998-3a4c-11e6-9f11-d21a3c7cb929.png)

![ta avr approved disappear](https://cloud.githubusercontent.com/assets/17632988/16354549/115a9856-3a4c-11e6-906d-b8ffce314f5b.png)

**A tentative spec doc of our Audio Visual Request module. Not sure who is in charge of it, but can discuss more tomorrow to see who can take it up?

**Comment by ichootheword** [comment]
New UI for AV Request with possible color scheme:

![av request no color](https://cloud.githubusercontent.com/assets/17632988/16543963/80d2d6de-40a6-11e6-857b-9d53df0d868d.jpg)

![av request 5 colors](https://cloud.githubusercontent.com/assets/17632988/16543964/843fbd8c-40a6-11e6-8c21-69fa60b34602.jpg)

![av request 5 colors - message playing](https://cloud.githubusercontent.com/assets/17632988/16543965/88c80490-40a6-11e6-9cf9-60312ebb8abf.jpg)

**Comment by finben** [comment]
Per the AV brothers 
1. they would like the name of the entire module and all places within to have a name change in the user interface to just audio in place of A/V since there are no video files
2. Adding the option for "other" as a reason for an audio requestor to request audio. This is because a trainee does not have to be sick to request an audio file. They could for instance have been in the class and still want to request the audio file

**Comment by billyeh** [comment]
Closing as this is not an actionable issue. We can always refer back, though
