### ISSUE TITLE
Meal Seating Generator

### ISSUE THREAD

**Issue by ichootheword** [attendanceproject/djattendance#286]
# Meal Seating Generator

The Meal Seating Generator is a module that will generate the meal seating for the trainees on a bi-weekly basis throughout a single term. Seating arrangements will be made according to the available categories. 

![meal seating generator home](https://cloud.githubusercontent.com/assets/17632988/16354591/9f73579e-3a4d-11e6-9061-6dc7f2a3165e.png)

Once a date is chosen (drop down calendar view), the "+2" button will automatically set the end date to two training weeks after the selected start date (i.e. if start date is a Tuesday, the end date would be set as the Lord's day for the second week after). 

![start date select](https://cloud.githubusercontent.com/assets/17632988/16354620/abc026b6-3a4e-11e6-9fd1-0cba612b2e12.png)

![start and end date selected](https://cloud.githubusercontent.com/assets/17632988/16354627/d03ea882-3a4e-11e6-977d-fa82ed02d1ac.png)

Trainees can be seated according to a variety of categories.

![seating categories](https://cloud.githubusercontent.com/assets/17632988/16354630/f31af6bc-3a4e-11e6-96c0-1294d1186d1d.png)

The seating arrangements can also be modified by editing the information database of the tables in the cafeteria via 'Edit Info'. 

![edit info](https://cloud.githubusercontent.com/assets/17632988/16354639/5371859e-3a4f-11e6-9276-418e1168677e.png)

**Comment by radicalray** [comment]
@ichootheword: We have some work already done on this component. Take a look on the new server. See if we can build off if existing UI to save extra work. 

What's the main focus of this page? Here are some items I think are important: sorting filer, list of tables mapped of list of trainees. Maybe we shouldn't hide the last 2 info in a popup box but display it front and center and hide non-essential items like buttons. 

What's add couples/remove couples?

What's process? Do you mean by assign tables?

How do I view historical data (past assignments, is that important?)

What does the exported table to seats report look like? Does it have to be in PDF form, excel form?

Do we eventually want to actually visualize all the tables with list of trainees sitting in them?

"Sort trainees by" should be called: "Assign trainees to tables by"

Finally, try to simplify the layout as much as possible so the Devs can implement the UI much more easily. It's really hard to place buttons in awkward positions on the page. 

Thanks @ichootheword! Let's keep iterating.

**Comment by ichootheword** [comment]
# Meal Seating Generator

The Meal Seating Generator is a module that will generate the meal seating for the trainees on a bi-weekly basis throughout a single term. Seating arrangements will be made according to the available categories.

![meal seating generator 2 1](https://cloud.githubusercontent.com/assets/17632988/16512345/06929744-3f0f-11e6-8cd7-6aaf7e3d2ebe.png)

Once a start and end date is chosen as well as a categorization of seating, an assignment of tables will drop down below:

![meal seating generator table assignments](https://cloud.githubusercontent.com/assets/17632988/16512398/bbe818d0-3f0f-11e6-956a-0ff52f1720e6.png)

The printable sheets of the table assignments will appear as below:

![meal seating generator print - table assignments](https://cloud.githubusercontent.com/assets/17632988/16512416/f0695ce0-3f0f-11e6-9bd4-b263250daded.png)

The Meal Seating is one of three tabs that one can view in the Meal Seating Module. The three tabs are Meal Seating, Tables, and Trainees. The "Tables" and "Trainees" tabs can view and edit the information on tables and trainees, respectively:

![meal seating generator tables 2 1](https://cloud.githubusercontent.com/assets/17632988/16512400/c24024fc-3f0f-11e6-8164-fb3d7430e2b2.png)

On the "Tables" tab, one can edit the information of each table, as well as add tables. 

![meal seating generator trainees 2 1](https://cloud.githubusercontent.com/assets/17632988/16512401/cbdf58f2-3f0f-11e6-945f-b167ca87568f.png)

On the "Trainees" tab, one can edit whether a trainee will be included in the roster for table assignment or not. This will be mainly to exclude trainees who are commuters from the meal seating assignments.

**Comment by jontey** [comment]
Live on AP server. Need someone to start testing @allisonfaith

**Comment by finben** [comment]
I believe we are done and have meal seating complete. I will reopen if we find any further issues
