### ISSUE TITLE
Permissions Clarification for TA/Dev

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#292]
@rayoowoo To save time on programming, is this a valid assumption:

Can we give dev/TA superuser status to be able to view every page so we don't have to litter our code everywhere giving dev/TA permissions to view that view?

Basically, can we check to make sure we want to give dev/TA all permissions to all pages.

If not, we'll have to modify our:

`@group_required` filter as well as have to write our own custom `from braces.views import GroupRequiredMixin` to auto-let devs/ta groups through.

**Comment by rayoowoo** [comment]
@radicalray On the current server, the developer and the TA account types actually differ in that developers have developer tools (such as identity change) while TA's do not. that being said, TA brothers have both account types, while TA sisters only have the TA account type. 

there are also a few (but rare) pages to which the developer account type doesn't have access. one such example is the absent trainee roster page. I'd have to go and find the other ones manually. 

also right now, the developer and the TA home page views differ, with the developer having the normal trainee home page, whilst the TA has their own home page view. 

so in considering making dev/TA superusers:
1. are they going to be one permission group? if so, they would have the same home page view. if they're not going to be the same permission group, that would allow them to have differing home page views. 
2. are we going to allow trainee developers access to every page? we should reconfirm with the TAs. 
3. do the TAs want access to all the pages? this includes TA brothers and sisters.


if i have any more considerations, I'll comment.

**Comment by rayoowoo** [comment]
Developers cannot grade exams, cannot see absent trainee roster, cannot see HC survey, HC recommendation pages. 

(will add when I find)

**Comment by rayoowoo** [comment]
@radicalray 
is there anything else we need to talk about for this?

**Comment by rayoowoo** [comment]
#293 Figure out way to massively apply permissions to views

http://stackoverflow.com/questions/8544983/dynamically-mixin-a-base-class-to-an-instance-in-python

but changing class def is a little dangerous, not confident enough.

**Comment by yipingbenjaminliu** [comment]
we'll be using groups as defined in groups.py for permissions. We'll also use user type in certain cases.
