### ISSUE TITLE
Django migrate is getting really slow for empty db

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#301]
Maybe squash migration files?

http://www.rkblog.rk.edu.pl/w/p/squashing-and-optimizing-migrations-django/

Upgrade to django 1.9?

https://www.reddit.com/r/django/comments/3zks2r/django_makemigrations_and_migrate_super_slow/

Known serious performance problem: https://code.djangoproject.com/ticket/24743

Started to get really slow only after adding wiki.

**Comment by billyeh** [comment]
Not sure what fixed it but migrations are not bad right now! :)
