### ISSUE TITLE
Design Toolkit

### ISSUE THREAD

**Issue by miriamc09** [attendanceproject/djattendance#304]
Here is what I've come up with so far for the design toolkit. Includes color palette, typography, layout guidelines, and general components.

![ap_designtoolkit-01](https://cloud.githubusercontent.com/assets/19627516/16537414/92ac7f04-3fb6-11e6-8ea1-0fb29ec26bad.png)
![ap_designtoolkit-02](https://cloud.githubusercontent.com/assets/19627516/16537415/92c3053a-3fb6-11e6-9d61-0f1d7f5c1070.png)
![ap_designtoolkit-03](https://cloud.githubusercontent.com/assets/19627516/16537416/92c30968-3fb6-11e6-990d-4bf8fbbc73b6.png)
![ap_designtoolkit-04](https://cloud.githubusercontent.com/assets/19627516/16537417/92c53fb2-3fb6-11e6-9bf5-c6f6bf3d542e.png)
![ap_designtoolkit-05](https://cloud.githubusercontent.com/assets/19627516/16537418/92c5c338-3fb6-11e6-90ef-e876ab20461e.png)

**Comment by rayoowoo** [comment]
Under "project managers"
https://github.com/attendanceproject/djattendance/wiki
