### ISSUE TITLE
allow_bulk_destroy Question for Sam

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#312]
What does this do in attendance/views.py

```
    def allow_bulk_destroy(self, qs, filtered):
        return not all(x in filtered for x in qs)
```

@schai6 ??

**Comment by schai6** [comment]
It allows you to bulk delete. It only allows delete if the queryset was filtered, so you can't just delete everything, Does that makes sense?

**Comment by radicalray** [comment]
Ok, that wasn't clear. What if the filter is so broadly defined it returned all the rows in the db? i.e. you only had sisters in the db but the filter was for just sisters?

**Comment by schai6** [comment]
Yeah, right now it's any filter. It's just the most basic safety until we
want to implement something better I guess...
