### ISSUE TITLE
Clarification on numbering for week/periods

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#322]
Hey @jontey how is our weeks and periods numbered?

weeks -> zero-based?
periods -> zero-based?

I forget our conversation. We have inconsistent  definitions throughout the code.

**Comment by jontey** [comment]
I changed mine to zero based to follow Bible reading tracker and personal
attendance modules

**Comment by radicalray** [comment]
Ok, let's make that 0-based across the whole site: https://github.com/attendanceproject/djattendance/wiki/Week-Periods-Numbering-Standard
