### ISSUE TITLE
absentee report bugs

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#326]
- [x] List of available users includes all trainees. Should be just trainees in that house (for HC) and all active trainees (for absentee_roster service trainees)

**Comment by rayoowoo** [comment]
Testing so far. I can't come up with anymore cases. 

|Page	|Role	|Functionality / Cases	|Comments	|Label|Resolution|
|-------|-------|-----------------------|---------------|-----|---------|
|HC submission page	|HC	|view of the page	|the trainees in the HC's house should be displayed, not a dropdown menu of all possible trainees|	BUG	||
|HC submission page	|HC	|submitting a trainee not in the HC's house	|this will not take the HC's house off of the "unreported houses" list. |	BUG	||
|HC submission page	|HC	|submitting a trainee that IS IN the HC's house	|this does take the HC's house off the "unreported houses" list.|		||
|HC submission page	|HC	|there are no trainees absent for that day	|there is no way for the HC's to indicate all the trainees in his or her house are healthy. (maybe we can add a checkbox that says: all trainees healthy)|	MISS	||
|Ab. Tr. Roster Service Page	|Service trainee	|deleting a trainee from absent list	|this removes the trainee from the report, but does not add the trainee's house back onto the list of unreported houses	|	||
|Ab. Tr. Roster Service Page	|Service trainee	|emailing report	|error 404|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|list of unreported houses	|houses that are not being used by the training currently are also being listed. they need to be taken off|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|archived reports	|there is no way to view past reports.|	MISS	||
|Ab. Tr. Roster Service Page	|Service trainee	|list of trainees	|trainees not active in the trainee are listed. they need to be taken off|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|sick trainees who are coming to class|	should they be on the report or not?|	NOT SURE|	they do||
|Ab. Tr. Roster Service Page	|Service trainee	|view report	|a report is generated in a PDF form according to what is displayed on the roster page|		||
|Ab. Tr. Roster Service Page	|Service trainee	|viewing the list of unreported houses	|the testbox should not hide any text. that is inconvenient|	SMALL	||
|HC submission page	|HC	|add trainees	|adding trainees onto their list will cause them to appear on the Ab. Tr. Roster Service Page|		||
|ADMIN page	|Admin	|removing a trainee from a report	|you can't remove trainees from a report from the admin rosters page|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|a trainee who has been absent for multiple days consecutively|	the trainees is shown to have been absent for multiple days		|||
|Ab. Tr. Roster Service Page	|Service trainee	|a trainee who has been absent for multiple days NONconsecutively|	the trainee is shown to have been absent for multiple days. it should only be consecutive absences/sicknesses, but it's calculating absences/sicknesses from the past 6 days, including current day, consecutive or not. (e.g. a report on 7/20 will include absences/sicknesses from 7/14 - 7/20.)|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|selecting trainees to put on the report|	after you select one trainee, that trainee is still in the dropdown menu. selecting the same trainee twice and trying to save will bring up a white screen|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|deleting the last trainee from the absent list|	clicking the X will delete the trainee from the report, but there is not visual feedback that the delete has occurred|	BUG	||
|Ab. Tr. Roster Service Page	|Service trainee	|add trainees|	adding one trainee should automatically add an empty line; there shouldn't be a manual adding of a line|	BUG|	|
