### ISSUE TITLE
Wiki - resize "preview" window

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#329]
After making an edit on an article on the wiki, you can preview your work in a popup window. resizing this window causes the top of the window to be unaccessible. 

Like so:
![image](https://cloud.githubusercontent.com/assets/17632989/16962689/81c2da0e-4da7-11e6-900a-5ca4ffdb0c39.png)

![image](https://cloud.githubusercontent.com/assets/17632989/16962626/4f4ffdea-4da7-11e6-82da-5f7db929c924.png)

**Comment by billyeh** [comment]
Tested. Works. Probably was some bug with browser, `wiki` package, or bootstrap fixed by updating.
