### ISSUE TITLE
Testing Progress

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#336]
https://docs.google.com/spreadsheets/d/1i7hARS66lZYc2vBCdsLfNEfYsrW_SbwTgmGl-KwXXbk/edit#gid=605132957

I'm putting all my testing comments on this google spreadsheet. so check there :D

**Comment by rayoowoo** [comment]
or should i post everything on github?

**Comment by radicalray** [comment]
Hey @rayoowoo the excel doc may be too hard for devs to consume. Can you break it up into modules and push out into separate issues since each dev may be working on a different module (bug fix-wise)? Thanks!
