### ISSUE TITLE
Login Remember Me

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#337]
https://chriskief.com/2013/09/29/django-remember-me-option-at-sign-in/

```

remember_me = forms.BooleanField(required=False, widget=forms.CheckboxInput())

if not self.cleaned_data.get('remember_me'):
    self.request.session.set_expiry(0)
```

**Comment by billyeh** [comment]
Wait, it remembers by default for 2 weeks according to that article. I'm going to close this, then. That seems useful/reasonable to me. Although the current server logs out with every session.
