### ISSUE TITLE
Exams / Grades Bugs

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#342]
#### Entering scores (list view)
- [ ] entering scores should not be visible to a normal trainee. should be only for TA's and grading sisters
- [ ] reopen exams - doesn't work; also still needs feedback
- [ ] entering scores - 1st year test has helper TA's and other users on the list. needs to be changed.
- [ ] saving scores -there is a "save grades"" button on the top of the page and a ""save"" button at the bottom. what's the point of both?" 
#### Creating/Edit Exams
- [ ] editing/creating an exam -there is no place to indicate instructions - such as word count, things to remember, etc.
- [ ] printing paper exams -there's no way of printing the exam questions on paper directly
- [ ] creating an exam - the create exam functionality should only be seen by TA accounts
- [ ] creating an exam - if when creating an exam, you answer "NO"" for ""is exam open?"" you have to open the exam through Django admin. put something on the server?"
- [ ] inputting question points or exam duration - if you put letters instead of numbers, and try to create the exam, it's white screen.
- [ ] saving scores -there is a "create exam" button on the top of the page and a "create exam" button at the bottom. what's the point of both?" 
#### Taking Exams
- [ ] taking an exam -the 2nd year tests should only be seen by the 2nd year trainees, not 1st years; 1st years are not allowed to take the 2nd year test, but it shoul dnot be displayed at all

**Comment by radicalray** [comment]
- [ ] Get rid of so many try/catch in exams backend code. Will be hard to debug in the future and also slows down code execution.

**Comment by radicalray** [comment]
@rayoowoo All the duplicate save buttons are for convenience if page gets long.

entering scores - 1st year test has helper TA's and other users on the list. needs to be changed.

^ what does this mean?

**Comment by rayoowoo** [comment]
Oh that just means on the page where they enter scores for a first year exam, people other than first year trainees were listed

**Comment by billyeh** [comment]
Closing this as much has been rewritten. Can open new issues as they come up.
