### ISSUE TITLE
Other Attendance bugs

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#344]
#### GROUP LEAVE SLIP:
- [x] choosing trainees to be on the leave slip - however many trainees you select, the dropdown says you have that amount +1 selected
- [x] creating a leave slip - shouldn't creating a group leave slip require specific roles? or is it that the start and end time will automatically determine which rolls to be selected?
- [x] create a group leave slip - white screen
- [x] create a group leave slip - the start and end time input format is not clear
#### INDIVIDUAL LEAVE SLIP:
- [x] creating a leave slip - shouldn't creating a group leave slip require specific roles? or is it that the start and end time will automatically determine which rolls to be selected?
- [x] choosing a roll for leave slip - however many rolls you select, the mobile says you have that amount +1 selected
- [x] create a leave slip (with proper parameters) - white screen
#### VIEW SCHEDULE:
- [x] calendar at the top - the dates go from 7/24 to 6/25 - 6/30, when it should be all in July; same with 10/24 to 9/25-9/39
#### PERSONAL ATTENDANCE:
- [x] submitting a personal roll - nothing happens when i click submit; the user was marked as a self-attendance user. 
- [x] submitting a leave slip - nothing happens when i click submit
- [x] submitting a group leave slip - nothing happens when i click submit

**Comment by jontey** [comment]
@billyeh Check if this is still valid.

**Comment by billyeh** [comment]
These are all good. Some remaining attendance stuff in #457.
