### ISSUE TITLE
Room Reservation

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#375]
Maybe we can use this for our room reservation UI?

http://fullcalendar.io/js/fullcalendar-scheduler-1.3.3/demos/scale.html

@rochellewang Feel free to add to this all that you have done/researched for future PM's to continue your work. Thanks!

**Comment by rayoowoo** [comment]
Is this what is going to be displayed on the TV screens in the TV as well? Or are we going to display the old calendar format?

**Comment by jontey** [comment]
I don't think this is suitable for us to use. It is not easily customized for our needs
