### ISSUE TITLE
Environment settings bug during install

### ISSUE THREAD

**Issue by schai6** [attendanceproject/djattendance#385]
Install did not succeed unless I added os.environ.setdefault("DJANGO_SETTINGS_MODULE", "ap.settings.dev") in makeallmigrations.py.

**Comment by radicalray** [comment]
You shouldn't have to write the variable into code. You need to export the environment variable into your bash. 

Export DJANGO_SETTINGS_MODULE = "ap.settings.dev"

This should work automatically for you if you fpip your virtualenv correctly. 

Ray

**Comment by jontey** [comment]
+1 @radicalray
