### ISSUE TITLE
Room Reservation Request

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#393]
# Room Reservation Requests (Functional)

Room Reservations Requests is a module that is used by trainees to reserve rooms in the Training Center (TC) and the Ministry Conference Center (MCC). Related to this module is the TV display page. 

The rooms that are available for request are as follow:

MC (main classroom), NE209, NE210, NE212, NE213, NE215, NE216, NE217, NE218, NE219, NE220, NE221, NE222, NE223, NE224, NE225, NE3, NW201, SE132, SE238, SE239, SE240, SE241, SE243, SE244, SE245, SW120, SW227, SW229.

Rooms in the brothers' study area:
SE238, SE239, SE240, SE241, SE242, SE243, SE244, SE245

Rooms in the sisters' study area:
NE209, NE210, NE212, NE213, NE215, NE216, NE217, NE218, NE219, NE220, NE221, NE222, NE223, NE224, NE225

## Trainee Request Page

Each request submitted by the trainee must contain the following information:

* Team or Group (optional) - who is reserving the room. The input in this field is displayed on the TV display page in the TC. 
* Room or rooms being requested
* Number in group - the maximum number of people in the room at once.
* day / date requested
* start time - in increments of 30 minutes (due to the TV display page being in increments of 30 minutes)
* end time
* reason for meeting - the reason for the room reservation. not displayed on the TV display page

The request page also contains all the room reservation requests made by the trainee for the whole term, regardless of status. 

If the room being requested has already been reserved, the request is not allowed to be submitted. 

## TA Approval Page

The TA Page contains a list of pending requests made by trainees, for the TA to approve. A schedule all the rooms and the approved room reservations for that day is displayed. 

TA's are also able to manage which rooms trainees are able to make reservation requests for. 

## Workflow

The TA's have asked that the reservation be made 24 hours in advance. 

A trainee makes a room reservation request on the server. Then, a TA marks the request as approved, denied, or fellowship. 

If approved, the trainee will acknowledge the approval on their server. 
If denied, no further action is needed. 
If fellowship, the trainee comes into the office for fellowship. Afterwards, the status of the request is updated.

**Comment by rayoowoo** [comment]
# Room Reservation Requests (Design)

Room Reservations Requests is a module that is used by trainees to reserve rooms in the Training Center (TC) and the Ministry Conference Center (MCC). Related to this module is the TV display page. 

The rooms that are available for request are as follow:

MC (main classroom), NE209, NE210, NE212, NE213, NE215, NE216, NE217, NE218, NE219, NE220, NE221, NE222, NE223, NE224, NE225, NE3, NW201, SE132, SE238, SE239, SE240, SE241, SE243, SE244, SE245, SW120, SW227, SW229.

Rooms in the brothers' study area:
SE238, SE239, SE240, SE241, SE242, SE243, SE244, SE245

Rooms in the sisters' study area:
NE209, NE210, NE212, NE213, NE215, NE216, NE217, NE218, NE219, NE220, NE221, NE222, NE223, NE224, NE225

## Trainee Request Page
![pagre](https://cloud.githubusercontent.com/assets/17632989/21076708/812803ba-bee7-11e6-98ac-916e0beb4a32.jpg)

The request form is on the left of the page; the list of requests made by the trainee is on the right. 
Upon filling the date, start time and end time, the room being requested (which should be a drop down) menu will display only the rooms that are available. 

(forgot a submit button)

## TA Pages

### approval page

![ta approval page](https://cloud.githubusercontent.com/assets/17632989/21076710/86a23f5e-bee7-11e6-8595-88be69d2573a.jpg)

Training Assistants (TA) view a list of requests that need to be approved. He can select multiple requests and perform one action on all the ones selected. 

### Schedule view
![ta schedule view](https://cloud.githubusercontent.com/assets/17632989/21076711/8ac80e42-bee7-11e6-9bae-27897dd328ed.jpg)

The TA can view an entire day's room reservations at a glance.

## Workflow

The TA's have asked that the reservation be made 24 hours in advance.

A trainee makes a room reservation request on the server. Then, a TA marks the request as approved, denied, or fellowship.

If approved, the trainee will acknowledge the approval on their server.
If denied, no further action is needed.
If fellowship, the trainee comes into the office for fellowship. Afterwards, the status of the request is updated.

**Comment by jontey** [comment]
We need this on launch... at least the models... for the TV screens to continue working.
