### ISSUE TITLE
Add e-shepherding requests

### ISSUE THREAD

**Issue by jontey** [attendanceproject/djattendance#397]
Add e-shepherding requests to Web Access Requests
It is an automatically approved web access request for 30 minutes.

**Comment by ksungreborn** [comment]
Is this something on the trainee side? You request 30 minutes e-shepherding and you get internet access? Is there a certain time period during the week and each day where e-shepherding is allowed?

**Comment by jontey** [comment]
The specs can be found here
https://github.com/attendanceproject/djattendance/issues/203

**Comment by jontey** [comment]
Merge! Should start testing with the rest of the Web Access Requests Module @ichootheword

**Comment by swenghj** [comment]
Test done
