### ISSUE TITLE
Badges Print Options

### ISSUE THREAD

**Issue by miriamc09** [attendanceproject/djattendance#403]
![screen shot 2016-12-03 at 2 03 52 pm](https://cloud.githubusercontent.com/assets/19627516/20862509/a86909d2-b961-11e6-842e-e2063aaec39e.png)

In the middle section of this dropdown menu, there needs to be a feature to print "Mass-Print Back Badge for FTTA-XB" as well as to "Print 8 Back Badge for FTTA-XB" 

The back of the badges for FTTA-XB is different than for FTTA, so we need to be able to print a different back page for their badges.

**Comment by jontey** [comment]
@miriamc09 Do you know what is supposed to be printed on the back of the XB trainee's badge?

**Comment by miriamc09** [comment]
Yes, do you need me to give you a document? It's basically the address for the training center in Boston and some other text. This would be for both the trainees and the staff in Boston so we only need one print option for the back for anyone in XB.

[Boston back 8_FOR REAL.pdf](https://github.com/attendanceproject/djattendance/files/632836/Boston.back.8_FOR.REAL.pdf)

**Comment by jontey** [comment]
Fixed in 7019710
