### ISSUE TITLE
Broken sort function on badges page

### ISSUE THREAD

**Issue by allisonfaith** [attendanceproject/djattendance#405]
When I sort by term, it doesn't work. Some 4th termers are disbursed within the 3rd termers.
I attached two photos of the sort not working. I refreshed and did a fresh sort, still didn't work. 

![sorting by term again](https://cloud.githubusercontent.com/assets/19786868/20862567/2d4801f2-b963-11e6-9ef2-76dd2103eb4d.PNG)
![sorting by term](https://cloud.githubusercontent.com/assets/19786868/20862568/2d49ca96-b963-11e6-9641-36e3ddeb33d0.PNG)

**Comment by billyeh** [comment]
If you change their term to something else and change it back the sorting works for the misplaced ones. Data's just probably corrupted somehow, but I don't know how to access the ap.ftta.lan server.

**Comment by billyeh** [comment]
Haven't run into this this term, seems to be working. Gonna chalk it up to data corruption.
