### ISSUE TITLE
Life_Study_Page_Permissions

### ISSUE THREAD

**Issue by DrewHawthorn** [attendanceproject/djattendance#407]
Just discovered that if I am in possession of the url ( http://ap.ftta.lan/lifestudies/create-discipline ), then I am able to assign life studies to any trainee (confirmed that the assignment committed to Andrew Dina when logged in as Lisa and Andrew Dina.

Form submission might need to check credentials before committing.

**Comment by jontey** [comment]
At least you have to be logged in to view that page xD
Anyways good catch!

**Comment by radicalray** [comment]
This is a known issue because we haven't locked down any of our rest end points yet. Please see permissions page in wiki on how to lock down rest endpoints. Do this at the very end of our release since it could be done incorrectly easily and we waste a lot of time on a minor issue.
