### ISSUE TITLE
Absent Trainee Report: "Coming to class" defaults to checked when adding new trainee

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#427]
By being default checked when a new trainee is added, it appears like the coming to class checkbox doesn't save after pressing save.
![defaultchecked](https://cloud.githubusercontent.com/assets/23424787/21410839/96da77ce-c798-11e6-8638-80a1b771df9c.jpg)
It sometimes works and sometimes doesn't, and I'm not sure if using Safari or Firefox makes a difference.

**Comment by radicalray** [comment]
This is a really nasty bug. I thought I squashed it. You probably need to monitor very closely HTTP headers / POST vars sent back and forth. I believe the difference is between when you create a new form and when you update an existing form. Try that.

**Comment by ruthnan** [comment]
this bug also disappeared
