### ISSUE TITLE
Class Proxy Model

### ISSUE THREAD

**Issue by jontey** [attendanceproject/djattendance#428]
Class Proxy Model does not return Event objects with type==Class if the class was created using Event model and not Class model.

I'm not really sure if this is the intended behaviour for proxy models

**Comment by radicalray** [comment]
Please clarify description. Class proxy model should return Class-typed (which is a type of Event_ objects that are typed Class. If class was created using an Event model, it would return an Event object, and not a Class object (this is correct). This is to discourage you from creating a class using Event.

**Comment by billyeh** [comment]
We ended up fixing this in the last commit in #423. Thanks Ray! Yeah, if you query for `Class`, you should get `Class` objects, and `Event`s for `Event`. Looks like there was just a messy merge sometime in the past so `proxy = True` wasn't set and we weren't getting the results we were expecting from queries.
