### ISSUE TITLE
Prevent direct pushes to dev

### ISSUE THREAD

**Issue by radicalray** [attendanceproject/djattendance#433]
This might be one way to do it: https://gist.github.com/vlucas/8009a5edadf8d0ff7430

Please test out extensively before merging in. 

@billyeh

**Comment by billyeh** [comment]
I've seen this other method used before. I was surprised I was able to merge to dev actually haha. 

https://help.github.com/articles/about-protected-branches/
https://help.github.com/articles/configuring-protected-branches/

Seems to work pretty well.

**Comment by jontey** [comment]
My initial thought was to use protected branches too

**Comment by jontey** [comment]
Fixed.

**Comment by radicalray** [comment]
Thanks, @jontey! Have you guys tested it to make sure you can't push directly to dev before closing this ticket? Just checking.

**Comment by jontey** [comment]
Need someone else to check it. Apparently administrators can push directly onto dev regardless of permission. 

Src: http://stackoverflow.com/questions/18520618/disable-push-to-specific-branches-on-github#comment-66518860

**Comment by jontey** [comment]
@billyeh Could you test this out and report it back here? I'll reopen the issue and you can close it again if the fix works.

**Comment by billyeh** [comment]
Looks good!

```
(ap)billyeh@Bill:ap (dev) $ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 315 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/dev.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To https://billyeh@github.com/attendanceproject/djattendance.git
 ! [remote rejected] dev -> dev (protected branch hook declined)
error: failed to push some refs to 'https://billyeh@github.com/attendanceproject/djattendance.git'
```
