### ISSUE TITLE
House Forms Functional Docs + UI

### ISSUE THREAD

**Issue by ichootheword** [attendanceproject/djattendance#438]

**Comment by ichootheword** [comment]
# House Forms

## Purpose:

To allow trainees to request maintenance service, linens, or frames for their respective houses. For trainees who have access to the reports would use these to view their respective service-related reports (i.e. Maintenance Reports for Facility Maintenance, Linens Report for the Linens Sisters, etc.)

## Functions:

### House Reports:

**HC TRAINEES + DESIGNATED SERVICES** (e.g. linens sisters, maintenance)

**Maintenance Report**
HC trainees would generally not check this module unless making sure their maintenance requests were submitted and is visible to the maintenance brothers. 

Trainees designated for facility maintenance service would check this regularly for service times to know which houses need to be serviced.

**Linens Report**
Trainees that would check this regularly would be linens sisters for service times to see what houses/trainees requested.

**Framing Report**
Framing sisters would view the requests for service times to know which frames need to be fixed and where. 

**Furniture Report**
Furniture brothers would view furniture requests prior to service time. 

**MAINTENANCE BROTHERS**

For the majority of the times, maintenance brothers will probably only check 'Maintenance Report', unless asked to look at anything else. All other reports would be viewed by the trainees who are designated to serve in those areas (e.g. framing, linens, etc.)

**TRAINEES**

**Maintenance Requests**
Trainees from respective houses can request maintenance for various reasons, with specifications to: (1) type, (2) room, and (3) priority, either a routine check-up or an  urgent matter. Trainees are asked to describe the problem in detail for serving trainees' sake. 

**Linens Requests**
Trainees from respective houses can request linens specified by: item, quantity, and reason for request. 

**Framing Requests/Repairs**
Trainees can submit a request form for a quote they desire to be framed that was approved verbally by a TA brother. Trainees can also request existing frames to be repaired with detailed description of what is wrong with it. 

## Workflow:

### Trainees

**Maintenance Request**
Trainees who are submitting a maintenance request will go to the webpage, indicate which house they are, fill out the subsequent fields (type, room, priority) with a detailed description of the problem, and they would then save it. The maintenance brothers and those on the facility maintenance team will then review the request and respond accordingly to their availability. 

**Linens Request**
Trainees submitting a linens request would similarly go to the webpage, indicate what house they're in, fill out the subsequent fields (item, quantity, and reason for request), then save. The linens sisters will view the request and respond accordingly.

**Framing Requests/Repairs** 
Trainees who want to submit a frame request would go to the webpage, indicate which house they are requesting for, describe the location where the frame is to be placed, and type in the quote that is desired. Trainees will have to indicate whether the quote was prior approved verbally by a TA brother. Trainee would then save and the Framing Sisters would respond accordingly. 

### Maintenance Team

**Maintenance Report:**
Maintenance brothers view Maintenance Reports to see which trainee(s), house(s), or areas of the Training Center need attention.

### Framing Sisters

**Framing Report:**
Framing sisters view Frames Reports per request and respond accordingly. 

### Furniture Team

**Furniture Report:**
Furniture team views Furniture Report requests and respond accordingly based on schedule and availability.

### Linens Sisters

**Linens Report:**
Linens sisters view Linens Report and respond accordingly to each house(s) or trainee(s) request while keeping track of inventory and available supplies.

Possible UIs for House Forms:

![trainee view house forms home](https://cloud.githubusercontent.com/assets/17632988/21463897/8a848ecc-c925-11e6-97d7-e119dbb5c13a.png)

![trainee view house forms home 2 0](https://cloud.githubusercontent.com/assets/17632988/21463903/95416f4c-c925-11e6-9763-e1f5b572c4b2.png)

![mb furniture framing linens home view](https://cloud.githubusercontent.com/assets/17632988/21463905/a14c4c12-c925-11e6-8f0f-29c4b59b5abe.png)

![trainee view framing](https://cloud.githubusercontent.com/assets/17632988/21463907/b13a0cc2-c925-11e6-95b9-a558b9e25d18.png)

![framing sisters report view](https://cloud.githubusercontent.com/assets/17632988/21463909/b57d998e-c925-11e6-8c9b-959d5fdcfe91.png)

**Comment by billyeh** [comment]
@ichootheword I know you might not have finished this but I just wanted to ask before I start working on it--there doesn't seem to be a way to update the status of a request once it's done if we just have requests and reports here, right? 

Can we just have maintenance teams/TAs look at request lists kind of like we do for announcements and web access requests now? 

It looks like this:

![screen shot 2017-01-03 at 3 00 25 pm](https://cloud.githubusercontent.com/assets/2067277/21626355/6f78476a-d1c5-11e6-999f-566db5aa052d.png)
![screen shot 2017-01-03 at 3 00 38 pm](https://cloud.githubusercontent.com/assets/2067277/21626356/6f7b827c-d1c5-11e6-937b-de94dddd7964.png)

**Comment by ichootheword** [comment]
Hey Bill,

So sorry for the late reply! That sounds like a good idea. I didn't realize
we couldn't edit those requests once they were submitted. Hope this didn't
come too late for you.

How're you doing in Germany? Enjoying time with family?

I'm in Vancouver with Cindy until this Friday, then we're driving back down
to fly out from LAX on the 18th.

Isaac

**Comment by billyeh** [comment]
No problem, thanks for putting in time during the interim :) Yeah, I just didn't see a way specified to modify the requests/their statuses so just wanted to make sure we had a way to do that.

Germany is pretty great. Been doing some sleeping since I got sick but feeling better now. That's a pretty long drive. :o You guys should visit Berkeley on the way!

**Comment by ichootheword** [comment]
That's the plan! Though Berkeley has a winter retreat, so most of the
students won't be there, I think D: I might see them after, Cindy and I
will be in the area until the 17th.

Isaac

**Comment by billyeh** [comment]
Oh yeah forgot about that winter retreat :( maybe you should just join them there.

**Comment by ichootheword** [comment]
Lol am I allowed to? I'll probably just stay in the SF area and maybe I'll
get to see some of them after they're done. I'm hoping to have dinner with
David Tien on Monday night.

**Comment by billyeh** [comment]
They'd probably love to have you, they always got the classic trainees-sharing-on-morning-revival thing :D Yeah there's plenty of working saints you'll probably see, though some of them would go join the retreat on Saturday! :o

**Comment by billyeh** [comment]
Talked to Joon and to document" we have not done reports for this module yet. Also, the house field is automatically filled out as the submitter's house because I don't see why a trainee or non-trainee would need to submit a maintenance request for another trainee.

**Comment by billyeh** [comment]
Closing as this is not an actionable issue. We can always refer back, though
