### ISSUE TITLE
Inspection Pages

### ISSUE THREAD

**Issue by ichootheword** [attendanceproject/djattendance#451]
# Inspection Pages

## Purpose:
The main hub of all house-inspection-related functionality pages. The primary users are house inspectors and TA's to input data and review previous house scores of specific time periods. 

## Functions:
(Current Server)

VIEWABLE BY:
House Inspectors, TA's

### Enter Scores
Inspectors input house scores with the following data:
	1) House ID
	2) Date inspected
	3) RIC (Room-in-Charge for that inspection)
	4) Inspector (i.e. the trainee who inspected the respective house)
	5) Score
	6) Note
	7) Uninspectable house (check or leave box blank)

### Manage Inspectors
Customizes who has access to the Inspections Page and also which trainees are assigned House Inspectors. 

Q: Why are short-termers included in the list of possible inspectors? Functionality/design edit - make roster of possible inspectors only those currently enrolled in the FTTA.

### Manage Inspectable Rooms
Customizes which 'rooms' or houses are inspectable. 

*Possibly include an option to delete houses that are no longer viable (i.e. houses that are no longer FTTA housing), as well as adding new houses. 

### Itemized Inspection Report
Displays information in specific timeframes for brothers, sisters, couples, and all houses. Custom dates can be selected to produce reports of houses of time periods manually chosen by requester. 

*New design for reports format - reconsider order and display of information. Possibly have an option to view score per house.

### Average Inspection Report
Displays the average inspection score of each house, with both the minimum and maximum scores, standard deviation, and total number of times the house was inspected. 

### House Inspection FAQ
Submit a question for uncertainties that come along during house inspections. All previously asked questions and answers given can be displayed and viewed. Specific issues in the database can also be searched. 

Q: Who receives and answers these questions?

**Comment by jontey** [comment]
Related #659

**Comment by JoannaRumbley** [comment]
See new issue #1598
