### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by rayoowoo** [attendanceproject/djattendance#453]
|Module Name|Documented|Brainstorm|Functional|TA Approval 1|Basic Layout|Design|TA Approval 2|Development|Pull Request|Code Review|Merge Into Dev|Deploy|QA & Testing|Done!|
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|Absent Trainee Report|done|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Admin Tools|done|
|Announcements & Notifications|done|done|done|done|done|done|done|done|done|done|done|done|
|Attendance|done|done|done|done|done| | |done|
|Badges|done|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Rolls|done|done|done|done|done| | |done|done| |
|A/V Requests|done| | | |done|
|Bible Reading Tracker|done|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Boston Training|done|
|Class notes|done|done|done|done| | | |done|
|Exams & Grading|done|Allison|done|done|done| | | |done|done|done|done|
|Gospel Team|done|
|Gospel Trip|done|
|Graduation|done|
|Greek|done|
|House Forms|done|
|Importer|done|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Inspection|done|
|Life studies|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Meal Seating|done|done|done|done|
|Permissions|done|done|done|done|done|done|done|done|done|done|done|done|done|done|done|
|Reports|done|done|
|Resources|done|
|RFID Rolls|done|done|done|
|Room Reservations|done|done|done|
|Seating Chart|done|
|Semi-annual Training Test|done|
|Service Schedule|done|done|done|done|done|done|done|done|done|done|done|done|
|Syllabus|done|
|Web Access Request|done|done|done|done|done|done|done|done|done|done|done|done|
|FTTA-APP|

If there are more modules, just add it.

**Comment by ichootheword** [comment]
Consider adding 'PSRP Group Generator.' Doesn't seem it's being done through the old server, but possibly manually as of right now.
