### ISSUE TITLE
Bug: House Form Requests

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#493]
## Issues 
- [ ] Fix reports links: they are not shown (maintenance, linens, framing, furniture)
  : these links are for the HCs and designated service trainees 

- [x] Missing fields in submitting requests
   **house number is omitted for implementation purpose, but the house number is not shown when the request is created - fix whether in the form submission or in the form submitted**
  - [x] Maintenance - missing: 1) house number, 2) type, 3) room, 4) priority 
  - [x] Linens - missing: 1) house number, 2) item and reasons should be drop down menu? 3) how about urgent check box?
  - [x] Framing - missing: 1) house number, 2) check box(frame approved by TA brother), 3) change the title of blank, "Frame" to "Desired quote to be in frame: Must be a verse, footnote, ministry quote, or hymn AND must have verbal approval from a TA brother." 4) check box(Is a frame there already?)

**Comment by billyeh** [comment]
Closing because reports are being considered separately
