### ISSUE TITLE
Badges bugs

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#498]
* The facebook page has every person on a new line rather than in a row
(These next two are hard to test/reproduce. Seems different for every computer.)
* Badges are not printed correctly from Windows
* Pictures seem the wrong size when printed (? needs confirmation)

**Comment by billyeh** [comment]
#499 addresses item 1 and the badges team is waiting on this fix.

**Comment by jontey** [comment]
Merged #499

**Comment by billyeh** [comment]
Thanks Jon!

**Comment by billyeh** [comment]
Adding remaining todos to #160
