### ISSUE TITLE
Use media queries for printing things/reports

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#502]
There's a media query for styles that is used when printing from a webpage. https://stackoverflow.com/questions/355313/how-do-i-hide-an-element-when-printing-a-web-page

Maybe we should use this for reports and even things like the badges pages so it's easier to maintain in the future rather than creating separate pages.

**Comment by jontey** [comment]
Can we just use CSS media for reports instead of depending on a third party pdf converter like XTHML2pdf? 
@yipingbenjaminliu

**Comment by yipingbenjaminliu** [comment]
This actually looks quite good. Seems feasible, doesn't need any new plugins or anything just CSS. You can define the media query for printed pages with repeated headers and footers.

**Comment by yipingbenjaminliu** [comment]
#519 will take care of this
