### ISSUE TITLE
Date Error on attendance page

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#506]
- [x] I put in a leave slip for Tue 6/6 and on the summary section above the calendar view on the attendance page it says 6/5. Time zone issue...? idk 0679937
- [x] Also, on some computers the TAs show up as [Object] object

**Comment by billyeh** [comment]
Also, on some computers the TAs show up as `[Object] object`

**Comment by billyeh** [comment]
Closing since we can't reproduce the second error.
