### ISSUE TITLE
Tracking Trainee Rolls Finalization

### ISSUE THREAD

**Issue by jontey** [attendanceproject/djattendance#515]
There is a Statistics Model in accounts/models.py. Would it be possible to use that to track finalization rolls instead of using a dummy present roll? @billyeh

**Comment by billyeh** [comment]
I think we need to do this. Currently we have hacks in place for personal attendance and Bible tracker. Now we need to add finalization to HC rolls, team rolls, etc. so maybe we just add fields to `Statistics` like `attendance_weeks_finalized` and `bible_reading_weeks_finalized` similar to `Term.weeks`? Any other suggestions?

**Comment by yipingbenjaminliu** [comment]
We may need to reconsider implementing the redirect page with just one middleware in one of the modules. HC rolls and team rolls currently for procedure allows them to hand in a paper copy to the AMs box and then the AMs would input the data.

Double check with the office and the AMs if we want to transfer that responsibility to the respective trainees. Once it's confirmed, we can implement it into that one middleware for fixed redirect.

**Comment by yipingbenjaminliu** [comment]
@billyeh how do you feel about using one middleware, I'm thinking for notification, to implement force redirect rather than using middleware for both attendance and bible-tracker

@JoannaRumbley , is that accurate for the current procedure for submitting rolls for teams and HCs?

**Comment by billyeh** [comment]
In the team monitor/HC meeting last night the TAs said the team monitors/HC should enter the attendance on the server unless there's bugs preventing that, then the AMs will do that from the paper copy.

I'm not sure if I'm getting your question but just one middleware makes sense

**Comment by yipingbenjaminliu** [comment]
@billyeh , so procedure wise, the HCs and team monitors need to input roll on the server and they don't have the option of handing in a paper copy?

**Comment by billyeh** [comment]
They're supposed to do it on the server if it's not broken. They should still hand in paper copies though.

**Comment by JoannaRumbley** [comment]
So for HCs, taking house roll online works. (great job!) 
But apparently the status says "Submitted" before and after they actually submit roll. 
And I heard they stopped handing out paper forms this past week. (shouldn't be a problem since it works online)

**Comment by JoannaRumbley** [comment]
@yipingbenjaminliu Sorry for the late reply. Yes, the old procedure was for HCs and team monitors to take roll on a slip of paper and turn it in to AMs. Just like Bill confirmed. :)

**Comment by yipingbenjaminliu** [comment]
Okay, I'll implement this and work on the force redirect for HCs, team monitors and ypc rolls.

**Comment by yipingbenjaminliu** [comment]
#1281
