### ISSUE TITLE
Seating Chart Adding Extra Elements

### ISSUE THREAD

**Issue by jontey** [attendanceproject/djattendance#516]
I noticed that the seating chart that gets printed out has extra elements that are not trainee seats, eg. empty seats, Piano, AV Box, Podium,  etc..

**Comment by billyeh** [comment]
#502

**Comment by ruthnan** [comment]
Can we combine this issue with enhancements in #274?

**Comment by billyeh** [comment]
Let's combine them. Haha why is everyone working on this right now?

**Comment by ruthnan** [comment]
haha, idk! i also noticed @finben has been closing lots of issues... i'm just relaxing in the comfort of a saints' home in MPK, so nothing better to do, besides study for MoHL
