### ISSUE TITLE
Bugs in the Leave Slips

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#526]
- Bugs in the **Individual Leave Slips** 
  - [x] summary for the leave slip - date is off by one day 0679937 #506
    - [ ] verified?
  - [x] occasionally pops up message when creating - "Please select a TA" (Red) 1b7588f
        : this does not create any error in the web console 
    - [ ] verified?
  - [x] editing the submitted leave slip not working 1e2f51e
        : select one from summary, and select another time slot then submit again - 500 error 
        : same scenario for the group leave slip works fine, editing with another time slot
    - [ ] verified?
  - [x] reason - meal out location and host name e9da761
        : select "meal out", then you see "Location (address for **night out**)"
        : do we need host name? do you mean restaurant name? 
    - [ ] verified?

- Bugs in the **Group Leave Slips** 
  - [x] summary for the leave slip - time is off 
    - [ ] verified?
  - [x] group leaveslip that doesn't include current trainee shouldn't show on summary or calendar view 12acad0
    - [ ] verified?
  - [ ] time slot selection 
        : please confirm with design intention - it does not allow selecting individual time slots
        - [ ] verified?
  - [x] please put condition check for the number of trainee name 37d1f9f
        :  group leave slip must be at least two trainees - compare with the old server 
        - [ ] verified?
  - [x] reason 
        : why group leave slip does not have “night out”, “meal out” ?
        - [ ] verified?
  - [ ] the calendar doesn't show rolls/leaveslip statuses when submitting group leaveslips on the old server. Do we want to do this for the new server? (probably)
    - [ ] verified?

**Comment by billyeh** [comment]
> : why group leave slip does not have “night out”, “meal out” ?

This is how it works on the old server. I'm not 100% sure why there's no night/meal out group leaveslip. But one reason I can think of is that displaying the last night/meal out for the group doesn't work in the current UI. Maybe this is a feature we can think about implementing later?

**Comment by billyeh** [comment]
>  summary for the leave slip - time is off
Gonna need someone to reproduce this. Maybe it's been fixed somehow? :)

**Comment by swenghj** [comment]
>> : why group leave slip does not have “night out”, “meal out” ?

>This is how it works on the old server. I'm not 100% sure why there's no night/meal out group leaveslip. But one reason I can think of is that displaying the last night/meal out for the group doesn't work in the current UI. Maybe this is a feature we can think about implementing later?

Thanks for checking. I think then we can leave it the same, and in the future if someone complains about it, then we can fix it that time. 

>> : do we need host name? do you mean restaurant name?
>> : select "meal out", then you see "Location (address for night out)"

> I think the items quoted in this comment are kind of arbitrary text where the old server isn't necessarily perfect either. How I feel is that if it works, it's fine. But if there's a design/UX reason to change it that's cool too!

the old server looks fine to me in both night out and meal out case. It specifies differently such as 

    Where you can be reached for your night out:
    Where you can be reached for your meal out:

For the night out, the input fields follow the design of old server, but for the meal out, the design intend looks different. We can bundle them together with one string, "Location" as the fix submitted, but we can check with design team. 

>>  summary for the leave slip - time is off

> Gonna need someone to reproduce this. Maybe it's been fixed somehow? :)

I can help you :)

**Comment by billyeh** [comment]
Thanks Joon!
