### ISSUE TITLE
Bugs in the TA view on Leave Slips

### ISSUE THREAD

**Issue by swenghj** [attendanceproject/djattendance#527]
- [x] view detail - time slot is not marked on from the leave slip submission 
    - [x] individual leave slip
    - [x] group leave slip
- [x] comments on the individual leave slip and saving not working - trainee name error 
- [x] what is the purpose of "description" box? and it is greyed out? 
    : is the comments of the leave slip supposed to be in the description box, not in the comment area?

**Comment by swenghj** [comment]
@iamsitting : this is for tracking purpose. Once the fix is merged, I will double check later.

**Comment by yipingbenjaminliu** [comment]
#666 to address this
