### ISSUE TITLE
Roll and Trainee deletion cascade

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#548]
Look at relationship between a trainee and rolls, seems like deleting a trainee won't delete rolls resulting in null rolls that can't be deleted from the admin view.

**Comment by jontey** [comment]
I don't think this has to do with the delete cascade but with the Trainee object manager only selecting active trainees. So previous term's trainees will appear as null on the roll admin page

**Comment by yipingbenjaminliu** [comment]
#597 will solve it.
