### ISSUE TITLE
Class attendance rolls to seating chart not correlating

### ISSUE THREAD

**Issue by ksungreborn** [attendanceproject/djattendance#559]
The class attendance rolls to update trainees' attendance does not correlate with seating chart (some people are missing from the chart in class attendance roll view)

**Comment by ruthnan** [comment]
I think this is because the schedule that the events are assigned to don't have a term associated with it/we can't see anything on the schedule-side on the admin page. related to issue #562

**Comment by jontey** [comment]
Actually the issue is that the event has last term's seating chart associated with it.
![screenshot-2017-9-23 change event ftta admin](https://user-images.githubusercontent.com/1665131/30779383-a40c7c0a-a0a3-11e7-90ac-6dcee54f5821.png)

Seating chart should be Fall 2017, not Spring 2017

**Comment by jontey** [comment]
nvm.. that didn't change anything

**Comment by ruthnan** [comment]
Yes, I tried with various classes already...

**Comment by jontey** [comment]
Fixed in #579
