### ISSUE TITLE
Group leave slip

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#573]
Individual leaveslips show up fine, but for group leaveslip no events show up. Look at JZ Hung on the live server.

**Comment by jontey** [comment]
i didnt see any group leaveslips for JZ on live server

**Comment by yipingbenjaminliu** [comment]
she wasn't able to submit any group leaveslips.
![image](https://user-images.githubusercontent.com/8671058/31056403-e6dd1f84-a685-11e7-8b3f-9a008677e17e.png)

![image](https://user-images.githubusercontent.com/8671058/31056404-efd5654c-a685-11e7-951f-cc2e08a04d13.png)
so she would switch from personal to group and see nothing

**Comment by billyeh** [comment]
Fixed this I think. "Group Events" was the name of the schedule, seemed to have all the trainees and events. I only changed its `term` value to Fall 2017 and they show up now.

**Comment by yipingbenjaminliu** [comment]
@billyeh , problems resurface, could you take a look?

**Comment by billyeh** [comment]
That's what this line was for  https://github.com/attendanceproject/djattendance/commit/8f32781dc7783260edd8a4b1a392362fd93a5dd0#diff-a56114035785ef8a50e1633111057b6aL21

This isn't really an issue. What we need is #635.
