### ISSUE TITLE
Maintenance Requests dropdown list

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#574]
maintenance requests for a user can choose more than their own house

**Comment by iamsitting** [comment]
This seems to be a data entry issue. According to the old server the user should be able to see a list of generic 'rooms' i.e:
![screen shot 2017-10-02 at 4 59 17 pm](https://user-images.githubusercontent.com/8170930/31104705-4c2bc6de-a793-11e7-9728-a8cb79c9486a.png)

Do we want to keep it this way?

**Comment by billyeh** [comment]
#578 looks good for now. Doesn't look like the old server actually keeps track of house rooms or bunks right now? Which explains the generic list. We can do something similar.
