### ISSUE TITLE
Come up with standard for notifications and menu

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#577]
See also #575.

A few questions:

* what goes in the topmost menu?
* what goes in the submenu which appears only on certain pages?
  * attendance has the submenu from the topmost menu appear
  * lifestudies TA view, services and badges have a submenu different from the topmost menu. Maintenance requests should probably have something similar (?)
* what does the submenu look like for different kinds of notifications (e.g., when something is submitted)?

It's important to come up with a standard so that we can start coding with it and make all these different pages uniform.

Somewhat related: notification link/text needs to be customized to the alert color because it's unreadable sometimes right now.
![screen shot 2017-10-05 at 12 33 38 pm](https://user-images.githubusercontent.com/2067277/31248673-77630ffa-a9c9-11e7-95fc-274db424e1f5.png)

**Comment by caricchow** [comment]
a lot of the answers to these questions can be found by looking mockups on the dropbox. **attendance project > djattendance > design - miriam > pages.**

**Comment by caricchow** [comment]
let me know what questions you still have that the mockups can't answer and I will look into them. thanks!

**Comment by billyeh** [comment]
👍  ok thanks Caric!

**Comment by billyeh** [comment]
Conclusion: keep the submenu on top only when clicked, other pages shouldn't have those menu bars. Alert text still needs to be fixed.
