### ISSUE TITLE
Room Reservation submit button

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#582]
Room Reservation button is hard to access because it's too close to the edge. The scrolling table also makes it a little difficult to scroll down to the page. Also, the attendance page feels like it should have a little more white space outside of the gray border?

![screen shot 2017-10-07 at 3 41 32 pm](https://user-images.githubusercontent.com/8170930/31312383-50815faa-ab76-11e7-96bb-b02983a4465b.png)

**Comment by billyeh** [comment]
Idea: we should add a footer thing with some copyright/info so all the pages will have some padding on the bottom
