### ISSUE TITLE
Group Leave Slips extra element covers the border

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#584]
There is a input.rw-input box (role: listbox) that blocks a bit of the border in select trainees.

![leaveslip_glitch](https://user-images.githubusercontent.com/23424787/31312427-a387713e-ab77-11e7-87de-3f6312e6f423.jpg)

![leaveslip_glitch2](https://user-images.githubusercontent.com/23424787/31312426-a06db152-ab77-11e7-828b-3e4740b4fc32.jpg)

**Comment by billyeh** [comment]
Looks fixed. Please re-open if it still shows though. I think we updated the package?
