### ISSUE TITLE
Bible Reading Tracker - ability to save previous weeks?

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#592]
Should we allow the trainee to be able to update the previous weeks' bible reading? On the current server, you can save but not finalize. On the new server, you have to ask the TAs to input the bible reading for you if it's for a previous week.
![brtbug](https://user-images.githubusercontent.com/23424787/31791335-163b54f8-b4cd-11e7-91f8-d9543ca4a529.jpg)

**Comment by billyeh** [comment]
Also TAs need a way to help trainees finalize previous weeks

**Comment by czhaocmu** [comment]
TA’s should be able to finalize any week. But you can check by testing it.
