### ISSUE TITLE
Exam auto-grading

### ISSUE THREAD

**Issue by ksungreborn** [attendanceproject/djattendance#605]
- [x] Not sure what changes were made to the exam auto-grading part, but after making a test with one of each type of question and taking the test, the exam score is incorrect for what seems to be more than one category of question.

- [x] Also I had previously set the default to: after a trainee finalizes an exam, on the TA view, they must finalize the exam score on their side because of any essay portions that need to be read and graded (for essay questions the score would be 0 until a TA grades it). Now it appears the exam score is already finalized on the TA view with the exam score being '0', which should not be right? Unless we want the trainee to see their score without the essay portion being graded right after they take it? In that case the TA needs to ensure they unfinalize every exam and score the essay portion?

**Comment by billyeh** [comment]
Related: I think for exams we should have a way for trainees to peer-grade essays because that's what we usually do in class.

**Comment by ksungreborn** [comment]
Good idea. I can work on that.

**Comment by ksungreborn** [comment]
Also just noticed a few more bugs:
- looks like 'Add Question' button only works for the first question, after that no more questions are generated for a section.
- total exam score for a test still looks off when I do "VIEW GRADED RESPONSES"

**Comment by billyeh** [comment]
#608 addressed remaining issues
