### ISSUE TITLE
Show commuter names - for attendance monitors

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#621]
Attendance monitors want to be able to search the trainee list to see who are commuters. 

Right now, in ap.ftta.lan/admin a commuter house will show " - " and  not "commuter." We want to be able to search "commuter" and get the list  of names.

**Comment by billyeh** [comment]
They can see the list of commuters now http://ap.ftta.lan/admin/houses/house/?p=2

**Comment by JoannaRumbley** [comment]
It works, but attendance monitors can't see the Houses tab/page.

**Comment by yipingbenjaminliu** [comment]
On which page is this supposed to be?

**Comment by JoannaRumbley** [comment]
Admin > Houses > Houses

**Comment by billyeh** [comment]
they can see them now b3faa97a2f156024d7f4f5cdd01ae63669c9b893
