### ISSUE TITLE
Notification Bell

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#622]
<img width="1438" alt="screen shot 2017-11-25 at 4 20 15 pm" src="https://user-images.githubusercontent.com/29343365/33236053-c857be82-d1fc-11e7-968b-1a872375dc61.png">

1) Notification popup needs to disappear when you click any other element.
2) Width of subnav bar should reach all the way across the page.

**Comment by billyeh** [comment]
Hmm what website is it that looks like this? I can't reproduce this.

**Comment by caricchow** [comment]
@billyeh ap.ftta.lan - it can be seen on any trainee identity

**Comment by finben** [comment]
The subnav bar has been obsoleted by the new homepage. Going to close out.
