### ISSUE TITLE
Interim intentions form

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#624]

**Comment by yipingbenjaminliu** [comment]
#972

**Comment by JoannaRumbley** [comment]
I just had to comment on the layout a little...take it or leave it.
@caricchow I'd say, feel free to advise the devs on the most important design/UI changes. The image below is my feeling about it; please comment if you disagree or feel that another change would be more important. 😄 

![image](https://user-images.githubusercontent.com/33075368/39893088-8fc4f1ba-5457-11e8-888e-9b293d8e3c21.png)

**Comment by yipingbenjaminliu** [comment]
#972 addressed.
