### ISSUE TITLE
Room Reservations Admin Page

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#630]
![change_room___ftta_admin_and_https___trading_scottrade_com_handlers_confirmations_displayconfirmation_ashx_id_796334221](https://user-images.githubusercontent.com/23424787/33520235-9468f572-d76b-11e7-97cb-ba33a91c3943.png)

When you change the code value for the room on the admin room page, the action creates a duplicate entry with the same values except for code and doesn't edit the code value.

![select_room_to_change___ftta_admin_and_https___trading_scottrade_com_handlers_confirmations_displayconfirmation_ashx_id_796334221](https://user-images.githubusercontent.com/23424787/33520280-924f17d4-d76c-11e7-992a-a15bf4d24ebc.png)

**Comment by billyeh** [comment]
Not an issue - the room code is the primary key https://github.com/attendanceproject/djattendance/blob/dev/ap/rooms/models.py#L51 https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.Field.primary_key
