### ISSUE TITLE
TA cannot edit LS number or type of offense & word count

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#631]
- [x] TA cannot change the number of life-studies assigned nor the type of offense, when assigned.
Also
- [x] make word count visible to TAs
- [ ] Life study assignment currently broken

**Comment by billyeh** [comment]
Word count looks like it appears on TA page http://ap.ftta.lan/lifestudies/71/approve-summary

![screen shot 2017-12-06 at 7 09 53 pm](https://user-images.githubusercontent.com/2067277/33696888-2ad7d1ae-dab9-11e7-83ce-b088e6f9eeee.png)

**Comment by yipingbenjaminliu** [comment]
fixed.
