### ISSUE TITLE
Issues with WAR

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#633]
- [ ] For the TA, the web access requests are approvable and deniable after being denied and approved.
- [ ] On the user's side, after starting the web access request, the button is still clickable.
- [ ] There should be some kind of indication that the web access request has started; maybe a time-counter?
- [ ] Needs to be way for trainees to restart web access requests

**Comment by jontey** [comment]
> Needs to be way for trainees to restart web access requests

Maybe name it "Resume" instead of restart
