### ISSUE TITLE
Group leave slip needing a generic schedule

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#635]
Prior to launch we need a generic time based event schedule for group leave slips to be selected.

**Comment by isaactsou** [comment]
for clearer error message when submitting leave slips state: "please select the time and day of the event" instead of "please select an event"

**Comment by isaactsou** [comment]
or "please select the time(s) and day(s) of the event(s)"

**Comment by yipingbenjaminliu** [comment]
#666 addresses this
