### ISSUE TITLE
Afternoon events in schedule not showing up

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#642]
created population script simulates a generic campus schedule, all the afternoon events for the schedule isn't showing up.

Pull from the latest demo branch to see

**Comment by billyeh** [comment]
Was working on #635, ran into this. Issue is this line https://github.com/attendanceproject/djattendance/blob/dev/ap/accounts/models.py#L499

The `memoize` prevents new events from being added after the server starts running (confirmed by restarting server, new changes show up).

**Comment by yipingbenjaminliu** [comment]
confirmed locally, this works.
