### ISSUE TITLE
Functionalities for Attendance Monitors - Add Roll page

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#670]
In ap.ftta.lan/admin site:
Under Attendance:
- [x] Be able to search for rolls
- [x] Be able to add a corporate roll (a roll for multiple trainees)

Under Attendance => Add Roll:
- [x] Add search function for Event and Trainee 
- [x] Automatically fill in the Submitted By box with the user name (set default to user)

**Comment by JoannaRumbley** [comment]
Be able to add a corporate roll (a roll for multiple trainees):
--> They can do this on the main server, not the /admin site

Automatically fill in the Submitted By box with the user name (set default to user)
--> Not auto fill, but search function is there

**Comment by ryanli633** [comment]
Addressed by #686
