### ISSUE TITLE
Functionalities for Attendance Monitors - Schedules pages

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#671]
In the ap.ftta.lan/admin site:
Under Schedules => Schedules => (select a schedule):
- Let AMs know that for adding/removing a trainee to/from a schedule, if they type a name a second time then it removes the trainee. In the search dropdown list, trainees in grey are selected; trainees in white are not selected.

Under Schedules => Schedules:
- [x] Review column display
- [x] Add search functionality
- [x] Create feature to duplicate a schedule

**Comment by yipingbenjaminliu** [comment]
#685 address this
