### ISSUE TITLE
Designer Issues with Existing FTTA Server

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#680]
- [ ] TA View needs to show information about the approved room reservations, not just the room schedule (maybe the room schedule lets you get to the room reservation request from the 
![ftta___room_reservation_schedule](https://user-images.githubusercontent.com/23424787/34315339-1fc369c8-e733-11e7-8560-5db4e896cca1.png)

**Comment by iamsitting** [comment]
Addressed in #707
