### ISSUE TITLE
Linens Request Form

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#682]
The current linens request form has 2 extra items: **Hand Towel**, and **Shower Curtain Rod**. These can be removed on the new server. 

*Gabby Prior informed me of this and she said she had already asked/talked with sister Veronica about it. (Because hand towels are not used, and shower curtain rods might be with the maintenance brothers instead of the linens sisters.)

**Comment by yipingbenjaminliu** [comment]
#683 will address this
