### ISSUE TITLE
for Attendance Monitors - Leave Slips

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#684]
Attendance monitors edit leave slips for weekly services. They access it by: 
**Generate Service Leave Slips** =>**Edit Service Leave Slips** => **Edit**
Which brings up the list of names for the service they selected:
![image](https://user-images.githubusercontent.com/33075368/34315030-10a437e0-e749-11e7-871b-659b681e6c66.png)
*I erased the names, but you can see that next to each name is a dropdown for:
Present, Absent, Replaced, Volunteer, and Remove

They said they don't use Volunteer or Remove. So, those options may be removed on the new server. Currently, they use another way to enter in volunteer names.

**Comment by yipingbenjaminliu** [comment]
already existing as a functionality within the server, currently cannot filter by service but is able to individually do it.

**Comment by yipingbenjaminliu** [comment]
@finben @jontey , how does the new server handle service rolls?

**Comment by jontey** [comment]
It's not implemented...

**Comment by billyeh** [comment]
They can use the admin page to edit leaveslips.
