### ISSUE TITLE
Jerome's Feedback Minor Changes

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#718]
- [ ] Categorizing trainees panels…
- Leaveslips
- Tardies
- Absences
- Life Studies
- Class Notes

Smart menu
- [x] Order alphabetically 04f9db314c5f7d9cb05be40964681c39a4da1ea1

Maintenance
- [x] Requests go to certain trainees
- [x] Trainees on service can pull reports
- [x] Colonial should not exist, Neptune should not exist
- [x] Make maintenance, framing, and linens groups

Lang/Char
- [x] Rename to something general
- [x] Other category

Nomenclature:
- [x] Leave slips is two words.
- [x] Class notes is two words.
- [x] Rename current tab (for fobi)

Other:
- [ ] Class Notes Legend
- [ ] Form generalization
- [x] Force trainees to Bible reading and attendance. They cannot use other features until this is filled out.
- [ ] Discipline for missed service rolls
- [x] Change radio to select on TA select for attendance
- [x] Training Office Informed add “?” d9d75d401f3309fc1443618a7f1bd259bdca34e7
- [x] Change label
	- Yes,
	- Yes, by attendance number
	- No

Room Reservation:
- [ ] Add “no preference” to room selection
- [x] Frequency: all lowercase
- TA Room Reservation Request:
	- [ ] Remove Reason
	- [ ] Remove pending default
		- [ ] Pending are on top
	- [ ] Schedule
		- [ ] Add actions to schedule
		- [ ] Show room reservation on 
- [ ] Make consistent as other maintenance requests
- [ ] TA View make consistent (frontend)

- [x] Profile picture squished

**Comment by finben** [comment]
Not sure if we still need this... Probably just going to work off his list now
