### ISSUE TITLE
Use Fobi to allow bug reports

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#728]

**Comment by jontey** [comment]
Look at one of the PRs. Someone made a bug issue tracker that posts
automatically to a separate GitHub project.

**Comment by billyeh** [comment]
Closing this. I don't think we want to use fobi for bug reports, hard copies seem to be working okay. And we have an open pull request to remind us of this issue

**Comment by JoannaRumbley** [comment]
sorry to bring this up again...which PR was that?
It may be good to transfer the bug report form onto the server at the start of next term or the term after.
