### ISSUE TITLE
Bible Tracker page - Daily tab

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#737]
(From Austin)
Daily tab:
No way to remove a CMN state if pressed (unless you refresh the page before saving it). Relevant if I choose the wrong week on the dropdown menu. (I now have completed my Bible reading for Monday on week 9 when it is week 0)

**Comment by iamsitting** [comment]
#735 - limit weeks before and up to current week. They don't need remove a state after submission.
