### ISSUE TITLE
Double scroll bar on multiple pages

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#738]
Double scroll bars on these pages:
- Bible tracker page - 1st and 2nd year tabs
- Home page
- Attendance - when the page size is shrunk, all tabs (Summary, personal slips, group slips)
- basically any page that needs a scroll bar has 2 scroll bars

There are 2 scroll bars... One controls the inner frame. Not sure what the other is doing.
![image](https://user-images.githubusercontent.com/33075368/36400522-625a3790-159f-11e8-9e5c-cbdf189bbf3a.png)

It's on the home page too...
![image](https://user-images.githubusercontent.com/33075368/36400472-0fefc524-159f-11e8-85f9-5b5290c5ba7f.png)

**Comment by iamsitting** [comment]
#735 addressed

**Comment by yipingbenjaminliu** [comment]
#752 fixes it, needs to add overflow to the individual css
