### ISSUE TITLE
Attendance page

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#740]
(From Austin)
Under training office informed: [object Object] is displayed by default if "Yes, by a TA" is selected
![image](https://user-images.githubusercontent.com/33075368/36400602-e722c91a-159f-11e8-8723-107f30161de5.png)

**Comment by yipingbenjaminliu** [comment]
Data issue, Trainee needs to be assigned a TA.

**Comment by JoannaRumbley** [comment]
But then, it's possible for a trainee to forget to check that box and just submit the slip. So the form would say they notified a TA when they may not have. 
Can we make the default choice on the first drop-down just a blank space?

**Comment by billyeh** [comment]
This has been resolved.
