### ISSUE TITLE
attendance monitors needs to be able to search of service leaveslips

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#745]
attendance monitors needs to be able to search for specific trainees in group leaveslips

**Comment by billyeh** [comment]
I added some code in 23c56d318c1968c1a8bd5dcb8c849a1e9ba6ffab that allows them to filter by service assignment, not sure if that's good enough or what else we can do to help

**Comment by iamsitting** [comment]
#749 - done
