### ISSUE TITLE
Reconsider Room Reservation for UI/UX

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#746]

**Comment by ruthnan** [comment]
Wait for my commit @joeyu23

**Comment by finben** [comment]
@caricchow @xuefeizheng I don't see that we have a design document for this. Maybe the design team can come up with one for room reservation page?

**Comment by JoannaRumbley** [comment]
See #1151 
@isaactsou is working on it. Closing this one since it's a duplicate of #1151

**Comment by JoannaRumbley** [comment]
Actually...let's keep this one open since it's already assigned to ppl. :)
When it's done, please check it off on 1151. Thx

**Comment by iamsitting** [comment]
Let's close this. The designers are assigned in #1151
