### ISSUE TITLE
SS admin page worker groups defines number of workers needed by the filtered candidates.

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#754]
So under services >> Worker slots, you cannot edit the workers required, because it automatically sets it based on the Worker group, which is fine because you can change the worker group, but it looks like it's using the filtered query (worker count 1 for AP service) instead of the workers. I don't exactly see this on the localhost, but on the live server, it has this issue.

![change_worker_group___ftta_admin](https://user-images.githubusercontent.com/23424787/36516535-53295568-1733-11e8-8ea0-2a83e40c2310.jpg)

![change_service___ftta_admin](https://user-images.githubusercontent.com/23424787/36516571-7d1504d0-1733-11e8-8616-2baba73ece33.jpg)

Filter only has one worker
![select_worker_group_to_change___ftta_admin_and_notes](https://user-images.githubusercontent.com/23424787/36516658-f37a4126-1733-11e8-8121-c676dc6ceede.jpg)

![change_worker_group___ftta_admin](https://user-images.githubusercontent.com/23424787/36516629-d07b89fa-1733-11e8-8212-766fcef4b7d3.jpg)

Tagging @ryanli633 because I told him incorrectly earlier about assigning worker groups.

**Comment by jontey** [comment]
That is because the service is set as a designated service.
