### ISSUE TITLE
TA Feedback

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#755]
Start of list of items.

**HIGHEST PRIORITY**
- [ ] TA sisters need a way to transfer leave slips and reassign to different TA brothers. Related to this but not as high of a priority is if they could transfer multiple to a TA brother at once instead of having to hand click one leave slip at a time

- [ ] Leave slips should still be able to select the notify TA brother column. This would not reassign the leave slip to them however it would make them as well as the assigned TA brother aware of who the fellowship was with

- [ ] Page goes blank when you approve a life study

- [ ] Attendance report called AR is a statistic report on the old server that will be needed in a few weeks because it is used to send to the localities 

- [ ] TA's need the ability to submit rolls outside of hours. Sometime attendance brothers come in to ask them to submit a roll if they didn't make it by the cut off time. TAs should have attendance monitor access. TAs should be able to Personal Attendance for each Trainee.

**MEDIUM PRIORITY**
- [ ] Change the exclamation point when a leave slip is marked for fellowship. Change it to the character F

- [ ] Implementation of force page by Wednesday if a trainee has not submitted bible reading for the past period then they will be confronted with the page and forced to take action before moving on using the service

- [ ] Past leave slips need to still be viewable on the site to the TA's as of now they are unable to see them once they are approved 

**LOW PRIORITY**
- [ ] Did not inform TA needs to be explicitly defined on the TA view of a leave slip

- [ ] Inconsistency problem. On TA leave slip list if you hit view all there is the field Reason but within a leave slip it is defined as Type. They should both show Reason

- [ ] Icons on trainee view of if leave slips are approved, or denied currently are all to similar all using a black + or -. Instead the icons should be color based to make for easier interpretation 

- [ ] Search bar requested when TA's are looking at all life studies

- [ ] Statistic tracker to catch trainee's who regularly skip one type of activity for example PSRP 

- [ ] A way for the office to view designated service trainees

- [ ] A link from class notes to actually take you directly to audio request page for trainees

- [ ] Ability to actually delete leave slips

Smart menu
- [ ] Not all TAs want to see everything, but they want the access? Do they want customized panels and menus?

Maintenance
- [ ] Leave slip should be two words on "Leaveslip" page.

**Comment by jontey** [comment]
Not all TAs want to see everything, but they want the access? Do they want
customized panels and menus?

Didn't see that coming....

**Comment by iamsitting** [comment]
Closing. Duplication of #755 and #756. We can merge the issues. This one has a little more details.

**Comment by JoannaRumbley** [comment]
"Not all TAs want to see everything, but they want the access? Do they want
customized panels and menus?"

For this, could we put all the pages they don't want to see under a "More" menu? 
For them to choose what not to see, would it be easier to:
**1.** Make a "Settings" page for them to checkbox what they want to see and put the unchecked menu items under "More"?
Or, **2.** Make an invisible "-" (minus sign) next to each menu item on the home page. When they mouse over an item, the minus "-" would show up next to it. And they can click the "-" to move it to the "More" menu.
