### ISSUE TITLE
All TA Feedback - Medium/Low Priority

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#757]
- [x] Change Leaveslips to Leave Slips 06cb753c86bba2a7e5d67d57ef4a2802905cc429

- [x] On Leave Slips clearly show which is TA informed and TA assigned. (May be just a documentation issue.) e4e8970ef541139e0f985ec2349279abed12e7d4

- [x] Change Fellowship Mark from "!" to "?" or "F" a0f80e34587206fb3abd949ac7f6a424a6413ca6

- [x] Preview Description or Reason in ListViews of Leave Slips and Web Access Requests cbcc9a683d397f8ec9a2346689a89a2d9934b546

- [x] TA Leave Slips make consistent Reason and Type fields cbcc9a683d397f8ec9a2346689a89a2d9934b546

- [x] Add email column to Trainee Information Table a9b004531af853c336338dc3cb51c240b4249169

- [x] Designated Service Viewer #824

**Comment by JoannaRumbley** [comment]
Referencing #755 

"Not all TAs want to see everything, but they want the access? Do they want
customized panels and menus?"

For this, could we put all the pages they don't want to see under a "More" menu?
For them to choose what not to see, would it be easier to:
1. Make a "Settings" page for them to checkbox what they want to see and put the unchecked menu items under "More"?
Or, 2. Make an invisible "-" (minus sign) next to each menu item on the home page. When they mouse over an item, the minus "-" would show up next to it. And they can click the "-" to move it to the "More" menu.
