### ISSUE TITLE
Service Exception Frontend - Urgent

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#759]
- [x] ServiceException Frontend with TraineeSelectForm. The TraineeSelect filters are very critical when making Service Exceptions. (In Progress: 967ef42a378f78dbf296d16f4c0db443def979c7)

**Comment by iamsitting** [comment]
#822

**Comment by billyeh** [comment]
This probably needs work but closing for now since something has been merged for this.
