### ISSUE TITLE
Export maintenance requests as excel file

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#768]
The maintenance brothers like to download the data like that and work on it from there

**Comment by yipingbenjaminliu** [comment]
I'll take care of this

**Comment by yipingbenjaminliu** [comment]
af830b88b54425eb076f51eeaf04b2ae442e3592

**Comment by yipingbenjaminliu** [comment]
@ruthnan ,
i've created a front page access for the maintenance brothers. Please ensure that they are in the new system with user type training assistant, and they they're only in one group, the facility group. Once they log on, they should see a table of all the maintenance requests with options for filter, search, and export

![screenshot from 2018-02-28 17-38-17](https://user-images.githubusercontent.com/8671058/36822702-37f85638-1cae-11e8-8127-5cd9fd7ada34.png)

**Comment by ruthnan** [comment]
Is this already on ap.ftta.lan?

**Comment by yipingbenjaminliu** [comment]
it's in PR #777 , waiting for @billyeh to take a look to be approved

**Comment by ruthnan** [comment]
@yipingbenjaminliu we have to split maintenance requests into 3 different groups, linens, framing, and facility maintenance, so the count groups thing wouldn't work. Also, what about the trainees that have designated services with facility maintenance?

**Comment by yipingbenjaminliu** [comment]
I'll fix it up

**Comment by yipingbenjaminliu** [comment]
@ruthnan , has the maintenance requests already been split into 3 different groups?

**Comment by yipingbenjaminliu** [comment]
final commit for this issue
11a67fafe2017c1a93cacf353df5464f8199fe26

**Comment by yipingbenjaminliu** [comment]
still need to abstract and dry up the house requests module,
also need to make abstracted report template for linens and frames

**Comment by yipingbenjaminliu** [comment]
I removed all options for the maintenance brothers who are type ta and have only he facility_maintenance group

**Comment by ruthnan** [comment]
It works.
