### ISSUE TITLE
House roll missing finalize and save buttons

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#775]

**Comment by yipingbenjaminliu** [comment]
I'll look into this issue

**Comment by billyeh** [comment]
It doesn't need to be "saved" it gets updated automatically when you enter stuff.

**Comment by yipingbenjaminliu** [comment]
Make response more explicit, gotcha

**Comment by yipingbenjaminliu** [comment]
84308224467a144c0a557cbeb8423fd0c1114b66
DRY-ed up the response to data changes by using flashAJAXStatus
roll entry response entered, not sure if we need a finalized button here
