### ISSUE TITLE
Get a certificate for the server

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#778]
On someone's iPhone it gives a nasty warning right now that our site is trying to steal their information.

**Comment by JoannaRumbley** [comment]
Is this only when they type https:// instead of http:// ?

**Comment by billyeh** [comment]
Maybe? Didn't get to test anything.

**Comment by finben** [comment]
Yes, this is only when they put in https instead of http since we don't have the certificate for it to be considered secure

**Comment by billyeh** [comment]
K. I think the solution is just not to type https:// because we can't get a legit certificate for our site, I looked into it. Old server had this issue too.
