### ISSUE TITLE
Force Page needing notification and some trainee's have gotten stuck even after finalizing

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#784]
- We need something to alert trainee's as to why they are stuck on the force page

**Comment by yipingbenjaminliu** [comment]
they probably filled out the reading for this week rather than the last week. make sure they select the previous week, fill it out, and click finalize.

**Comment by yipingbenjaminliu** [comment]
#789 would address this

**Comment by yipingbenjaminliu** [comment]
#791 Would address this
