### ISSUE TITLE
Service Scheduling PDF report off

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#788]
Besides the fact that it duplicates the designated services 11 times or so, the other services also get duplicated across various days, which impacts the reporting, because it seems to be time-slot based, and the days that the services are actually assigned to trainees are not consistent with what is printed out in the Service Scheduling Report PDF. e.g., Basel is assigned to breakfast prep on the 27th and 3rd, but he's actually on restroom cleaning for those days.

**Comment by yipingbenjaminliu** [comment]
@iamsitting , could you do a dumpdata and upload it to he Dropbox? I can load then load it onto my local and fix the reports.

**Comment by iamsitting** [comment]
@yipingbenjaminliu live server dump is in dropbox: attendance project > test data > ap****.sql

**Comment by iamsitting** [comment]
@yipingbenjaminliu maybe you could look at #787 too.

**Comment by yipingbenjaminliu** [comment]
@iamsitting , I'll take a look

**Comment by yipingbenjaminliu** [comment]
@iamsitting , i'm running into a bunch of errors for the sql dump, could you use django's dumpdata into json format please? the sql file doesn't consider model dependencies along with files usages for badge links, it's throwing things off...

**Comment by billyeh** [comment]
What kind of errors? I did `psql djattendance < ap_03_01_2018_135319.sql` and it worked no probs.

Had to `dropdb djattendance` and `createdb djattendance` first

**Comment by yipingbenjaminliu** [comment]
It's throwing the error saying that the user id is not found. I cleared the db first. I'll take a closer look at it later today.

**Comment by yipingbenjaminliu** [comment]
@billyeh , errors got cleared up by fiddling around with migrations.

@ruthnan , could you take a screenshot of the duplicates problem? I'm looking at the service reports and I'm spotting a few issues but I can't seem to find the duplicates

**Comment by iamsitting** [comment]
@ryanli633 is this fixed? If so, you can close this issue.

**Comment by jontey** [comment]
It's fixed

**Comment by billyeh** [comment]
The service schedulers said it's still off.

**Comment by yipingbenjaminliu** [comment]
I'll take a look at it. What's the specific detail of it being off?

**Comment by jontey** [comment]
Some people have their services placed in the wrong category columns.

**Comment by billyeh** [comment]
2ba0374b05e4ac904bb70f94cca97b3e4ce186a9 report should be good now.
