### ISSUE TITLE
Investigate AnonymousUser exceptions on live server

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#793]
We get a lot of errors with AnonymousUser trying to access pages on the live server. Weird issue where it seems like sometimes trainees login but they're still AnonymousUser which I've also seen live on some trainees' devices.

**Comment by yipingbenjaminliu** [comment]
Private browser? I'll look into this

**Comment by billyeh** [comment]
I don't think we should worry too much for now. Doesn't seem to be happening as much (last few were me).

**Comment by billyeh** [comment]
This is probably because people have the page/url cached on their browser and reload it but their session has expired so they're logged out. Should login-protect pages (redirect if not logged in)
