### ISSUE TITLE
Can we do something about the Training Assistant group?

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#796]
like in the leaveslips model, this part could be changed to check the training_assistant permission group or no? TA = models.ForeignKey(TrainingAssistant, blank=True, null=True, related_name="%(class)sslips")

That way, the Saturday brothers and kitchen staff who are "TAs" wouldn't show up in the list of who you fellowshipped with.

**Comment by yipingbenjaminliu** [comment]
PR #797 clears this up
