### ISSUE TITLE
Class Rolls Needs Study Rolls

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#801]
- [x] Add Thursday and Saturday Study Rolls 1b5f772d8839693d4ff561a52d2a3fd57491d518
- [x] Current roll shows only Greek II (needs to show German, Greek I, and Character, etc.)
- [x] Freeze the top few rows for convenient roll input.
- [x] Option to order by last name
- [x] When hovering over row, the name is opaquely highlighted (can't see the name)

![screen shot 2018-03-03 at 1 10 29 pm](https://user-images.githubusercontent.com/8170930/36939364-74e53a7e-1ee4-11e8-9773-8864907592df.png)

**Comment by ruthnan** [comment]
Greek I, German, and Character just need people in the class. So AMs need to assign the students. When I put a trainee in Greek I, the class shows up in the Class Table.

**Comment by yipingbenjaminliu** [comment]
who's working on this?

**Comment by iamsitting** [comment]
It's up for grabs.

**Comment by yipingbenjaminliu** [comment]
I'll take it

**Comment by yipingbenjaminliu** [comment]
@iamsitting , anything else pressing over there?

**Comment by iamsitting** [comment]
@yipingbenjaminliu not really, we have jontey working on service scheduling.

**Comment by yipingbenjaminliu** [comment]
Hallelujah Jesus

**Comment by yipingbenjaminliu** [comment]
#831 should solve this.
