### ISSUE TITLE
Web Access Requests

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#802]
Add a continue button. So if something happens with the firewall, they can reopen, or continue, the request.

Also:

- [ ] A "Pause" button? Wants a "show expiration" notification.

- [ ] An "Edit" button, so trainees can edit incorrect leave slips after submitting them

**Comment by JoannaRumbley** [comment]
Also a "Pause" button? Wants a "show expiration" notification.

**Comment by billyeh** [comment]
#633
