### ISSUE TITLE
Audio Request Page Not Working

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#803]
Page is blank when I click "Audio."

Maybe it worked partially before. A bug fix request said the "Select a class" button didn't work because no list showed up. I'm guessing that was because data was missing... (The slip was written on 3/1/18)

**Comment by billyeh** [comment]
Yeah, I got the wrong directory for audio files

**Comment by billyeh** [comment]
It works now! 😮
