### ISSUE TITLE
YPC Team Monitor has ugly roll page

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#809]
![ftta___ypc_rolls](https://user-images.githubusercontent.com/23424787/36940823-239107ee-1f01-11e8-8af6-85d1739056bf.jpg)

This is what Dennis sees when he takes roll for YPC. He shouldn't see people who aren't in children's or yp teams. Also, toggle should not be available for second years, since those trainees don't show up on his roster anyway.

**Comment by yipingbenjaminliu** [comment]
1ca24c18f2829ee5548833f5489b36f8589dfc7a would fix the display for none children or YP trainees
interface-wise if it's usable, we'll leave it as is for now
there may be some second years that are on self attendance

we can add some controls to the front end for filtering a little later
