### ISSUE TITLE
Trainee landing page tardy/absence count

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#816]
Finish TODO in accounts/models for function get_attendance_record use for calculating unexcused absence and tardies.

Consider case where there's two records of the same roll for the same trainee, one by the trainee another by the AM. Consider how to reconcile and who's to take.

**Comment by billyeh** [comment]
Yeah, this is kind of a problem also because of https://github.com/attendanceproject/djattendance/blob/ee09c539cb7b2b29f2f6cc0b32098d192f4974b2/ap/attendance/serializers.py#L22-L45

**Comment by yipingbenjaminliu** [comment]
This is just an issue we need clarification from the TAs, before the roll is finalized, if there's two conflicting rolls, which one should we use?

**Comment by billyeh** [comment]
fc009c9 addresses this.

The audit functionality where multiple people can submit a roll for a person for an event needs some fine-tuning. People expect that when they or an AM submits a roll for them it should reflect on their attendance summary.
