### ISSUE TITLE
Audio Request page

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#820]
The fix to #803 Looks great! One thing:
We can't really see the audio player on the bottom of the page (of Week 0) since the boxes of options/classes are covering it.
![image](https://user-images.githubusercontent.com/33075368/36953849-bc0b42f6-1feb-11e8-903e-418063b03c34.png)

**Comment by yipingbenjaminliu** [comment]
@billyeh , that looks so slick. like legit it bomb. props props

**Comment by yipingbenjaminliu** [comment]
#821 should address this

**Comment by billyeh** [comment]
😄
