### ISSUE TITLE
Mar5 Overview of Issues From Meeting With Jerome

### ISSUE THREAD

**Issue by finben** [attendanceproject/djattendance#827]
Dear All, 
This is a rough sketch of issues that came up in our meeting with Jerome. If you need more details on items come ask myself, Bill, Carlos, Ruth, Bridget, or Priscilla as we were all in the meeting and may have more details then I have included here. We will have another meeting with Jerome Monday so if you can check these off as we take care of them it makes it easier to give a status update next week. 

Feel free to create additional issues out of these as needed as well as edit this post as needed. Lets try and focus first on the high priority items and if you see anything that should be marked high priority and is not please mark it as high priority.

Grace be with you! 

LEAVE SLIPS
- [ ] **HIGH PRIORITY** When a TA processes a leave slip they should automatically go into the next leave slip in their list instead of back out to list view. As of now Jerome says it is taking them twice as long as it should to process leave slips without this functionality.
- [ ] **HIGH PRIORITY** Leave slip detailed view for the TA's coloring scheme is confusing if a trainee has multiple leave slips it is confusing do to light red vs slightly less dark red for the TA's to know what events the current leave slip is for
- [ ] **HIGH PRIORITY** All leave slip fields need to be completely editable by the TA's including the events themselves. 
- [ ] MEDIUM PRIORITY TA detailed view of a leave slip needs to have a box to hit "does not count against perfect attendance". This box should be invisible in the trainee views. 
- [ ] Transferring leave slips. TA sisters are linked to TA brothers and we need to get the list from Jerome. Then pair up defaults so that they push leave slips along to their TA. However, while the field should be filled out by default with their paired TA they should be able to change the TA if needed
- [ ] TA sisters really need three options on Leave Slips. They need 1. a way to save, 2. a way to approve/transfer and 3. a way to transfer only. This does not deny the slip but does let the TA know that the TA sister does not think that the slip should be approved
- [ ] A way to bulk approve leave slips for TA sisters instead of one at a time
- [ ] Currently, informed TA is where the leave slip is going. However, informed TA should not do anything to where the leave slip goes but only allow the TA see who the trainee informed
- [ ] Withing the detailed view of a leave slip there should still be a way to see what time the trainee submitted the slip including the time stamp to see if trainees are submitting leave slips in class
- [ ] The little circles in leave slips status need to have color for more clarity. Currently just empty or filled black circles. This should be across TA and trainee views
- [ ] Trainee's need to be able to fully edit their own leave slip as long as the leave slip is still in pending status. However as soon as the leave slip moves into fellowship, approved, or denied status they should no longer be editable
- [ ] Night out and meal out options should have "last time out" next to the selection in the Trainee view when they are submitting leave slips
- [ ] Four categories of leave slips submitted by trainees "Conferences, Team Trips, Services, and Fellowship" should all automatically select the field "does not count against perfect attendance"
- [ ] TA leave slip list view for TA abbreviations are not consistent in dates. For example it says Feb but then says March instead of Mar

ATTENDANCE 
- [ ] Events on the trainee schedule need to have a start time that is shown when a trainee hovers over an event. Reason Trainee's are confused of times for events because the schedule does not specify when you look at the schedule. The old server does a good job of this when you hover over giving information such as start time of event, if there are leave slips the reason and the leave slip number

ROOM RESERVATION
- [ ] Continue to work on moving room reservations fully to the new server and connect to TV's
- [ ] Number pending is not matching actual number of room reservations

REQUESTS
- [ ] Add permissions to allow trainees to submit linens, framing requests. 
- [ ] Add dishware requests to linens since they are taken care of by the same service team
- [ ] Maintenance request brothers still want a csv export 

ROLLS
- [ ] **HIGH PRIORITY** TA's not able to update a trainee's attendance for the previous week. After Tuesday the submit role is not working. This is probably permissions related because Attendance Monitors are still able to do this. The TA's need this capability
- [ ] For House Rolls Need a finalize button also a save "dummy" button that does nothing but gives the user an illusion of action. Currently it automatically saves every time they update which we still want to keep it this way but the button is just to give them assurance the roll is saved. We may need to have a further discussion around this item as it may just be a matter of getting the users used to not having save buttons.
- [ ] Need a way for second year trainee's to moved back between 1st and 2nd year attendance as needed. Since some 2nd years are on 1st year attendance. 
- [ ] Still when 2nd years finalize attendance there is very little feedback that it worked. Need stronger feedback

ABSENT TRAINEE ROSTER
- [ ] Cron job sending the email is sending on Mondays 
- [ ] Also the email is shown as being sent from APserver instead of Absent trainee roster

BIBLE READING
- [ ] Bible reading finalize button having issues still expecting issues tomorrow. 

WEB ACCESS REQUESTS
- [ ] **HIGH PRIORITY** Apparently, marking for fellowship is approving automatically. However we need to look into this to see if it is so (Acts 17:11)
- [ ] The urgent is not marked red as is consistent with how we mark urgent on the rest of the site. 
- [ ] From TA detailed view of a web access request there is a field saying "Urgent False" change wording to just "Urgent"

TA LANDING PAGE
- [ ] Leave-slip number is not matching the actual numbers of leave-slips
- [ ] In general the TA's would like to see their own number of items as well as in parenthesis the number of total items. Ex. Web Access Requests 5 (230). The only exception is leave slips which should only show the TA's personal number of slips
- [ ] Remove housing from TA landing page as they do not need this

ANNOUNCEMENTS
- [ ] If a TA creates an announcement there is a status field that should not be seen anymore from that view since it should always be approved
- [ ] In the TA list view they are seeing trainee email and name. No need for email. Just have this be consistent with others of name only
- [ ] Get rid of comment button from TA list view for consistency across site. Also button is not working anyways and unnecessary as they can input comment in detail view

TA LIST VIEWS
- [ ] MEDIUM PRIORITY All of the TA list views of things like web access requests, leave slips etc they are all sorted starting with approved so they literally have to scroll past all of the approved to get to pending. The correct sort order needs to be the following (Pending, Marked for Fellowship, Approve, Deny) 
- [ ]  In the future we need a way to filter the TA list views because they have to scroll excessively and try to find items on their list views. 
- [ ] On TA list views we can take off approved and denied things such as leave slips etc but only if they are able to still see these when they search a persons name. This is what the old server does now
- [ ] Trainee names on the TA list views should be made more visible
- [ ] Across site need delete options for things like web access requests etc. Currently no ability to do so.

MISC
- [ ] Collect data on random device issues and fix. For example when Bridget Duo uses her iPad she cannot see personal attendance

**Comment by billyeh** [comment]
see #828

**Comment by finben** [comment]
Yeah, that's why I closed so people would not get confused by two lists

**Comment by billyeh** [comment]
Just wanted to link them in case cuz it seems this one has a few more details/hope we got all the issues merged into the one that's currently open.
