### ISSUE TITLE
Feedback (Updated 03-17-18)

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#828]
Priority Key
HP = High Priority
MP = Medium Priority

- **Leave slips:**
- [x] Better feedback for Leave Slip submission. (@davidhtien) 2e43ec1 https://github.com/attendanceproject/djattendance/pull/847
@billyeh , maybe make something similar to what bible_tracker does right now, flash a save. take a look at https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L480-L482
https://github.com/attendanceproject/djattendance/blob/eaa38a736f934c3a2e9e23db18c3176f8bc65ab6/ap/bible_tracker/templates/bible_tracker/index.html#L271-L272

- [ ] TA informed should be a field that doesn’t affect where the leave slip goes 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- [ ] **MP** For leave slips TA brother / TA sister pairs linked by default for leave slip transfer. Use pairings from old attendance server

- Assigned TA:
  - [ ] should be trainee’s default TA or transferred TA (Trainees don’t see this) @billyeh 
  - [x] Leave slip count is wrong on TA landing page 1bb420f52ee0c27480ad6ac2e521199da1a6741f
  - [ ] Filter out Saturday TAs

- TA sisters:
  - [ ] Transfer and approve button (automatically transfers to linked TA brother)
  - [ ] Save button (allows TA sister to make edits to leave slips, including TA informed)
  - [ ] Transfer button (allows TA sisters to transfer to linked TA brother without approving it)

- [ ] Leave slip submission acknowledgement disappears too quickly. 

- [x] After approving leave slip, redirect to next pending leave slip 8b1ec8ceca41635aae918984ed5cdc62bf23b798

- [ ] Allow all leave slip fields to be edited by TA @iamsitting 0768dae38a1cadac66e1d0fd464c8da2aa65b27e

- [ ] Allow trainees to access previous Leave slips. Maybe a ListView for trainees.

- Extra field:
  - [ ] “Does not affect perfect attendance” (Automatic for Conferences, team trips, house meals, service, fellowship, and allow for TA override)

- [x] Need more obvious event highlighting when editing/reviewing leave slips 94b37d7f0e319cd962c02ca21248fa59a54c94a8

- [x] Show submission date on leave slip detail @samvictor232 76354fa900280d7268a56cdb02a5b55fe60ad1bc

- [x] Add “last slip” to meal/night out, even if there isn’t one on record 652eb48bc

- [x] Hover over event for start time, event name, and reason 5119ce9

- [x] On ListView, Month abbreviations are not consistent @samvictor232 50d2da0c62eea24157c3a2b4661322f572a72864

- [ ] Group slip approve/fellowship/deny buttons need to be bigger @samvictor232

- [x] Color code Leave Slips status codes on personal attendance @bdou 448d6ce9449b5e9c588e64f1e41076c44ba5b641
- [x] Trainees should be able to edit their own leave slips as long as the leave slip is still in pending status

- **Rolls:**
- [ ] House and Team Roll (make a dummy save, and finalize button) @priscilagonzalez 

- [ ] Need unfinalize roll button for attendance monitors and TA's

- [x] Team Roll is not auto-saving

- [x] 2nd year rolls finalize button has vague feedback

- [ ] Implement way for 2nd years on first attendance

- [x] TA needs permission to submit rolls 7a31214191df594c151d1a89182b574fe8f558ea

Trainee items:
- [x] Allow trainees to see linens requests for trainees. fbc394c

- **Life-studies:**
- [x] Search function for Life Study ListView 7a8dd6d9cf5475a5ce2cc13d6ff5167300cc63d0

- [x] Populate with life-study books

- [x] Decrease Life Study Penalty ce0a11e

Web Access Requests:
- [ ] For TAs: order by status (Pending, Fellowship, Approved, Denied) then by submission date @bdou

- [x] Urgent text should be red - working; but only urgent pending requests have red text. @bdou

- [x] Urgent value is not shown for nonurgent request detail views @bdou 

- [ ] Bug: Mark for fellowship actually approves

Attendance:
- [x] Allow TAs to change self-attendance field for 2nd year trainees 0da336236ef01c9087cb4140395d84f9e8bc4fab

**Room Reservations:**
- [ ] Requests do not match landing page count

- [ ] When TA is editing a room reservation request the title page is "FTTA | Room Reservation" but on other pages it is pluralized. Just pluralize this

- [ ] Rooms are not in alphabetical order after editing available rooms

- [ ] Schedule needs to be imported into the new attendance server

- **TA Landing Page:**
- [ ] TA's should see their personal number of items as well as a total number of items. Ex. web access requests 5 (390). The only exception is leave slips which should only show the TA's personal number of slips

- [x] Remove housing from TA landing page as they do not need this 0815c9b

TA List Views
- [ ] Get rid of comment button from TA announcement list view for consistency across site. 

- [ ] All TA list views need the following sort order (Pending, Marked for Fellowship, Approve, Deny) to stop them from having to excessively scroll. Secondary sort needs to be time submitted based

- [ ] Trainee names need to be made more visible (increase font size)

- [ ] Across site lists need delete options for items from TA list view

- **Bible Reading Tracker**

- [ ] Bible reading note says trainee needs to see a TA brother to finalize Bible reading. This should no longer be the case since force page will take care of this

- **Absentee Trainee Roster:**

- [ ] Text change from "Everyone is Present!" text to "All Present"

- [x] Absent Trainee Roster is not needed on Monday (related: # days on report should not reset after Monday) 4601138180c00912a5c41378b850fac9762f1659

- [x] Change Email account name to something better than “AP Server” d650605f2

- [x] Remove "Coming to Class" as an option 71be9bb48d346f84f24e102a2839a3493d330154

- **Announcements:** eb42242506ed2c1933c171d1184fa4014efe3820
-  [x] Auto-approve announce request for TAs (Hide status field for TAs)

- [x] Bug: Submitted by “None” when it’s submitted by a TA

- [x] In TA list view the submitted by includes trainee email inconsistent with other list views. Email not needed

- [x] fix switch identity page trainee selector

- **Other:**
- [ ] **HP** FTTA-XB application is needed on the new attendance server @ryanli633 

- [ ] **MP** HC surveys, the TA's cannot see anything about what the HC survey asks, to edit, or to delete an HC survey. 

- [ ] **MP** Graduation module is missing graduation invitations, DVD numbers, and remembrance pages

- [ ] Add dishware requests to linens since they are taken care of by the same service team

- [ ] House Requests, Room Reservations, Life Studies, Class notes, are user (Trainee or TA) specific.

- [x] Maintenance request brothers want a csv export to fit their current workflow af830b88b54425eb076f51eeaf04b2ae442e3592

- [ ] Trainees with designated services need to be able to input their service hours (ex Greg Lee Transportation)

**Comment by finben** [comment]
Migrated all of these issues to #874
