### ISSUE TITLE
Attendance office hours 3/7

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#833]
- [x] Submitting a new roll for someone doesn't change the status (duplicate roll issue, #816?)
- [x] Personal slip -- cannot edit the event to which it's related (?)
~~Deleting roll deletes the related leave slip on the admin (foreign key like locality)~~ a leave slip must be attached to a roll.
- [x] Group slip admin page picking trainees doesn't work as well as the schedule trainee picker (?)
- [x] Search leave slips by pk on admin fc58b45fc5498780b3e51bcd821386f72dc6fd09

**Comment by yipingbenjaminliu** [comment]
For IndividualSlip, you can edit what event it's related to by clicking into it. In the summary tab, when your mouse is over the leaveslip and you click on it, it pulls up the personal slip edit for that leaveslip.

I'm not sure why you're able to delete rolls after a leaveslip is submitted. If you remove the absent or tardy or whatever, it should just edit the roll to present. There shouldn't be a case where you are allowed to delete a roll associated with a leaveslip, you can edit the roll status but not delete the record.
