### ISSUE TITLE
Generating leaveslips

### ISSUE THREAD

**Issue by ruthnan** [attendanceproject/djattendance#834]
- [x] Just generate one leaveslip for all the trainees on that service. e.g., one service leaveslip is generated for stars, another one for all the trainees, brothers, and sisters, or people in certain categories like plus one services. 3b60714e1b14f453bfb077f946fd170c6f4a69af
- [x] Service assignment under group leaveslips has a massive dropdown menu. Add search bar. e0cd4255b9a566a0a2de8553df49eaceab59ecb4

**Comment by yipingbenjaminliu** [comment]
addressed via #837

**Comment by yipingbenjaminliu** [comment]
Wait till PR goes through
