### ISSUE TITLE
When service schedulers update designated services it should update groups

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#863]
for permissions, to see links and stuff.

**Comment by ruthnan** [comment]
i'll do it

**Comment by JoannaRumbley** [comment]
Also, Designated services are not listing everyone (ex: only 2 brothers – Greg Lee and Ryan Holt – are listed for transportation) http://ap.ftta.lan/services/designated_services_viewer

**Comment by ruthnan** [comment]
closed in #958
