### ISSUE TITLE
datetime is None for HC survey

### ISSUE THREAD

**Issue by billyeh** [attendanceproject/djattendance#883]
https://mail.google.com/mail/u/3/#inbox/1624ec71f36157f7

similar to 59264930ee02bc40a3bb4a22b4d4f339def666fe?

@billyeh, what's this one on?

**Comment by billyeh** [comment]
Graduation https://mail.google.com/mail/u/3/#inbox/1624e8e2c67ecf92

**Comment by yipingbenjaminliu** [comment]
yea...I've fixed it in grad_fix already.

**Comment by billyeh** [comment]
Oh, ok. Yeah I wasn't sure because this is HC survey, not grad?

**Comment by billyeh** [comment]
Also might as well throw in https://mail.google.com/mail/u/3/#inbox/1624f5749c4bc405 to here
