### ISSUE TITLE
Bible Reading Tracker - Unclick the box

### ISSUE THREAD

**Issue by JoannaRumbley** [attendanceproject/djattendance#890]
Bible reading needs an option to unclick the C M N boxes if pressed by mistake (if they accidentally marked a future day). This will minimize human error when people enter their Bible reading.

**Comment by finben** [comment]
Closing for now. It is up to the trainee's to re-select other options before submitting when they are finalizing on Mondays.

**Comment by finben** [comment]
I actually made this mistake tonight lol and marked my next week all "C" but then I can just change them all to "N" until I actually do the readings since I have not read yet so this is also a very good solution for trainee's that make this mistake.
