### ISSUE TITLE
TA View Life Study Report Print Out is Inaccurate

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#895]
br Andrew isn't able to print this out because of the inaccurate information. There are trainees with no life studies that are named on the list. @yipingbenjaminliu

<img width="1432" alt="screen shot 2018-03-24 at 2 10 54 pm" src="https://user-images.githubusercontent.com/29343365/37869049-e15f6c8a-2f6d-11e8-8745-eddaa92ba3c3.png">

**Comment by iamsitting** [comment]
@yipingbenjaminliu says he "fixed" it.
