### ISSUE TITLE
Trainee: Leave-Slip Summary Page

### ISSUE THREAD

**Issue by xuefeizheng** [attendanceproject/djattendance#916]
Please follow the mockup page's design. Many have commented it is hard to read the leave slips in the current server. 

- Notice that you can **select** category under "TOTAL" (with orange highlight) and the category will appear underneath. 

- Please use **EVENT (e.g. Triune God)** instead of TIME (3/22/18 8:30 - 3/22/18 9:00) 

- The **[X]** for deleting a leave-slip is confusing (looks like a rejected leave-slip). There's **no need for a delete button** since the leave-slip can be edited once clicked. The user can delete it when they open the leave-slip. 

- Please follow the designed **leave-slip status buttons** for all pages related.[ ICO files here at Dropbox](https://www.dropbox.com/home/attendance%20project/djattendance/design%20-%20miriam/ico%20files/Leave-Slip%20Status).

<img width="1025" alt="screen shot 2018-03-25 at 4 44 22 pm" src="https://user-images.githubusercontent.com/33186134/37881365-d813e4c4-304b-11e8-8127-a7b8b7238a2d.png">

 
**MOCKUP PAGE**
![trainee_leaveslipsummary](https://user-images.githubusercontent.com/33186134/37881151-712c3c32-3048-11e8-8454-aa1b1dfef18a.jpg)

**CURRENT SERVER**
<img width="1314" alt="screen shot 2018-03-25 at 4 20 55 pm" src="https://user-images.githubusercontent.com/33186134/37881284-7e8bc594-304a-11e8-8f0f-45b3cb2ee4ff.png">

**Comment by finben** [comment]
Several things here. Please note.
1.  We are going to go with a different design for the roll status see attached.
2. The event is showing up correctly on personal leave slips now. Group leave slips are still time based but they may have to remain that way
3. I think right now that X is the only way to delete the leave slip. But we should move that option within the leaveslip

![spectacle x11775](https://user-images.githubusercontent.com/15247726/38582078-841a3042-3cc3-11e8-8851-3559ade56017.jpg)
