### ISSUE TITLE
Highlight color should be #C2B59B (tan)

### ISSUE THREAD

**Issue by caricchow** [attendanceproject/djattendance#962]
When the user selects a row, the color should be tan - HEX #C2B59B, not blue. Thank you!

<img width="1161" alt="screen shot 2018-03-31 at 5 08 29 pm" src="https://user-images.githubusercontent.com/29343365/38169117-f992c4d4-3515-11e8-9081-a8daf85055c5.png">

**Comment by ruthnan** [comment]
Would this tan be the same tan as the one differentiating the rows in the table?

**Comment by caricchow** [comment]
We will change the highlight color to medium blue with dark gray font.
