### ISSUE TITLE
Leaveslip Admin View Broken, immediate priority

### ISSUE THREAD

**Issue by yipingbenjaminliu** [attendanceproject/djattendance#970]
Live server detail view of an individualslip is broken.

**Comment by billyeh** [comment]
Fixed this yesterday https://mail.google.com/mail/u/3/#all/1628899b7603f0c5

Once we set on_delete=SET_NULL on everything when an event was deleted the rolls weren't. I pushed a fix to #919 3ffb817 just check if there's an event for the roll before attaching it to a leave slip.

**Comment by billyeh** [comment]
Never mind, I have no idea what's wrong with the admin site.

**Comment by yipingbenjaminliu** [comment]
#1105
