### ISSUE TITLE
Leave slip Rolls HUGE Problem

### ISSUE THREAD

**Issue by iamsitting** [attendanceproject/djattendance#975]
Individual Leave slips attached to rolls that don't belong to submitting trainee.
(I.e Trainee1 submits leave slips for Rolls corresponding to Events 1, 2, 3. But leave slip is attached to roll 1 for Trainee1 and rolls 2 and 3 belonging to Trainee2) @yipingbenjaminliu 

Perhaps look at
https://github.com/attendanceproject/djattendance/blob/e3bf370b8569f578e0f1811bb21932fce0641faf/ap/attendance/models.py#L63-L81

https://github.com/attendanceproject/djattendance/blob/e3bf370b8569f578e0f1811bb21932fce0641faf/ap/leaveslips/serializers.py#L35-L96

**Comment by yipingbenjaminliu** [comment]
#1105 , patched up leaveslip seralizer as well
