### ISSUE TITLE
Exam module fixes

### ISSUE THREAD

**Issue by ksungreborn** [attendanceproject/djattendance#979]
Exams to do
- [x] view exam score on trainee side after exam is closed  (done in branch exam-fixes)
- [x] training class in edit not showing right training classes (done in branch exam-fixes)
- [ ] finalize for grade -> after changing exam section/question BUG, trainee can’t see exam score after finalized/saved, and exam is finalized on ta side (done in branch exam-fixes)
- [x] save —> show exam score on grading page (not just for finalize)  (done in branch exam-fixes)
- [x] grade for paper response - need way to save/finalize and show on grading page (done in branch exam-fixes)
- [x] decimals needed for section (done in branch exam-fixes)
- [x] make number of exam questions required to answer for each section (done in branch exam-fixes)
- [x] admin instructions appear on trainee side should not be bold with caps (done in branch exam-fixes)
- [x] edit exam page —> preview test (done in branch exam-fixes)

Other less priority
1. open for makeup for specific trainees
2. generate makeup pdf - trainees that haven’t taken the test yet
3. sort functions (what has been graded, what hasn’t)

**Comment by yipingbenjaminliu** [comment]
addressed via #1252
